### ISSUE TITLE
Getting bgp-policy.yang:12: error: module "routing-policy" not found in search path error.

### ISSUE THREAD

**Issue by sashankh** [mbj4668/pyang#127]
Getting this error when trying to run it on 

https://github.com/YangModels/yang/blob/master/experimental/openconfig/policy/routing-policy.yang

user@:~/YANG_MODELING/yang/experimental/openconfig/policy$ pyang routing-policy.yang 
policy-types.yang:11: warning: imported module ietf-inet-types not used
user@:~/YANG_MODELING/yang/experimental/openconfig/policy$ pyang policy-types.yang 
policy-types.yang:11: warning: imported module ietf-inet-types not used

**Comment by mbj4668** [comment]
The error message tells you what the problem is.
