### ISSUE TITLE
include 

### ISSUE THREAD

**Issue by gpshead** [mbj4668/pyang#134]
Please include PyPI classifiers in your setup.py so that the package is indexed and declared which python versions it supports as well as its license.

The valid strings are:  https://pypi.python.org/pypi?%3Aaction=list_classifiers

They go in the classifiers=[...] argument to setup() in setup.py.

         'Programming Language :: Python :: 2',
         'Programming Language :: Python :: 2.7',
         'Programming Language :: Python :: 3',

One License :: one, etc.

**Comment by mbj4668** [comment]
I will start to use pypi for the next release.
