### ISSUE TITLE
validate leafref cross references

### ISSUE THREAD

**Issue by ing-wher** [mbj4668/pyang#135]
Hello,

I was wondering if yang2dsdl can validate a leafref in one module referencing a leaf in a different module (not an augment).

First module is leafrefs.yang :+1: 

module leafrefs {
  yang-version  1;
  namespace "http://example.com/leafrefs";
  prefix "lr";
  organization "Example";
  contact
    "abc@example.com";
  description
    "Leafrefs";
  revision "2015-02-10" {
    description "Initial revision";
  }
  list l1 {
    key "name";
    leaf name {
      type string;
    }
  }
}

Second module is leafrefs2.yang : 

module leafrefs2 {
  yang-version  1;
  namespace "http://example.com/leafrefs2";
  prefix "l2";
  import leafrefs {
    prefix "l";
  }
  organization "Example";
  contact
    "abc@example.com";
  description
    "leafrefs2";
  revision "2015-02-10" {
    description "Initial revision";
  }
  list l2 {
    key "id";
    leaf id {
      type uint8;
    }
    leaf l1-ref {
      type leafref {
        path "/l:l1/l:name";
        require-instance true;
      }
    }
  }
}

Data to be verified:

<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <l1 xmlns="http://example.com/leafrefs">
    <name>local</name>
  </l1>
  <l2 xmlns="http://example.com/leafrefs2">
    <id>1</id>
    <l1-ref>abc</l1-ref>
  </l2>
</data>

Thanks,
Helen

**Comment by ing-wher** [comment]
The XML didn't show up correctly in the previous post.  Here's the data to be validated that shows up correctly, at least in "Preview".

<?xml version="1.0" encoding="utf-8"?>
\<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  \<l1 xmlns="http://example.com/leafrefs">
    \<name>xyz</name>
  \</l1>
  \<l2 xmlns="http://example.com/leafrefs2">
    \<id>1</id>
    \<l1-ref>abc</l1-ref>
  \</l2>
\</data>

**Comment by llhotka** [comment]
Yes, yang2dsdl can validate this, provided that both modules are supplied, either on the command line or in a hello file. See also issue #131.

**Comment by sahilshah27in** [comment]
Hi there,
I am trying to validate this scenario using both the files. I created the xml-skeleton using both the files.

pyang -f sample-xml-skeleton test3.yang test2.yang -p /schema/imports/ -o sample.xml

**TEST3 YANG:**
module test3 {
  yang-version 1;
  namespace "http://com/xxx/test/test3";
  prefix test3;

  import com-xxx-test-test2 {
    prefix test2;
    revision-date 2017-10-03;
  }

  organization
    "XXX, Inc.";
  contact
    "XXX";
  description
    "Test3 Yang File";

  revision 2017-10-03 {
    description
      "Initial Revision.";
  }
  container container1 {
    leaf leaf2 {
      type leafref {
        path "/test2:leaf1";
      }
    }
  }
}

**TEST2 YANG**
module com-att-test-test2 {
  yang-version 1;
  namespace "http://com/att/test/test2";
  prefix test2;

  organization
    "AT&T, Inc.";
  contact
    "AT&T Network On Demand Design";
  description
    "Test2 Yang File";

  revision 2017-10-03 {
    description
      "Initial Revision.";
  }

  leaf leaf1 {
    type string;
  }
}

**sample.xml created**

<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><container1 xmlns="http://com/xx/test/test3"><leaf2>abc</leaf2></container1><leaf1 xmlns="http://com/att/test/test2" /></data>

I have both the instances filled now. I want to know how to supply both the instances while validating with yang2dsdl. It seems, it accepts only 1 instance. 

If we are able to supply only 1 instance, how do we validate that the instance with the leafref to another model has valid data?

Regards
Sahil
