### ISSUE TITLE
yang2dsdl not finding "mktemp" and "xsltproc"

### ISSUE THREAD

**Issue by mrehder** [mbj4668/pyang#138]
Runnning yang2dsdl on Windows 7.
The program complains that it can't find mktemp and xsltproc.
It seems that either the installation is broken or documentation is missing about a dependency on other packages (which need to be installed). 
How would I fix this issue?

**Comment by shinn1982** [comment]
+1 i have the same problem...

**Comment by llhotka** [comment]
yang2dsdl is a Unix shell script that was never intended to be run on Windows. Dependency on xsltproc and xmllint/jing is mentioned in the manpage.

I don't use Windows but if somebody writes a corresponding Windows script, we'll be happy to include it in pyang distribution.

**Comment by mrehder** [comment]
ok, so then what tool in Windows could I use to validate an XML instance of a YANG module?

**Comment by llhotka** [comment]
You need a RELAX NG validator and XSLT 1.0 processor, I am sure there are several choices available for Windows. Then it should be easy to perform the same steps as in the yang2dsdl script. Details are described in [DsdlDetails](https://github.com/mbj4668/pyang/wiki/DsdlDetails).

**Comment by mrehder** [comment]
Got everything working following the wiki.
It seems that “when” xpath statements are not validated. Is that intentional? Future feature?

**Comment by llhotka** [comment]
No, "when" is supported. Can you send me an example where it doesn't work?

**Comment by mrehder** [comment]
I did get an error eventually reported but I can’t figure out how to fix it.

YANG
    leaf physical-object {
      type boolean;
      mandatory true;
      description "Indicates if the component is a physical object or not.";
    }
    container physical-properties {
      uses physical-attributes;
      when "../physical-object=true";
      description "Physical properties of the component.";
    }

XML
      <physical-object>true</physical-object>
      <physical-properties>
        <height>933</height>
        <width>431</width>
        <depth>533</depth>
        <rack-units>21</rack-units>
        <power-consumed>155</power-consumed>
        <cooling-required>530</cooling-required>
      </physical-properties>

  <svrl:active-pattern id="id179079" name="id179079"/>
  <svrl:fired-rule context="/nc:data/deviceDefinition:device-definition/deviceDefinition:object-list/deviceDefinition:physical-properties"/>
  <svrl:failed-assert test="ancestor-or-self::*[processing-instruction('dsrl')] or (../deviceDefinition:physical-object=deviceDefinition:true)" location="/*[local-name()='data' and namespace-uri()='urn:ietf:params:xml:ns:netconf:base:1.0']/*[local-name()='device-definition' and namespace-uri()='http://amdocs.com/OSS/YANG'][1]/*[local-name()='object-list' and namespace-uri()='http://amdocs.com/OSS/YANG'][1]/*[local-name()='physical-properties' and namespace-uri()='http://amdocs.com/OSS/YANG']">
    <svrl:text>Node "physical-properties" is only valid when "../deviceDefinition:physical-object=deviceDefinition:true"</svrl:text>
  </svrl:failed-assert>


There are other when statements that are not reported as failing when they are clearly violating the expression.
For example,

YANG
  grouping physical-attributes {
    description "The physical properties of a component.";

    leaf height {
      when "../../component-class=Chassis";
      type uint32;
      units "millimeters";
      description "Height and rack units need to be proportional (at 44.45mm per RU)";
    }

XML
      <component-class>Module</component-class>
      <component-category>Carrier</component-category>
      <FRU>true</FRU>
      <physical-object>true</physical-object>
      <physical-properties>
        <height>44</height>
        <width>390</width>
        <depth>406</depth>
        <component-size>1</component-size>
        <power-consumed>170</power-consumed>
        <cooling-required>0</cooling-required>
      </physical-properties>

It seems that the xpath statement is ignored if it is incorrectly formatted or not accurate.


Mike

**Comment by llhotka** [comment]
The "when" statement is wrong, it should be
```
 when "../physical-object='true'";
```
All string literal values have to be quoted because otherwise in this example the XPath processor tries to compare the values of two nodes (XML elements) namely `../physical-object` and `true`. Since the latter doesn't exist, the expression is always false.

**Comment by llhotka** [comment]
By the way, you can use the the `svrl2text.xsl` stylesheet that's also included in _pyang_ distribution for translating the SVRL reports into something readable.

**Comment by mrehder** [comment]
Ok, that explains the first case.
What about the second?
Even if the path is wrongly formatted, the expression should return false and thus declare that the presence of “height” is not allowed.

Mike

**Comment by llhotka** [comment]
I do get a validation error:
```
$ yang2dsdl physical.yin 
== Generating RELAX NG schema './physical-data.rng'
Done.

== Generating Schematron schema './physical-data.sch'
Done.

== Generating DSRL schema './physical-data.dsrl'
Done.

$ yang2dsdl -s -j -b physical -v physical-data.xml 
== Using pre-generated schemas

== Validating grammar and datatypes ...
physical-data.xml validates.

== Adding default values... done.

== Validating semantic constraints ...
--- Failed assert at "/nc:data/ph:physical-properties/ph:height":
    Node "height" is only valid when "../../ph:component-class='Chassis'"
```

Here is the complete module and instance document with which I got the above result.
```
module physical {
  namespace "http://example.com/physical";
  prefix ph;

  grouping physical-attributes {
    leaf height {
      when "../../component-class='Chassis'";
      type uint16;
    }
    leaf width {
      type uint16;
    }
  }

  leaf physical-object {
    type boolean;
    default "false";
  }
  leaf component-class {
    type enumeration {
      enum "Chassis";
      enum "Module";
    }
    default "Module";
  }
  container physical-properties {
    uses physical-attributes;
    when "../physical-object = 'true'";
  }
}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<nc:data xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
      xmlns="http://example.com/physical">
  <physical-object>true</physical-object>
  <component-class>Module</component-class>
  <physical-properties>
    <height>933</height>
    <width>431</width>
  </physical-properties>
</nc:data>
```

**Comment by mrehder** [comment]
I’m in Windows and so not using yang2dsdl.
I’m using the tools directly on an xml instance file, following your wiki page.
