### ISSUE TITLE
Deviation not working with grouping

### ISSUE THREAD

**Issue by ankitjain093** [mbj4668/pyang#147]
deviation statement is not working for grouping:

Module:
```
module m {
  container c {
    uses g;
  }
  grouping g {
    leaf l {
      type string;
    }
  }
}
```
Deviation module:

```
module d {
  deviation /m:c/m:l {
    deviate not-supported;
  }
}
```

cmd$ pyang -f yin m.yang --deviation-module=d.yang

```xml
<container name="c">
    <uses name="g"/>
  </container>
  <grouping name="g">
    <leaf name="l">     >>>>>>>>>>>>> NO DEVIATION APPLIED
      <type name="string"/>
    </leaf>
  </grouping>
```

**Comment by mbj4668** [comment]
This works as designed.  The yin output plugin takes the input file and formats its statements as YIN.
It would be incorrect to change the leaf in the grouping; the deviation is not on the grouping but on the expanded tree.

You can try -f tree instead; this plugin works on the expanded tree.
