### ISSUE TITLE
In-line grouping for yin output

### ISSUE THREAD

**Issue by ankitjain093** [mbj4668/pyang#148]
Is there a way in pyang, I can get inline grouping for yin output:

```
module m {
  container c {
    uses g;
  }
}
grouping g {
  leaf l {
    type string;
  }
}
```

cmd$ pyang -f yin m.yang

Observed output:
```xml
<module name="m">
  <container name="c">
    <uses name="g"/>
  </container>
  <grouping name="g">
    <leaf name="l">
      <type name="string"/>
    </leaf>
  </grouping>
</module>
```

Desired output:
```xml
<module name="m">
  <container name="c">
    <leaf name="l">
      <type name="string"/>
    </leaf>
 </container>
</module>
```

**Comment by mbj4668** [comment]
Hi,

No this is not possible. The current yin plugin works on the statement tree; you'd have to modify it to work on the expanded tree instead.

**Comment by redivo** [comment]
Hi.
I would like to have something like this too.

Is there some other option to have a XML representation of Yang module where the 'uses' statement is  "verbosed", just like @ankitjain093 suggested?
