### ISSUE TITLE
Select subtree via command line argument

### ISSUE THREAD

**Issue by madhavan020985** [mbj4668/pyang#150]
If my yang model tree looks like,
````python
L1
   L1.1
         L1.1.1
L2
   L2.1
         L2.1.1
````
And if i am interested in studying the internals of L2 and not L1, can i select the subtree via a nodepath
like,
pyang --subtree L2 x.yang (or) //now, L2.1 becomes the root node
pyang --subtree L2/L2.1 x.yang  //to see just L2.1.1....

Here, the example is trivial but when there are too many nodes in yang, and scrolling down to read them is really tough, this really helps.

**Comment by llhotka** [comment]
It depends on what exactly you want to do. Some plugins need a complete tree while other support such "cuts". For example, you can use `--tree-depth` and `--tree-path` options with the tree plugin to see only a certain subtree.

**Comment by madhavan020985** [comment]
thi is what i was looking for, IIhotka.. thanks, i will close this issue
