### ISSUE TITLE
pyang yang2dsdl can not use -j parameter

### ISSUE THREAD

**Issue by classcwnd** [mbj4668/pyang#151]
Hi

When I use -j, it said "bin/yang2dsdl: line 106: jing: command not found". 
I don't know how to use jing, seems it is not integrated with yang2dsdl.
I searched jing in internet, and found it is a java package. And there is no document describes how to integrate jing with yang2dsdl. 
So I would be much appreciated if you could give me more detail about jing.

Thanks,
Yu

**Comment by llhotka** [comment]
Jing is an open source  RELAX NG validator written in Java. It can be downloaded from this page:

http://www.thaiopensource.com/relaxng/jing.html

In most Linux distributions it is available as a standard package. E.g. on Ubuntu:
```
$ sudo apt-get install jing
```
On OS X it is available via homebrew.

**Comment by damianoneill** [comment]
@llhotka Guys I know this is an old issue, but I just run a 

`make test`

And get 

````bash
== Validating grammar and datatypes ...
/projects/github/pyang/bin/yang2dsdl: line 110: jing: command not found
make[3]: *** [test] Error 3
make[2]: *** [itest] Error 1
make[1]: *** [test] Error 2
make: *** [test] Error 2
````

I'm building on a mac.  

Noting the comment above that jing is available via homebrew I 

````bash
$ brew install jing
Error: No available formula with the name "jing"
==> Searching for a previously deleted formula...
jing was deleted from homebrew/core in commit 670f3f3a78:
  jing: migrate to boneyard (https://github.com/Homebrew/homebrew-core/issues/4799)
````

In the absence of a brew install can you suggest how I should set this up on a mac?

**Comment by damianoneill** [comment]
I've recreated the brew and setup a tap for jing.  If using homebrew you can install jing as follows;

`brew install damianoneill/homebrew-jing/jing`

**Comment by llhotka** [comment]
You should be able to install it directly from

https://code.google.com/archive/p/jing-trang/downloads

**Comment by damianoneill** [comment]
Thanks @llhotka that is where I'm getting it for the tap above. 

This lets me get a little further in the make test though its still not completing.  I will raise a seperate issue to avoid cluttering this discussion.
