### ISSUE TITLE
jsonxsl plugin -  type decimal64  is presented in quoted form in json

### ISSUE THREAD

**Issue by rponczkowski** [mbj4668/pyang#152]
According to https://tools.ietf.org/html/draft-lhotka-netmod-yang-json-02 decimal64 type should be mapped to a JSON number. This mean it should appear in json in unquoted form. 
Using xsl generated by jsonxsl plugin results presenting such data in quotation.
It  can be easily fixed by patch:
--- a/pyang/plugins/jsonxsl.py
+++ b/pyang/plugins/jsonxsl.py
@@ -39,6 +39,7 @@ type_class = dict((t,"unquoted") for t in
                   ("boolean", "int8", "int16", "int32",
                    "uint8", "uint16", "uint32"))
 """Classification of types suited for JSON translation."""
+type_class.update(('decimal@' + str(t),"unquoted") for t in range(1,18))
 
 type_class.update((t,t) for t in
                   ("empty", "instance-identifier", "identityref", "string"))

and that is because parsing decimal type from yang results internal notation of such type: decimal64@<fraction-digits>, which leads to not finding it inside type_class dict.

**Comment by llhotka** [comment]
Please use the latest revision of JSON encoding spec:

https://tools.ietf.org/html/draft-ietf-netmod-yang-json-04

I-JSON requires numbers that don't fit into IEEE double precision floats to be represented as strings.
