### ISSUE TITLE
Parsing errors when using pyang - xmlFAParseAtom and xmlFAParseRegExp

### ISSUE THREAD

**Issue by marspetrova** [mbj4668/pyang#155]
Hello,
I am trying to convert the configuration yang model of a Juniper router model m7i, running Junos 15.1R1.8 to and XSD schema using pyang 1.5 . I am getting the following parsing exceptions while processing the yang file:
failed to compile: xmlFAParseAtom: expecting ')'
failed to compile: xmlFAParseRegExp: extra characters
failed to compile: xmlFAParseAtom: expecting ')'
failed to compile: xmlFAParseRegExp: extra characters
failed to compile: xmlFAParseAtom: expecting ')'
failed to compile: xmlFAParseRegExp: extra characters

I suspect that pyang is not able to parse some of the regex in the file but it does not says much about the actual reason. Any idea what is causing the failure?

Thank you!

**Comment by llhotka** [comment]
Can you show us the module or at least the suspicious regexes?

Note that XSD output plugin in pyang is incomplete and deprecated.

**Comment by marspetrova** [comment]
Hello,
I can only suggest a link where to download the yang model - http://www.juniper.net/support/downloads/?p=m7i#sw but it requires an account. I have also tried with another output format (e.g. yin) - I get the same exception.
The yang model itself is quite long and has a lots of regexes - I am not able to sort  them out and find those which are causing the error. Is there a way for pyang to show the regex which is failing or line in the file where the exception happens?

**Comment by llhotka** [comment]
I can't really help without being able to reproduce the problem. I can only suggest that you check that regular expressions use the correct syntax, which is described in [XSD spec](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs). Some Juniper modules I saw previously used a wrong (Perl-like) syntax.
