### ISSUE TITLE
How to enter a non-printable default value for a binary type in yang.

### ISSUE THREAD

**Issue by clareym** [mbj4668/pyang#158]
Example:

type binary {
    length "2";
}
default "00FF";

I want to use a 2 byte default including non-printable characters.  The above fails indicating that the length of the default is too long.  How can I enter the above non-printable default value?

**Comment by mbj4668** [comment]
Hi,

Binaries are base64 encoded.  So the way to do this in YANG is to base64 encode your two bytes and put it as the default: default "AP8="; for example.

But it turns out that defaults for binaries are not validated at all in pyang.  This is a bug which I am about to fix.
