### ISSUE TITLE
pyang implicit errors

### ISSUE THREAD

**Issue by vkosuri** [mbj4668/pyang#159]
Hello,

I am very new to Yang models, Could you some please let me know what are implicit errors, Why we are skipping implicit erros.

```python
def setup_fmt(self, ctx):
        ctx.implicit_errors = True
```

Thanks
Malli

**Comment by mbj4668** [comment]
If you read the code you'll see that bin/pyang uses this to decide how to treat errors in imported modules.  When implicit_errors is False, errors in imported modules do not cause pyang to exit with exit code > 0

**Comment by vkosuri** [comment]
Thank you very much
