### ISSUE TITLE
yang import depth can't over 2?

### ISSUE THREAD

**Issue by macauleycheng** [mbj4668/pyang#162]
I use pyang to convert opendaylight-match-types.yang file, it display error due to opendaylight-inventory.yin has problem.
But I convert opendaylight-inventory.yang to yin directly, it has no problem.
So I think that it is limit that pyang can't have more than 2 depth import?

Opendaylight yang file url: https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin:YangModels

Below is my command result.
pyang -p . -f yin opendaylight-match-types.yang -o opendaylight-match-types.yin

opendaylight-inventory.yin:9: warning: imported module yang-ext not used
opendaylight-inventory.yin:106: error: no module with the namespace "urn:opendaylight:yang:extension:yang-ext" is imported

**Comment by mbj4668** [comment]
Do you have yang-ext.yang or .yin in the path?  I didn't find opendaylight-inventory.yang or yang-ext.yang at the link so I can't test myself.

**Comment by macauleycheng** [comment]
https://github.com/YangModels/yang/tree/master/experimental/odp

**Comment by mbj4668** [comment]
This works for me when I checked out the files you provided.
