### ISSUE TITLE
how to avoid circular dependency?

### ISSUE THREAD

**Issue by cl20vv** [mbj4668/pyang#163]
I've written three yang files, one is the module named mod.yang, one is the submodule, named suba.yang, and the last is another submodule named subb.yang.

```
module: mod
   +--rw name?      string
   +--rw a
   |  +--rw forsub?   string
   +--rw b?         -> /nameb
   +--rw namea?     string
   +--rw parent?    -> /name
   +--rw another?   -> /nameb
   +--rw nameb?     string
   +--rw upper?     -> /a/forsub
   +--rw other?     -> /namea
```

there are three leafs **'/name'**, **'/a/forsub/'**, **'/b'** in mod.yang, and **'/b'** is a reference of **'/nameb'** in submodule **'subb'**.

there are three leafs **'/namea'**, **'/parent'**, **'/another'** in suba.yang, and **'/parent'** is a reference of **'/name'** in module **'mod'**, **'/another'** is a reference of **'/nameb'** in submodule **'subb'**.

there are three leafs **'/nameb'**, **'/upper/'**, **'/other'** in subb.yang, and **'/upper'** is a reference of **'/a/forsub/'** in module **'mod'**, **'/other'** is a reference of **'/namea'** in submodule **'suba'**.

1. the mod could reference any leaf in it's sub modules, because the sub modules are included.
2. any submodule could reference the leafs in mod, but none of the sub modules include mod, and mod could not be included by sub mod right?
3. because the suba has a leaf **'/another'** reference to **'/nameb'** in **subb**, the suba.yang should include the subb.yang, or it report **suba.yang:15: error: mod:nameb in the path for another at mod.yang:23 (at suba.yang:13) is not found**.
4. because the subb has a leaf **'/other'** reference to **'/namea'** in **suba**, the subb.yang should include the suba.yang, or it report **subb.yang:16: error: mod:namea in the path for other at mod.yang:24 (at subb.yang:14) is not found**.
5. after suba and subb including each other, it report **subb.yang:3: error: circular dependency for module "suba"**

1. Why the submodules couldn't see each other, even both of them are included in mod?
2. How could I reference leafs between any two submodules without leading to the circular dependency?

PS:
mod.yang
```yang
module mod {
        namespace "http://www.none.com/conf/mod";
        prefix "mod";
        include suba;
        include subb;


        leaf name {
                type string;
        }   

        container a { 
                leaf forsub {
                        type string;
                }   
        }   

        leaf b { 
                type leafref {
                        path "/nameb";
                }   
        }   
        uses suba-grouping;
        uses subb-grouping;
}

```
suba.yang
```yang
submodule suba {
        belongs-to mod { prefix "mod";}
        include subb;

        grouping  suba-grouping {
                leaf namea {
                        type string;
                }   
                leaf parent {
                        type leafref {
                                path "/name";
                        }   
                }   
                leaf another {
                        type leafref {
                                path "/nameb";
                        }   
                }   
        }   
}

```
subb.yang
```yang
submodule subb {
        belongs-to mod { prefix "mod";}
        include suba;

        grouping  subb-grouping {
                leaf nameb {
                        type string;
                }   

                leaf upper {
                        type leafref {
                                path "/a/forsub";
                        }   
                }   
                leaf other {
                        type leafref {
                                path "/namea";
                        }   
                }   
        }   
}

```

**Comment by mbj4668** [comment]
You have to move all common definitions from the top module into a separate submodule.  Then the other submodules can include it and use the definitions.

**Comment by cl20vv** [comment]
@mbj4668 thanks. 

I found that confdc-6.0(tail-f) support the reference in sub module without include them(the main module include all the sub module, the sub module doesn't include each other), while confdc-5.3 not work.

if it miss definition of a leaf when parser a sub module, could pyang to find the leaf from parent module included moudules?
