### ISSUE TITLE
pyang batch script

### ISSUE THREAD

**Issue by vkosuri** [mbj4668/pyang#165]
While using in windows, If the user made .py always opens with text editor pyang won't detect from cmd. It always gives below message to user.

**'pyang' is not recognized as an internal or external command,
operable program or batch file.**

To avoid such cases make place %PYTHONPATH%\Scripts\pyang.bat file put below commands, pyang will work windows normally.

``` bat
@echo off
python %PYTHONPATH%\Scripts\pyang %*
```

I felt this file creation will be useful pyang users while installing pyang itself

**Comment by mbj4668** [comment]
Hi,

Could you create a pull request with the necessary changes?


/martin

**Comment by mbj4668** [comment]
pull request merged
