### ISSUE TITLE
Unknown keyword path - error when converting YANG to DSDL or RNG

### ISSUE THREAD

**Issue by marioMadunic** [mbj4668/pyang#170]
Hi,
(Posting here as I can't find a mailing list)

I'm using Pyang to transform a Yang model to RNG, either using Pyang or yang2dsdl, and receive the following error message:
Unknown keyword path - this should not happen.

Entering the following on the CLI
pyang -f dsdl tailf-ned-cisco-ios.yang

All modules are in the same directory and using latest version of Pyang and run on a Mac OS 10.9.5

Is this a bug or how pyang is being executed.

thanks
Mario

import statements
  import tailf-common {
    prefix tailf;
  }
  import ietf-inet-types {
    prefix inet;
  }
  import ietf-yang-types {
    prefix yang;
  }
The above have submodules and all are in the same directory.

first instance of path
        leaf table {
          tailf:info "Specify table-map";
          type leafref {
            path "/ios:table-map/name";
          }
        }

**Comment by llhotka** [comment]
I am not able to reproduce this error. I tried to simulate the situation with these modules:
```
$ cat head-f.yang
module head-f {
  namespace "http://example.com/head-f";
  prefix hf;

  extension info {
    argument text;
  }
}
$ cat test.yang 
module test {
  namespace "http://example.com/test";
  prefix t;

  import head-f {
    prefix hf;
  }

  list table-map {
    key "name";
    leaf name {
      type string;
    }
  }
  leaf table {
    hf:info "Specify table-map.";
    type leafref {
      path "/t:table-map/name";
    }
  }
}
```
However,
```
pyang -f dsdl test.yang
```
works fine.

**Comment by marioMadunic** [comment]
Thanks Ladislav for looking into this. There are 54 Yang files in total with all the modules. I do not know if I have permission to zip them up and post the files for better testing. Some of the files could be proprietary.

I'm going to create a monolithic Yang file with all the modules and see what happens.

Once again thanks for taking the time to look into this.

Mario

**Comment by mbj4668** [comment]
marioMadunic <notifications@github.com> wrote:
> Thanks Ladislav for looking into this. There are 54 Yang files in
> total with all the modules. I do not know if I have permission to zip
> them up and post the files for better testing. Some of the files could
> be proprietary.

I think they are; you should not upload them.

It would be great if you could try to create a minimal example that
triggers this crash.  E.g., I assume the NED module augments another
module, and maybe there are some groupings involved.


/martin

**Comment by llhotka** [comment]
From the error message it seems "path" statement is used in a place where the DSDL plugin doesn't expect it, even though pyang parsed it correctly. Could this perhaps be inside an extension?

**Comment by marioMadunic** [comment]
I'm going to try and investigate that Ladislav and see if I can create what Martin above mentioned.

On another note. This does not seem like the correct forum to post this, is there a more appropriate forum for this?

**Comment by mbj4668** [comment]
marioMadunic <notifications@github.com> wrote:
> On another note. This does not seem like the correct forum to post
> this, is there a more appropriate forum for this?

Since you discovered a bug in pyang, this is the right forum.


/martin

**Comment by llhotka** [comment]
It should help to use a debugger (pdb) and set a breakpoint on the line that produces the error message
(it is line 878 in pyang/translators/dsdl.py). Then you should be able to identify the statement that triggers the error, e.g. by inspecting variables `stmt.keyword` and `stmt.arg`.

**Comment by marioMadunic** [comment]
I believe I found the issue and I do not believe it is with Pyang at all. Some of the "path"s belong to a Tailf namespaced element that has path as a child node and I believe this is the issue. You can close this issue if this is expected behaviour when converting a Yang model to DSDL/RelaxNG.

Mario

**Comment by marioMadunic** [comment]
Sorry sample
ns:nodename-leafref {path "/pathTo/node";}

**Comment by llhotka** [comment]
Yes, that's what I suspected. We should probably handle such cases (they are legal according to YANG spec). It is complicated by the fact that pyang might support some extensions and ignore others.

**Comment by marioMadunic** [comment]
Not receiving the unknown path error anymore and a RelaxNG file is created using yang2dsdl but appears that the RelaxNG file is not valid. Missing Children error message in Oxygen. To confirm can someone who has access to Tailf's tailf-ned-cisco-ios.yang please give it a try.

**Comment by cmoberg** [comment]
Mario,

 Since very few people have access to the YANG file you refer to (it's associated with our NCS/NSO product), feel free to reach out to me on camoberg at cisco.com and I might be able to help directly.
