### ISSUE TITLE
Could you help me？

### ISSUE THREAD

**Issue by jianglin19920812** [mbj4668/pyang#173]
Hi，
     when I used the Pyang to translate the yang file to tree,I encountered a problem like this:error module import module not found in search path.I don't know how can I set import module path,can you help me?

                                                                                                                                                                  Lin

**Comment by vkosuri** [comment]
Hi,

You have to speicify search path
``` batch
Try on shell pyang --help
-p PATH, --path=PATH  ;-separated search path for yin and yang modules

Use pyang command like this
pyang -p modes_path yangfile.yang
```
Thanks
Malli

**Comment by jianglin19920812** [comment]
Malli,
      Thank you!
       I have followed your suggestion,but when I input the correct yang file path like this:
python pyang -f tree -o C:\Users\Administrator\Desktop\yangtree\CoreModel.tree  -p C:\Users\Administrator\Desktop\yangtree CoreModel.yang,the terminal print out"error CoreModel.yang:[Error 2]No such file or direcctory:'CoreModel.yang' ",so I don't know what's wrong there.

**Comment by vkosuri** [comment]
create a pyang.bat file in PYTHON_HOME\Scripts\payng.bat and copy and paste below content it will work

``` bat
@echo off
python C:\Python27\Scripts\pyang %*
```
For more information https://github.com/mbj4668/pyang/pull/166

After placing pyang.bat file try 

``` bat
pyang -f tree -o C:\Users\Administrator\Desktop\yangtree\CoreModel.tree -p C:\Users\Administrator\Desktop\yangtree CoreModel.yang
```

**Comment by jianglin19920812** [comment]
Malli，
     Thank you for your help,I have followed your advice,and the Pyang could find the module' path,but couldn't find the import module's path.how could I set import module's path?

                                                                                                                                                          Lin

**Comment by vkosuri** [comment]
Thanks, i think this C:\Users\Administrator\Desktop\yangtree directory doesn't have imported module due to this you are getting this error message.
