### ISSUE TITLE
Option `--tree-path` doesn't work

### ISSUE THREAD

**Issue by llhotka** [mbj4668/pyang#178]
With this module:
```
module tree {
  namespace "http://example.com/tree";
  prefix tr;

  container top {
    container subtop {
      leaf foo {
        type empty;
      }
      leaf bar {
        type empty;
      }
    }
  }
}
```
option `--tree-path` doesn't seem to have any effect:

```
$ pyang -f tree --tree-path="/top/subtop" tree.yang 
module: tree
   +--rw top
      +--rw subtop
         +--rw foo?   empty
         +--rw bar?   empty
```
The `top` container shouldn't be present in the output.

**Comment by llhotka** [comment]
I realized what the option actually does, I think though that it doesn't match what the manpage says: It prints not only the subtree but also all its ancestors. I think both variants make sense in different situations, so perhaps a new option, e.g. `--tree-no-ancestors` could be added.

One problem with the current behaviour occurs in combination with the `--tree-depth` option: if one wants to see, say, two levels inside the subtree identified by `--tree-path`, then `--tree-depth=2` usually doesn't work – the number of ancestor levels has to be added.

**Comment by visciang** [comment]
I agree with you about the manpage, it not really clear.
From my point of view, what the --tree-path expression represent is not a node selector (like a Xpath expression) but a path in the tree to print.

That makes sense if you think at the corresponding xml document in a netconf operation, you will supply the complete path 'till the element node update/modified.
