### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by jianglin19920812** [mbj4668/pyang#180]
Hi,
    I meet a problem when I use pyang to convert a yang file to a yangtree,the background said "UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 36254: illegal multibyte sequence".And I don't know how could I solve this problem,could you help me?
    Thanks!

**Comment by mbj4668** [comment]
Which version of pyang did you use?  If you haven't tried with the latest version checked in, could you do that?  We fixed some unicode bugs recently.
