### ISSUE TITLE
pyang -- ietf should thrown an error, not a warning, for the namespace and module-name

### ISSUE THREAD

**Issue by bclaise** [mbj4668/pyang#182]
Example: compiling the data models from http://datatracker.ietf.org/doc/draft-ietf-rtgwg-policy-model/

    routing-policy.yang:1: warning: RFC 6087: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
    routing-policy.yang:4: warning: RFC 6087: 4.8: namespace value should be "urn:ietf:params:xml:ns:yang:routing-policy"

Because we use "pyang --ietf", these should be:

    routing-policy.yang:1: error: RFC 6087: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
    routing-policy.yang:4: error: RFC 6087: 4.8: namespace value should be "urn:ietf:params:xml:ns:yang:routing-policy"

https://tools.ietf.org/html/rfc6087#section-4.8

       The following URN prefix string SHOULD be used for published and
       unpublished YANG modules:

       urn:ietf:params:xml:ns:yang:

Regards, Benoit

**Comment by bclaise** [comment]
And you might want to improve the code, accordingly for the following options:
  --lint-namespace-prefix=NAMESPACE_PREFIXES
                        Validate that the module's namespace matches one of
                        the given prefixes.
  --lint-modulename-prefix=MODULENAME_PREFIXES
                        Validate that the module's name matches one of the
                        given prefixes.

**Comment by mbj4668** [comment]
These are both SHOULDs in 6087. --ietf and --lint gives warnings for SHOULD.
