### ISSUE TITLE
Discrepancy between master and yang-1.1 branches

### ISSUE THREAD

**Issue by bclaise** [mbj4668/pyang#185]
Info coming from http://www.claise.be/OpenconfigYANGPageCompilation.html
YANG Model in question: https://github.com/openconfig/public/blob/master/release/models/mpls/openconfig-mpls-te.yang

pyang, with or without --lint, from the master branch, passes correctly.
However, pyang, with or without --lint, from the yang-1.1 branch, throws these error messages.

openconfig-mpls-te.yang:549: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:587: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:771: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:1064: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:1149: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:1183: error: restriction require-instance not allowed for this base type
openconfig-mpls-te.yang:1192: error: restriction require-instance not allowed for this base type

**Comment by mbj4668** [comment]
Note that this submodule has "yang-version 1"; and in version 1, require-instance is not allowed.
