### ISSUE TITLE
Prefixes in leafref paths

### ISSUE THREAD

**Issue by llhotka** [mbj4668/pyang#188]
Leafref paths in tree output don't follow the rules of [sec. 6.4.1](https://tools.ietf.org/html/rfc6020#section-6.4.1) in RFC 6020. A simple example is this:
```
$ cat a.yang
module a {
  namespace "http://example.com/a";
  prefix a;

  container top {
    leaf foo {
      type empty;
    }
  }
}

$ cat b.yang
module b {
  namespace "http://example.com/b";
  prefix b;

  import a {
    prefix a;
  }

  leaf bar {
    type leafref {
      path "/a:top/a:foo";
    }
  }
}

$ pyang -f tree a.yang b.yang 
module: a
   +--rw top
      +--rw foo?   empty
module: b
   +--rw bar?   -> /a:top/foo
```

The leafref path should be `/a:top/a:foo` because the node `foo` is in a different namespace than the context node `bar`.

**Comment by mbj4668** [comment]
Yeah, this is intentional... it uses prefixes like XML does; not like XPath.   From the code:
                # Try to make the path as compact as possible.
                # Remove local prefixes, and only use prefix when
                # there is a module change in the path.

**Comment by llhotka** [comment]
I understand the motivation but "path" argument is a subset of XPath. YANG already changed XPath1.0 rules so I think we should stick to it. Even Radek Krejci got confused and this tells you something.

**Comment by mbj4668** [comment]
The tree output uses the notation:

  -> /../...

it does not claim to be XPath 1.0, nor YANG.

I prefer to stay compact...
