### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by irixt** [mbj4668/pyang#191]
I'm using 1.6 and getting a UnicodeEncodeError on several files. For example, when converting from YANG to XML using '-f yin' I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 420, in <module>
    run()
  File "/usr/local/bin/pyang", line 290, in run
    expect_failure_error=False)
  File "/usr/local/lib/python2.7/dist-packages/pyang/__init__.py", line 100, in add_module
    module.i_adler32 = zlib.adler32(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 1070: ordinal not in range(128)

**Comment by hjelmeland** [comment]
Same with me. Had to remove non-ascii characters from the yang file. (Comments with norwegian æøå in my case)

**Comment by mbj4668** [comment]
This bug has been fixed in "master".  Could you test your files with the latest code?

**Comment by hjelmeland** [comment]
Yes, it works now :-)
