### ISSUE TITLE
miss namespace prefix for unique statement argument in sch

### ISSUE THREAD

**Issue by shijunzhi** [mbj4668/pyang#200]
Hi

I meet one problem about missing prefix for unique statement argument if the leaf is in side one container. My yang module like this:
```
    sudmodule test {
        grouping list-group {
            list l {
                unique "b/c";
                container b {
                    leaf c {
                    }
                }
            }
        }
    }
```
In the generated sch file, the unique statement argument is translated to "$pref:b/c", but the correct one should be "$pref:b/$pref:c".

I checked the dsdl.py, if unique statement is inside grouping, the "$pref:" is added by gen-schematron.xml when generate sch file.
```
  <xsl:template name="qname">
    <xsl:param name="name" select="@name"/>
    <xsl:if test="not(contains($name,':'))">$pref:</xsl:if>
    <xsl:value-of select="$name"/>
  </xsl:template>
```
In this case, the name value is "b/c".

**Comment by llhotka** [comment]
@shijunzhi please verify the fix.

**Comment by shijunzhi** [comment]
@llhotka it works, Thank you!
