### ISSUE TITLE
Add a pyang option to ignore a specific error

### ISSUE THREAD

**Issue by nickweeds** [mbj4668/pyang#203]
The pyang --ignore-errors option ignores all errors, but sometimes it is safer to ignore a specific error.

This could be done by adding a new --ignore-error option that takes an error name parameter (as -W and -E do).

For example, if a Yang module contains patterns with invalid syntax it could be handled using:

    pyang --ignore-error PATTERN_ERROR mymodule.yang

Pull request to follow.

**Comment by nickweeds** [comment]
Hi Martin,

I have corrected the mistake you pointed out and resubmitted the pull request.
Would you be happy to accept it now ?

Also "make doc" doesn't seem to work for me.  Can you advise how to regenerate the man page or should I edit it by hand ?

Thanks,

   Nick.

**Comment by mbj4668** [comment]
What does "doesn't seem to work" mean?

**Comment by nickweeds** [comment]
I have run "make doc" on a couple of different machines.

(1) On one machine "make doc" runs without reporting any errors but the output pyang.1 file has quite extensive changes that appear unrelated to my source commit.  Installing using "sudo pip install ." followed by "man pyang" brings a man page that starts as follows:

    PYANG(1)                         pyang manual                         PYANG(1)

      .SH "NAME" pyang - validate and convert YANG modules to various formats

      .SH "SYNOPSIS"

       .HP 144u

          pyang
          [--verbose]
          [--canonical]
          [--strict]
          [--lint]
    ...

I have committed the pyang.1 file to https://github.com/nickweeds/pyang so that you can take a look if you wish.

(2) On the other machine I get errors such as the following:

    (cd doc; make)
    make[1]: Entering directory `/home/demo/pyang/doc'
    cat pyang.1.dbk | \
    	  sed -e 's/%PYANG_VERSION%/1.6/g' \
    	      -e 's/%DATE%/2015-10-06/g' | \
    	  xsltproc -o ../man/man1/pyang.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl -
    http://docbook.sourceforge.net/release/xsl/current/html/html-rtf.xsl:153: parser error : Couldn't find end of Start Tag apply line 153
    http://docbook.sourceforge.net/release/xsl/current/html/html-rtf.xsl:153: parser error : Premature end of data in tag copy line 151
    http://docbook.sourceforge.net/release/xsl/current/html/html-rtf.xsl:153: parser error : Premature end of data in tag template line 150
    http://docbook.sourceforge.net/release/xsl/current/html/html-rtf.xsl:153: parser error : Premature end of data in tag stylesheet line 2
    compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 72 element include
    xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/html-rtf.xsl
    make[1]: *** [../man/man1/pyang.1] Error 5
    make[1]: Leaving directory `/home/demo/pyang/doc'
    make: *** [doc] Error 2

The errors appear to be random and different each time.  Fetching the xsl files with wget works fine.

Both machines are running Ubuntu 14.04 with current updates.
