### ISSUE TITLE
Couldn't import yang model

### ISSUE THREAD

**Issue by ashishk1994** [mbj4668/pyang#205]
Hi,

I was trying to use pyang but I am getting following error for my yang model
```
pyangbind-example.yang:5: error: module "ietf-inet-types" revision "2010-09-24" not found in search path
pyangbind-example.yang:5: warning: imported module ietf-inet-types not used

```
My file is something like below, I have stored the ietf-inet-types file in the same folder as below module.
```
module pyangbind-example {
        namespace "urn:ietf:params:xml:ns:yang:ietf-lisp-address-types";
        prefix laddr;
        import ietf-inet-types { prefix inet; revision-date 2010-09-24; }

       // Omitted later part
```
Please help me if I am missing something. I am new to yang models and trying to understand various yang concepts as well.

**Comment by mbj4668** [comment]
Make sure you have the correct revision of ietf-inet-types.yang in your directory.
But this is a very old version of ietf-inet-types.  Also consider not using import by revision.
