### ISSUE TITLE
Import statements and schema is not properly converted from yang model.

### ISSUE THREAD

**Issue by vishwaraths** [mbj4668/pyang#207]
Hi,
I tried to convert yang file in java using jnc.py of JNC library and Pyang, but in java file import statements are not proper so i manually changed import statement and schema file.
But i think there is something missing in java file b'coz request message differs while executing same yang file from CLI using netconf-console and from JAVA.
Is there any issue with Pyang libary releated to this?

**Comment by mbj4668** [comment]
Sounds like a JNC issue.  Please report the bug in JNC, and remember to write instructions for how to reproduce the perceived bug.
