### ISSUE TITLE
Problem with double-quoted string in yang files

### ISSUE THREAD

**Issue by PavolVican** [mbj4668/pyang#213]
In the RFC 6020 6.1.3 said, space or tab character before a line break, this trailing whitespace is stripped from the string.

For example in ietf-netconf module at line 55, which is downloaded from netconfcentral.org, is one space at the end of line. This space should be removed. I think you have bug.

Next in in the RFC 6020 6.1.3 said, double-quoted string contains a line break followed by space or tab characters that are used to indent the text. In this process, a tab character is treated as 8 space characters.

For example:

[my-module.txt](https://github.com/mbj4668/pyang/files/208022/my-module.txt) I have to rename file from my-module.yang to my-module.txt due to copy this file to this issue. 
In this example double-quoted string start at column 17. For indent text, it used 2 tab characters and 2 space characters. Total space characters should be 18.

I think it should be print description:

```
description
    "This is
      indent the text";
```

**Comment by mbj4668** [comment]
Fixed in 0e54cb6d0a2b33df12a5d1b1642e97f09a2ff956
