### ISSUE TITLE
Trang command  not found using PYANG on MS Windows

### ISSUE THREAD

**Issue by DenisOlasyuk** [mbj4668/pyang#215]
deol1115@WSMKI-02016 ~/pyang/doc/tutorial/examples
$ trang -I rng -O rnc turing-machine-config.rng turing-machine-config.rnc
-bash: trang: command not found

**Comment by llhotka** [comment]
Trang is an open source Java application that has to be installed separately, see
http://www.thaiopensource.com/relaxng/trang.html
