### ISSUE TITLE
pyang doesn't check the date format

### ISSUE THREAD

**Issue by bclaise** [mbj4668/pyang#217]
[Note: the formatting with CODE BEGINS is screwed up]

Courtesy of Ebben Aries' investigation.

bclaise@bclaise-VirtualBox:~/ietf/my-id-mirror$ pwd
/home/bclaise/ietf/my-id-mirror
bclaise@bclaise-VirtualBox:~/ietf/my-id-mirror$ for i in .; do grep BEGINS *$i* | grep yang | grep -Ev "[0-9]{4}-[0-9]{2}-[0-9]{2}" | grep -E "[0-9]{4}-"; done

draft-hares-i2rs-service-topo-dm-06.txt:   <CODE BEGINS> file "ietf-i2rs-service-topology@2016-02-q0.yang"
draft-mirsky-ippm-twamp-light-yang-02.txt:<CODE BEGINS> file "ietf-twamp-light@2016-0305"
draft-zhang-ccamp-transport-ctrlnorth-yang-00.txt:   <CODE BEGINS> file " ietf-transport-service@2016-3-7.yang" 

None of those 3 drafts report an error regarding the date format.
See http://www.claise.be/IETFYANGPageCompilation.html

Example:
bclaise@bclaise-VirtualBox:~/ietf/my-id-mirror$ xym.py  draft-hares-i2rs-service-topo-dm-06.txt 
Created the following models::
   ietf-i2rs-service-topology@2016-02-q0.yang

bclaise@bclaise-VirtualBox:~/ietf/my-id-mirror$ pyang --ietf ietf-i2rs-service-topology@2016-02-q0.yang 
ietf-i2rs-service-topology@2016-02-q0.yang:1: warning: unexpected modulename "ietf-i2rs-service-topology" in ietf-i2rs-service-topology@2016-02-q0.yang, should be ietf-i2rs-service-topology@2016-02-q0

From 6020bis:
   revision-date-stmt  = revision-date-keyword sep revision-date stmtend

   revision-date       = date-arg-str

   date-arg-str        = < a string that matches the rule >
                         < date-arg >

   date-arg            = 4DIGIT "-" 2DIGIT "-" 2DIGIT

**Comment by earies** [comment]
I would like to point out that pyang does infact run validation on the date format (date regex in pyang/syntax.py) in the revision statement.  The above is solely with regards to the file declaration in IETF drafts where the `<CODE BEGINS>` starts and only affects the filename during extraction (before validation)

```
date = r"[1-2][0-9]{3}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])"
```

Therefore, the enhancement here would be to solely run validation on the filename itself to make sure that it follows the syntax defined in

https://tools.ietf.org/html/rfc6020#section-5.2

**Comment by mbj4668** [comment]
It is correct that pyang already validates the revison.  Furthermore, pyang provides a warning when the module name doesn't match the file name, as shown by Benoit's example.  So I don't think there is any case where pyang doesn't produce a warning.  However, in this particular case, pyang's "guess" is off - it is the file name that is bad, not the module name.
