### ISSUE TITLE
if-feature within augmented block generates invalid YIN

### ISSUE THREAD

**Issue by dcpontius** [mbj4668/pyang#218]
We encountered this issue when attempting to build the most recent IETF OSPF YANG model.

YANG EXCERPT:
```
 augment "/rt:routing/rt:routing-protocols/"
        + "rt:routing-protocol/ospf:ospf/ospf:instance" {
    when "../../rt:type = 'ospf:ospfv2' or
          ../../rt:type = 'ospf:ospfv3'" {
      description
        "This augmentation is only valid for OSPF
        (type 'ospfv2' or 'ospfv3').";
    }
    if-feature multi-topology;
    description
      "OSPF multi-topology instance configuration
       state augmentation.";
...
```
The YIN output contained "if-feature" nodes at multiple invalid locations in the sub-tree.  Subsequent validation of the YIN failed with "unexpected keyword: if-feature" on the "when" statement.

The existing implementation in v_expand_2_augment() appears to jam "if-feature" nodes to any and all sub-statements in the expansion rather than to the specific sub-statements for which they were intended.

I patched the statements.py file as follows and it seems to correct the problem:

```
diff --git a/pyang/statements.py b/pyang/statements.py
index 4dfbdd2..90eafba 100644
--- a/pyang/statements.py
+++ b/pyang/statements.py
@@ -1559,8 +1559,9 @@ def v_expand_2_augment(ctx, stmt):
     if_features = stmt.search('if-feature')
     for s in stmt.substmts:
         for f in if_features:
-            s.substmts.append(Statement(f.top, stmt.parent, f.pos, f.keyword,
-                                        f.arg))
+            tmp_stmt = Statement(f.top, stmt.parent, f.pos, f.keyword, f.arg)
+            if s == f.parent:
+                s.substmts.append(tmp_stmt)
         if s.keyword in _copy_augment_keywords:
             stmt.i_target_node.substmts.append(s)
             s.parent = stmt.i_target_node
```

**Comment by mbj4668** [comment]
I cannot reproduce this error.  Could you provide complete instructions for how to reproduce it?

**Comment by dcpontius** [comment]
The YIN file generation worked fine, but the validation of the generated YIN files failed on improperly placed if-feature statements.

Our build output:
```

$ pyang --lint ietf-ospf.yang 
$

No problems reported - good.

$ pyang -f yin ietf-ospf.yang > ietf-ospf.yin
$

(Good)

$ pyang -f yin ietf-ospf.yin  > /dev/null
ietf-ospf.yin:3277: error: unexpected keyword "if-feature"
ietf-ospf.yin:3280: error: unexpected keyword "if-feature"
ietf-ospf.yin:3285: error: unexpected keyword "if-feature"
ietf-ospf.yin:3332: error: unexpected keyword "if-feature"
ietf-ospf.yin:3335: error: unexpected keyword "if-feature"
ietf-ospf.yin:3340: error: unexpected keyword "if-feature"
ietf-ospf.yin:3495: error: unexpected keyword "if-feature"
ietf-ospf.yin:3498: error: unexpected keyword "if-feature"
ietf-ospf.yin:3503: error: unexpected keyword "if-feature"
ietf-ospf.yin:3552: error: unexpected keyword "if-feature"
ietf-ospf.yin:3555: error: unexpected keyword "if-feature"
ietf-ospf.yin:3560: error: unexpected keyword "if-feature"

(Not good)

```
pyang.zip includes original RFCs as well as rfcstripped and renamed yang files.

pyang2.zip includes just the 6 yang files that should be the minimal set necessary to duplicate all the commands below.  I duplicated them using pyang 1.7 released today.
[pyang.zip](https://github.com/mbj4668/pyang/files/318591/pyang.zip)
[pyang2.zip](https://github.com/mbj4668/pyang/files/318592/pyang2.zip)

(Also, the use of tmp_stmt in my snippet was unnecessary; just a leftover from my debugging hacks; it's really the "if s == f.parent:" that matters.)

Thanks for looking into this,
-Doug-
