### ISSUE TITLE
`share/yang/modules` not under `sys.preffix` when installing from pip

### ISSUE THREAD

**Issue by abravalheri** [mbj4668/pyang#225]
On Debian 8.2 (jessie), pip (from `python-pip` package) places the files from `modules` folder under `/usr/local/share/yang/modules`.

Since pyang rely on `sys.prefix` to discover the location for default modules (ietf & iana), it incorrectly assumes the default installation directory as `/usr/share/yang/modules`. Therefore, **it cannot find common modules (implicit `$YANG_MODPATH`),  e.g. `ietf-yang-types`, resulting in errors**.

These errors can be replicated with the following procedure.
- Install the most recent version of pyang using pip (from git repo):

``` bash
cd /tmp
git clone https://github.com/mbj4668/pyang.git
cd pyang
python setup.py bdist_wheel
sudo pip install dist/pyang-1.6-py2.py3-none-any.whl
```
- Create an `example-sport.yang` file (based on [wikipedia example](https://en.wikipedia.org/wiki/YANG#Example))

``` yang
module example-sports {
  namespace "http://example.com/example-sports";
  prefix sports;

  import ietf-yang-types {
    prefix yang;
  }

  container sports {
    config true;
    list person {
      key "name";
      leaf name {
        type string;
      }
      leaf birthday {
        type yang:date-and-time;
        mandatory true;
      }
    }
  }
}
```
- Compile the module

``` shell
pyang -f yin example-sports.yang -o example-sports.yin
# => example-sports.yang:5: error: module "ietf-yang-types" not found in search path
```

The following information describes the system state

``` bash
which python
# => /usr/bin/python
python -V
# => Python 2.7.9
python -c 'import sys; print sys.prefix'
# => /usr
which pyang
# => /usr/local/bin/pyang
ls /usr/share/yang/
# => ls: cannot access /usr/share/yang/: No such file or directory
ls /usr/local/share/yang/
# => schema/   modules/   xslt/   images/
```

Note that, when `import` statement is removed and `yang:date-and-time` is changed to `string`, the module compiles without problem.

I think this behavior cannot be detected in CI tests, since travis uses `env.sh`, which explicitly defines `$YANG_MODPATH`

**Comment by mcr** [comment]
#226 would seem to do the right thing for virtualenv, but my experience with pip3 install as mortal, pyang is installed in ~/.local, as are the modules.  I can't tell what the default path is (--help should ideally print it), but it does not appear to include ~/.local/share/yang/modules.
