### ISSUE TITLE
pyang 1.6 does not support "when statement for key leafs"

### ISSUE THREAD

**Issue by manoj-nair** [mbj4668/pyang#237]
Please see e.g. below:

module test1 {
    namespace "urn:test:test1";
    prefix "test1";

    list interface {
         key "name";

         leaf name {
             when "";
             type string;
         }
     }
}

$yang2dsdl -b test1 -t data test1.yang
test1.yang:9: error: the statement when cannot be given for a key
test1.yang:9: warning: default value for a key leaf is ignored
DSDL translation needs a valid module

This works with pyang 1.5. on Ubuntu 14.04 LTS. (Note: The when statement argument is just illustrative)

**Comment by mbj4668** [comment]
This is by design.  Explicitly illegal in YANG 1.1.

What are you trying to achieve?

**Comment by manoj-nair** [comment]
Oh, I see... Thanks for pointing this out!

I was using XPATH expressions in the 'when' statement for the key of a 'list' container to validate an XML instance. (BTW, I am not an expert in XPATH)
e.g.
1. To make sure that at least one (any one) of the non-key leafs in a list instance is always present in the XML.
Plus a few other use cases. 

Any suggestions on how such validations can be achieved in YANG would be appreciated.

Thanks

**Comment by mbj4668** [comment]
"when" makes the node conditional, i.e. if the expression evaluates to "false", the node cannot be present.  But all keys must always be present, which is why "when" is not allowed on key leafs.

You need to use a "must" expression in the list node to do what you're looking for, for example:

    list foo {
      ...
      must "a or b or c";
     leaf a { ... }
     leaf b { ... }
     leaf c { ... }
   }
