### ISSUE TITLE
Generating syntactically valid HTML5 output from PYANG

### ISSUE THREAD

**Issue by navaneethaKolichelma** [mbj4668/pyang#238]
We have observed a few bugs in the HTML code generated and fixed them in the **jstree.py**
 file attached (jstree.txt, changed the extension as it is not supporting uploading of .py file) and we have also done some minor modifications to make the HTML output fully valid as **HTML5** output.

Please find the list of bug fixes and HTML5 changes done:

1. Missing DOCTYPE declaration - added   
2. Missing  `<html>`,  `</head>` and `</div>` tags - added
3. Missing `<td><\td>` making the table improper - added
4. Closing  `</td`  tag is not proper in the output - fixed
5. Changed `<script language="javascript1.2">` to `<script type="text/javascript">`
6. Static ID values assigned to some table elements creating duplicate-id’s warnings in the output validator - removed
7. Inline styling for most of the elements: `<th align="left">` , `<font color="blue">`, `<table width=”100”>`… - defined as class/styles
8. Folder icon issue on click  of “Expand All” | “Collapse All” – fixed  (when clicking on "Expand All" the icons are not getting changed accordingly) - fixed
[jstree.txt](https://github.com/mbj4668/pyang/files/301878/jstree.txt)

**Comment by mbj4668** [comment]
Great, thanks!  Can you create a pull request for this fix please?

**Comment by mbj4668** [comment]
Fixed by pull request 242,
