### ISSUE TITLE
"sudo pip install pyang" doesn't take integrate the yang-1.1 branch

### ISSUE THREAD

**Issue by bclaise** [mbj4668/pyang#239]
I see that you merged the yang-1.1 two months ago.
The issue is that the YANG 1.1 is apparently not included.
http://www.claise.be/IETFYANGPageCompilation.html shows plenty of errors such as:
    yang:2: error: bad value "1.1" (should be version)

I had to use "git clone" and it worked fine.

**Comment by levkowetz** [comment]
Yes, it would be much appreciated if there was a new release, including Yang-1.1 support, up on pypi.python.org so it can be pulled and installed by 'pip install --upgrade'.

**Comment by mbj4668** [comment]
1.7 released
