### ISSUE TITLE
bits type default value can be empty string

### ISSUE THREAD

**Issue by gnanavelkrishnan1** [mbj4668/pyang#241]
bits type default value can be empty string

example: 

type bits {

   bit bit1;
   bit bit2;
   default "";
}

where as same yang in pyang 1.6 does not report error but 1.7 reports error

**Comment by wlupton** [comment]
I think that this is probably the bug discussed in the latter part of Issue #232 and fixed in Commit c878ce4.

**Comment by mbj4668** [comment]
wlupton is correct.  Already fixed.
