### ISSUE TITLE
augmentation not working properly for the nested hierarchy using pyang tree format

### ISSUE THREAD

**Issue by vinaykumar1315** [mbj4668/pyang#243]
Hi All,

I am Vinay and iam using pyang tree format command for the processing of yang file's.

ISSUE::: tree format augment part was not expanded in module tree when we use with import module in another main yang module.

USE CASE::: augment the existing yang file which was used(imported) in some other yang file already.

USAGE:::
In oc-parent.yang i imported openconfig-sub.yang 
and openconfig-sub-extended.yang have augment for the openconfig-sub.yang container.

Expectation: 
   all the augmented leafs should  be placed in the parent imported yang hierarchy.
    but the augments are placed only in the immediate yang hierarchy.

Please correct me if my understanding was wrong or my yang was wrong for my use case.

See below Output and attached yang files which was used:
pyang -version
pyang 1.7

pyang -f tree oc-parent.yang openconfig-sub.yang openconfig-sub-extended.yang

module: oc-parent
   +--rw parent* [name]
      +--rw name             string
      +--rw parent-type?     string
      +--rw configuration
         +--rw subs
            +--rw sub* [name]
               +--rw name      string
               +--rw config
                  +--rw name?          string
                  +--rw description?   string
module: openconfig-sub
   +--rw subs
      +--rw sub* [name]
         +--rw name      string
         +--rw config
            +--rw name?                string
            +--rw description?         string
            +--rw subext:sub-target              -- These container should come in module: oc-parent hirarcy
               +--rw subext:community?   string
               +--rw subext:import?      string
               +--rw subext:export?      string

oc-parent.yang:::
module oc-parent {
  yang-version "1";
  namespace "http://com.net/yang/oc-parent";
  prefix "oc-parent";
  import openconfig-sub { prefix sub; }

  list parent {
    key "name";

    leaf name {
      type string;
      description "host/parent name.";
    }
    leaf parent-type {
      type string;
    }
    container configuration {
        uses sub:sub-top;
    }
  }
}

openconfig-sub.yang:::
module openconfig-sub {
  yang-version "1";
  namespace "http://openconfig.net/yang/sub";
  prefix "sub";

  grouping sub-top {
  	container subs {
      list sub {
  			key "name";
        leaf name {
  			type string;
		}
  		container config {
          uses sub-config;
        }
       }
  	}
  }
  grouping sub-config {
    leaf name {
      type string;
    }
    leaf description {
      type string;
    }
  }
  uses sub-top;
}

openconfig-sub-extended.yang:::
module openconfig-sub-extended {
    yang-version "1";
    namespace "http://com.net/yang/openconfig-sub-extended";
    prefix "subext";
    import openconfig-sub { prefix "sub"; }

    grouping sub-target {
        container sub-target {
           leaf community {
             type string;
           }
           leaf import {
             type string;
           }
           leaf export {
             type string;
           }
        }
    }

    augment "/sub:subs/sub:sub/sub:config" {
        description "Adds addtional items";
        uses sub-target;
    }
}
[oc-parent.yang.txt](https://github.com/mbj4668/pyang/files/339534/oc-parent.yang.txt)
[openconfig-sub.yang.txt](https://github.com/mbj4668/pyang/files/339536/openconfig-sub.yang.txt)
[openconfig-sub-extended.yang.txt](https://github.com/mbj4668/pyang/files/339535/openconfig-sub-extended.yang.txt)

**Comment by mbj4668** [comment]
Hi,

No this is not a bug.  The augment clearly augments the hierarchy in "openconfig-sub", not "oc-parent".


/martin
