### ISSUE TITLE
YANG 1.1 - when statement in augment statement is ignored

### ISSUE THREAD

**Issue by zolvaczi** [mbj4668/pyang#255]
The aim of the attached YANG model: a type-A list element needs to be augmented with placeholder-type-1 + placeholder-type-2 leaves; a type-B list element with placeholder-type-1 + placeholder-type-3 leaves; while a type-C with placeholder-type-2 + placeholder-type-3.

What seems to happen instead is that the list items are augmented with placeholder-type-1 + placeholder-type-2 in a generic fashion (ignoring the when statement).

[Uploading YANG-files.zip…]()

**Comment by zolvaczi** [comment]
[root@localhost test]# pyang --strict *.yang
b.yang:9: error: there is already a child node to "/bm:a/bm:node-list/bm:node" at b.yang:7 with the name "placeholder-type-1" defined at a.yang:9
c.yang:9: error: there is already a child node to "/bm:a/bm:node-list/bm:node" at c.yang:7 with the name "placeholder-type-2" defined at a.yang:10
c.yang:11: error: main:global-list in the path for x at c.yang:11 is not found

[root@localhost test]# pyang -ver
pyang 1.7

**Comment by zolvaczi** [comment]
[YANG-files.zip](https://github.com/mbj4668/pyang/files/369037/YANG-files.zip)

**Comment by mbj4668** [comment]
The first to error message are pretty self-explanatory, right?  You cannot add the same node (same name) twice; regardless of any 'when' expression.
