### ISSUE TITLE
Error in uses statement which augments a grouping containing tailf:action

### ISSUE THREAD

**Issue by jjbreitenbach** [mbj4668/pyang#264]
Using pyang version 1.7, an error is generated when a uses statement augments a grouping which contains tailf:action.  In the example below, augmenting action-grouping:action-node/action-container results in a _"node action-bug::action-node is not found"_ error, while no error is produced when augmenting action-grouping:normal-node/normal-container.

**Setup:**
Environment: Ubuntu 16.04.1 LTS
Python: 2.7.12
pyang: 1.7
NSO: 4.2

```
$ pyang -p $NCS_DIR/src/ncs/yang -f yang action-bug.yang
action-bug.yang:21: error: node action-bug::action-node is not found

$ cat action-bug.yang
module action-bug {
  namespace "http://action-bug.com/";
  prefix abug;

  import tailf-common {
    prefix tailf;
  }

  grouping action-grouping {
    tailf:action "action-node" {
      container action-container;
    }

    container normal-node {
      container normal-container;
    }
  }

  container c {
    uses action-grouping {
      augment "action-node/action-container" {
        leaf action-leaf {
          type string;
        }
      }
      augment "normal-node/normal-container" {
        leaf normal-leaf {
          type string;
        }
      }
    }
  }
}

```

**Comment by mbj4668** [comment]
You should use yang 1.1 syntax and just use 'action'.

Alternatively, if you need the tailf syntax, you should use the pyang compiler that is delivered with NCS/ConfD.

Alternatively, you can find the file 'tailf.py' in the ncs/confd pyang installation (under plugins) and put it in your own plugin dir.
