### ISSUE TITLE
deviate add does not work properly

### ISSUE THREAD

**Issue by warvyvr** [mbj4668/pyang#267]
Hi,
  I try to use pyang to deviate an mandatory configurable leaf to non-mandatory read-only leaf, it turns out that the mandatory property is removed on purpose but 'config false' is not added to that leaf.
  here is the details:
`test.yang`
```
module test {
  yang-version 1.1;

  namespace urn:test;

  prefix test;
  
  container root {
    list child {
      key name;
      leaf name {
        type string;
      }
      leaf foo {
        mandatory true;
        type string;
      }
    }
  }
}
```

the deviation yang model is as following:
`test-dev.yang`
```
module test-dev {
  yang-version 1.1;
  namespace urn:test-dev;
  prefix test-dev;
  import test {
    prefix t;
  }
  deviation /t:root/t:child/t:foo {
    deviate delete {
        mandatory true;
    }
    deviate add {
        config false;
    }
  }
}
```

the result of deviating the `test-dev.yang` to `test.yang` is 
```
$ pyang test.yang --deviation-module=test-dev.yang -f tree
module: test
    +--rw root
       +--rw child* [name]
          +--rw name    string
          +--rw foo?    string
```
the expected result is the `foo` is with `ro` instead of `rw`

version information is
```
$ python --version
Python 3.5.1
$ pyang --version
pyang 1.7
```
the pyang in my laptop is cloned from the git repo, the latest commit is as follow
```
commit d9c10e1eef46c62f1f874c227e0235d935830161
Author: Martin Björklund <mbj4668@gmail.com>
Date:   Thu Sep 22 14:48:37 2016 +0200

    Fixes #265 - an identity is not derived from itself
```

**Comment by mbj4668** [comment]
Hi,

This is a bug, but maybe not as you would expect... All nodes have a "config" property; it is inherited from the parent if not explicitly set.  So you need to do 'deviate replace'.  The bug is that pyang should detect this and not just be silent.

**Comment by warvyvr** [comment]
Thanks, you are right. I should use `deviate replace`
