### ISSUE TITLE
require-instance for leafref 

### ISSUE THREAD

**Issue by abhikeshav** [mbj4668/pyang#274]
Hi,
require-instance statement is supported for leafref only in yang 1.1 (RFC 7950), but pyang successfully validates a yang-version 1 model which has a leaf like the below

```
yang-version "1";

...
leaf refleaf {
 type string;
}

leaf a {
  type leafref {
    path "/refleaf";
    require-instance true;
  }
}
```

Is this per design?

**Comment by abhikeshav** [comment]
FYI.. I only see this on `1.6`, on `1.7`, the yang-version statement is checked correctly

**Comment by mbj4668** [comment]
Yes, known bug in 1.6.
