### ISSUE TITLE
if-feature errors?

### ISSUE THREAD

**Issue by MichaelWangzitao** [mbj4668/pyang#280]
Hi, 
I use the "pyang --ietf" command to check "ietf-conn-oam.yang" model. And received some errors:   
ietf-conn-oam.yang:740: error: bad value "continuity-check" (should be if-featur
e-expr) 
But these errors did not appear before pyang-1.7.1. To localize this problem, I also use pyang-1.7.1 to check the "ietf-routing@2016-11-04.yang"(RFC8022), but received same erros:
ietf-routing@2016-11-04.yang:362: error: bad value "multiple-ribs" (should be if
-feature-expr)
ietf-routing@2016-11-04.yang:426: error: bad value "router-id" (should be if-fea
ture-expr)
Does it some bugs of pyang-1.7.1?

Best Regards!
-Michael Wang

**Comment by mbj4668** [comment]
I cannot reproduce this error.  Please make sure that you really run pyang-1.7.1.

**Comment by MichaelWangzitao** [comment]
Hi Martin,

I check it again, and screenshot it:

[cid:image001.png@01D2466D.A1306A50]

BR!
-Michael

发件人: Martin Bjorklund [mailto:notifications@github.com]
发送时间: 2016年11月24日 16:08
收件人: mbj4668/pyang
抄送: wangzitao; Author
主题: Re: [mbj4668/pyang] if-feature errors? (#280)


I cannot reproduce this error. Please make sure that you really run pyang-1.7.1.

**Comment by mbj4668** [comment]
Please try to include the relevant information in the bug report.
