### ISSUE TITLE
Question: When creating yin (-f yin) from yang file, is there any option to get pyang recursively include submodules

### ISSUE THREAD

**Issue by darshana-jk** [mbj4668/pyang#282]
Hi,
I want to create a yin from a yang module which is devided in to multiple sub-modules (my yang file: https://github.com/BroadbandForum/yang/blob/master/standard/interface/bbf-vdsl.yang).
When creating tree:
`pyang -f tree bbf-vdsl.yang`
 pyang scans all included submodules and generate the full tree.
But, when creating the yin file, `pyang -f yin bbf-vdsl.yang`, it only creates it for the root module file, doesn't follow any sub-module. the sub-modules are included as `<include module="bbf-vdsl-base-body"/>...`.

Is there an option to pyang to make it recursively include all the sub-modules when generating the yin file?

Darshana.

**Comment by mbj4668** [comment]
No.
YIN is an alternative syntax for YANG.  So it translates on a syntactical level.  You need to translate all submodules as well.
