### ISSUE TITLE
referencing status data in XPath placed in configuration data

### ISSUE THREAD

**Issue by rkrejci** [mbj4668/pyang#286]
I'm not sure how much pyang checks XPath expressions in schema, so may be this is out of scope for pyang. Anyway, accessible tree for XPath expressions (e.g. `must`) in configuration data (RFC 7950, sec 6.4.1) is `the data in the datastore where the context node exists`. So it does not make sense to refer status data from config data since e.g. in `startup` datastore it will never satisfy. Pyang does not check for this issue in schema:
```
$ pyang --version
pyang 1.7.1
$ cat b.yang 
module b {
  namespace urn:yang:b;
  prefix b;

  leaf status {
    type string;
    config false;
  }

  leaf config {
    type string;
    must "../status";
  }
}
$ pyang b.yang
$
```

**Comment by mbj4668** [comment]
Hi,

Yes, the problem is that payng doesn't have an XPath parser.  So it doesn't check any XPath paths.  This is a known issue, and it would be great to incorporate an XPath parser.
