### ISSUE TITLE
search_grouping and search_typedef not working under augment

### ISSUE THREAD

**Issue by martin-volf** [mbj4668/pyang#288]
The code of these two functions relies on that `parent` eventually leads up to the ancestor module/submodule statement. This is obviously true in the initial phases, but after the augment expansion phase has completed, this may not be true any longer. For instance, in case of modules like this:

```
module m1 {
  namespace "http://example.org/m1";
  prefix m1;

  container c1;
}

module m2 {
  namespace "http://example.org/m2";
  prefix m2;
  import m1 { prefix m1; }

  typedef t {
    type int32;
  }
  augment "/m1:c1" {
    container c2 {
      leaf l { type t; }
    }
  }
}
```
If `st_l` represents the statement `leaf l {...}`, the expression `statements.search_typedef(st_l, "t")` yields `None`. Or perhaps the two functions are not intended to be used in a plugin code?

**Comment by mbj4668** [comment]
Hi,

Sorry for the very late reply.

After expansion, the typedef is available as the 'type's statement i_typedef property.   The search_ functions work - as you noted - before expansion.
