### ISSUE TITLE
Validate YAML instance through YANG model

### ISSUE THREAD

**Issue by gerardo-garcia** [mbj4668/pyang#292]
I am looking for a library or tool that allows me to validate a file written in YAML against a YANG model, obtaining, as a result, a Python object with the content once validated. I have just discovered PYANG and I think that it might be useful for the purpose, but I am a bit lost. Can you tell me if PYANG can be used for that purpose?

Right now, the validation I'm doing is against a JSON schema. See attached file ([test3.txt](https://github.com/mbj4668/pyang/files/663336/test3.txt)) with a Python example using the current validation. Every time there is a change in the original YANG model, I need to apply that change manually to my JSON schema. That manual task is  what I want to avoid. Is it possible with PYANG? Can I automate it somehow?

**Comment by mbj4668** [comment]
There is no std encoding of YANG-defined data in YAML.  pyang doesn't validate YAML files against a YANG model.  But you could write a plugin to do this, but there is no point in translating the YANG module itself to YAML.

**Comment by gerardo-garcia** [comment]
Thanks for your answer. Is there a standard way of encoding YANG-defined data in XML or JSON?
If so, is there a plugin to do that inside pyang? I could inspire on it for the YAML case.

**Comment by mbj4668** [comment]
Yes, RFC 7950 defines XML encoding and RFC 7951 defines JSON encoding.
yang2dsdl in pyang can validate instance data in XML.

**Comment by llhotka** [comment]
Also, JSON can be directly validated with Yangson:

https://github.com/CZ-NIC/yangson
