### ISSUE TITLE
In pyang  we are not able to convert bits with positions above 63

### ISSUE THREAD

**Issue by amundra30** [mbj4668/pyang#299]
PYANG VERSION : 1.5
ERROR 
confdc -c total_yang/bbf-vdsl-base-body.yang -o confd-fxs/bbf-vdsl-base-body.fxs --yangpath total_yang/total_yang/bbf-vdsl-base-body.yang:587: error: Cannot convert bits with positions above 63.

Because this error we can not able to genrate the fxs file of the yang & pyang not able to genrate the yang tree .

In yang we have bitmap of bit position 68.
How we can resolve this issue ?? or either Pyang is restricting it ??
If some alternative suggest me ??

**Comment by mbj4668** [comment]
This is not a pyang issue.  You are running 'confdc', not pyang.

**Comment by amundra30** [comment]
But Internally in make file we use pyang tool also . Tell me one thing pyang suport more than 64 bits or not to genrate a yang tree.

**Comment by mbj4668** [comment]
If you have a problem with pyang and bits, please include (1) the pyang command you use and (2) the relevant data models and (3) the error.
