### ISSUE TITLE
errors parsing standard yang files

### ISSUE THREAD

**Issue by davemiedema** [mbj4668/pyang#301]
The model here https://github.com/OpenROADM/OpenROADM_MSA_Public/tree/master/Version%201.2

cannot be parsed anymore with 1.7 or 1.7.1.  They were successfully parsed with 1.6.

Is this an issue with the model or the parser?

Here are some of the errors

yangtest/ietf-netconf.yang:103: error: bad value "candidate" (should be identifier-ref)
yangtest/ietf-netconf.yang:103: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:378: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:389: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:435: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:441: error: bad value "writable-running" (should be if-feature-expr)
yangtest/ietf-netconf.yang:470: error: bad value "validate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:524: error: bad value "url" (should be if-feature-expr)
yangtest/ietf-netconf.yang:551: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:557: error: bad value "writable-running" (should be if-feature-expr)
yangtest/ietf-netconf.yang:564: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:570: error: bad value "url" (should be if-feature-expr)
yangtest/ietf-netconf.yang:588: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:599: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:605: error: bad value "url" (should be if-feature-expr)
yangtest/ietf-netconf.yang:638: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:644: error: bad value "url" (should be if-feature-expr)
yangtest/ietf-netconf.yang:672: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:683: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:711: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:722: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:782: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:792: error: bad value "confirmed-commit" (should be if-feature-expr)
yangtest/ietf-netconf.yang:800: error: bad value "confirmed-commit" (should be if-feature-expr)
yangtest/ietf-netconf.yang:812: error: bad value "confirmed-commit" (should be if-feature-expr)
yangtest/ietf-netconf.yang:831: error: bad value "confirmed-commit" (should be if-feature-expr)
yangtest/ietf-netconf.yang:846: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:855: error: bad value "confirmed-commit" (should be if-feature-expr)
yangtest/ietf-netconf.yang:877: error: bad value "validate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:895: error: bad value "candidate" (should be if-feature-expr)
yangtest/ietf-netconf.yang:906: error: bad value "startup" (should be if-feature-expr)
yangtest/ietf-netconf.yang:912: error: bad value "url" (should be if-feature-expr)
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:104 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:579 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:592 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:667 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:677 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:703 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:713 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:786: error: org-openroadm-device:org-openroadm-device in the path for circuit-pack-name at yangtest/org-openroadm-device.yang:763 (at yangtest/org-openroadm-device.yang:782) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:104 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:592 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:667 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:677 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:703 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-device.yang:797: error: org-openroadm-device:org-openroadm-device in the path for port-name at yangtest/org-openroadm-device.yang:713 (at yangtest/org-openroadm-device.yang:793) is not found
yangtest/org-openroadm-syslog.yang:166: error: bad value "selector-sevop-config" (should be if-feature-expr)

**Comment by davemiedema** [comment]
Thanks!!

**Comment by mbj4668** [comment]
Sorry, bad checkin, fixed properly in c23f38f05f7e91bdfcf51bb9639676e4747ac44d
