### ISSUE TITLE
Issue on compilation in pyang 1.7 version to genrate .yin file

### ISSUE THREAD

**Issue by aniayu** [mbj4668/pyang#304]
pyang -f yin -a /repo/amundra/CI_VDSL2/sw/vobs/dsl/yang/IACM/NOKIA_CONFD_ANN/DHCPv4Relay/nokia-bbf-dhcpv4-ann.yang -p total_yang total_yang/bbf-dhcpv4.yang -o yin/bbf-dhcpv4.yin
Usage: pyang [options] [<filename>...]
Validates the YANG module in <filename> (or stdin), and all its dependencies.
Error:
**pyang: error: no such option: -a**

pyang version - 1.7

on compilation using latest pyang version 1.7 facing an issue that no option "-a " to attach annotation file . The same satament using pyang 1.5 version compiling siuccesfully ,.

Tell me solution how to resolve this issue .I stuck because of this .Suggest me bertter way to resolve it .

Regards,
Ayushi Mundra

**Comment by mbj4668** [comment]
-a is a tail-f specific option.  Make sure you have tailf.py in the pluginpath.

**Comment by aniayu** [comment]
I cross check that inside plugin path there is tailf.py is present . still I am getting error .
Now what to do .

**Comment by rainbowbird** [comment]
@mbj4668 will add tailf.py in the upstream?

**Comment by mbj4668** [comment]
No, tailf.py is tail-f specific, and I want to keep this repo vendor-neutral.

**Comment by rainbowbird** [comment]
okay.
