### ISSUE TITLE
In pyang 1.7 version on compilation "-a" option throwing an error 

### ISSUE THREAD

**Issue by aniayu** [mbj4668/pyang#305]
on compilaton with attching annotation file
"pyang: error: no such option: -a"
I checked in plugib path tailf.py file is present dere still same error occurs .
How to resolve this using 1.7 version of pyang

**Comment by mbj4668** [comment]
The -a option is defined in tailf.py.  Check your tailf.py version to make sure it is there.  Do a pyang -h.  Does it show -a?  Does it show any other tailf-specific option?  If it doesn't then it means the plugin isn't loaded, which means it is not present in your plugin path.
