### ISSUE TITLE
should be if-feature-expr

### ISSUE THREAD

**Issue by jasonwin35** [mbj4668/pyang#309]
Do you know problem which display this error message the following as below:

ietf-interfaces.yang:240: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:309: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:395: error: bad value "if-mib" (should be if-feature-expr)

Please, Thanks a lots.

**Comment by mbj4668** [comment]
Running: "pyang ietf-interfaces.yang" works fine.

Which version of pyang are you using?  Which command are you running?


/martin

**Comment by jasonwin35** [comment]
No, The message still display error. 
# pyang ietf-interfaces.yang
ietf-interfaces.yang:240: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:309: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:395: error: bad value "if-mib" (should be if-feature-expr) 

#pyang -v
pyang 1.7.1

I found the pyang/statemonts.py file has some codes for this message.
Is the "# version 1 allows only a single value as if-feature" something happen on different version ?

def v_type_if_feature(ctx, stmt, no_error_report=False):
    """verify that the referenced feature exists."""
    stmt.i_feature = None
    # Verify the argument type
    expr = syntax.parse_if_feature_expr(stmt.arg)
    if stmt.i_module.i_version == '1':
        # version 1 allows only a single value as if-feature
        if type(expr) != type(''):
            err_add(ctx.errors, stmt.pos,
                    'BAD_VALUE', (stmt.arg, 'identifier-ref'))
            return

**Comment by jasonwin35** [comment]
as opposed to 1.1
The "if-feature" statement makes its parent statement conditional. The argument is a boolean expression over feature names. In this expression, a feature name evaluates to "true" if and only if the feature is implemented by the server. The parent statement is implemented by servers where the boolean expression evaluates to "true".

    if-feature-stmt = if-feature-keyword sep if-feature-expr-str optsep stmtend
   
    if-feature-expr-str = < a string that matches the rule if-feature-expr >
    
    if-feature-expr = ’(’ if-feature-expr ’)’ /
                       if-feature-expr sep boolean-operator sep
                         if-feature-expr / 
                       ’not’ sep if-feature-expr /
                       identifier-ref-arg
    
    boolean-operator = ’and’ / ’or’

**Comment by mbj4668** [comment]
Sorry, this seems very odd.  Since I can't reproduce it, I can't do much.  If you can try to debug this it would be appreciated.  Maybe you can print the 'expr' just after the line:
 expr = syntax.parse_if_feature_expr(stmt.arg)

**Comment by jasonwin35** [comment]
I have debugged the expr variable and print out value after the line.  but this "v_type_if_feature" was not entered this code.  I checked another function related the "v_type_if_feature"  and the "validate_if_feature" was be used 6 times and never going to "v_type_if_feature" function. why ? 

def v_type_feature(ctx, stmt):
    if hasattr(stmt, 'i_is_validated'):
        if stmt.i_is_validated == True:
            # this feature has already been validated
            return
        elif stmt.i_is_validated == 'in_progress':
            err_add(ctx.errors, stmt.pos,
                    'CIRCULAR_DEPENDENCY', ('feature', stmt.arg) )
            return

    stmt.i_is_validated = 'in_progress'

    name = stmt.arg

    # search for circular feature definitions
    def validate_if_feature(s):
        if s.keyword == "if-feature":
            v_type_if_feature(ctx, s, no_error_report=True)
    iterate_stmt(stmt, validate_if_feature)

    stmt.i_is_validated = True

**Comment by mbj4668** [comment]
Ok, it is actually the grammar check that returns this error, not the v_type_if_feature function.  Check the function chk_if_feature_expr in syntax.py.  Mayeb you can add some printouts to parse_if_feature_expr to find out what is going wrong.

Which python version are you using?

**Comment by jasonwin35** [comment]
Thank you for your response.
My python version is 2.7, I will debug and print out some information. I will let you know if i have any progress.

**Comment by jasonwin35** [comment]
I have compared  with 32bit Ubuntu for python command (original problem OS platform is 64bit Fedora).
I debugged the "parse_if_feature_expr" function in syntax.py. I found the different printout value. 

Code:
    def y():
        tok = sx.get_token()
        print("tok=%s" % tok)

Command:
Running "sudo pyang -f yin ietf-interfaces.yang -o test.yin"

Result:
64bit Fedora:
s=if-mib
tok=i
s=if-mib
tok=i
s=if-mib
tok=i
ietf-interfaces.yang:240: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:309: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:395: error: bad value "if-mib" (should be if-feature-expr)

32bit Ubuntu:
s=if-mib
tok=if-mib
s=if-mib
tok=if-mib
s=if-mib
tok=if-mib
s=if-mib
tok=if-mib
s=if-mib
tok=if-mib
s=if-mib
tok=if-mib

Why is the "tok" value for getting the all work (if-mib) and first character ( i ) ?

**Comment by mbj4668** [comment]
The code uses the standard module "shlex".  Maybe it behaves differently on Fedora?  Could you try this:

    $ python
    Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import shlex
    >>> sx = shlex.shlex("if-mib")
    >>> sx.wordchars += ":-"
    >>> sx.get_token()
    'if-mib'
    >>> sx.get_token()
    ''

**Comment by jensencj** [comment]
dear mbj4668, I encounter the same problem as jasonwin35, when I run the pyang command, pyang ietf-interfaces.The program goes wrong.
ietf-interfaces.yang:241: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:310: error: bad value "if-mib" (should be if-feature-expr)
ietf-interfaces.yang:398: error: bad value "if-mib" (should be if-feature-expr)

I try to debug the pyang program. Add some debug imformation to the program.
![image](https://user-images.githubusercontent.com/9319500/30948072-15c8901e-a440-11e7-863f-76ff89520193.png)
I run the pyang command again, the output is:
![image](https://user-images.githubusercontent.com/9319500/30948084-2e5a997e-a440-11e7-8911-df935dcab934.png)
When I run the shelx command in python shell, the output is same as you say. I can not find the reason why the shlex token of if-mib is i。

**Comment by mbj4668** [comment]
Which OS and python version are you running?

**Comment by jensencj** [comment]
the OS version is centos7.0, the python version is 2.7.1, the pyang version is 1.7.3

**Comment by mbj4668** [comment]
I think I found the issue.  In the documentation to shlex, it says: Prior to Python 2.7.3, this module did not support Unicode input.

Trying this on python 2.4 I get:

    >>> import shlex
    >>> sx = shlex.shlex(u'if-mib')
    >>> sx.wordchars += ":-"
    >>> sx.get_token()
    'i'

Try to upgrade python to >= 2.7.4

**Comment by mbj4668** [comment]
Hmm, I think it would be safe to convert the string to ascii before calling shlex, since all parts are supposed to be identifers.

**Comment by jensencj** [comment]
I try to convert the string to ascii, and it works. Thanks a lot!

**Comment by mbj4668** [comment]
I've fixed this in the code, will soon push a fix
