### ISSUE TITLE
Convertation yang to mib, smi plugin 

### ISSUE THREAD

**Issue by aksenofontova** [mbj4668/pyang#317]
Hello, Pyang Team.
Can i convert my yang model to mib file? Where i can get smi plugin, if it is need.
Thank you for your work, 
Anna.

**Comment by mbj4668** [comment]
Hi,

pyang does not have a plugin that creates a MIB module from a YANG module.  It can be done, but someone has to write such a plugin.

What do you mean with "smi plugin"?

**Comment by aksenofontova** [comment]
Hi,

I was looking for a solution for convert YANG to MIB and found such a note http://help.openclovis.com/index.php/Convert_YANG_to_MIB_model
about conversion with some smi plugin.

**Comment by remingtonc** [comment]
Based on the documentation, that appears to be a better question for https://github.com/OpenClovis than pyang. Would be nice if they open sourced it :)
