### ISSUE TITLE
XPath function "compare" is not defined in the XPath context

### ISSUE THREAD

**Issue by airshiplay** [mbj4668/pyang#328]
container end
                {
                    tailf:cli-flatten-container;
    
                    leaf end_date
                    {
                        tailf:cli-drop-node-name;
                        tailf:cli-incomplete-command;
                        type xs:date; 
                    }
                    
                    leaf end_time
                    {
                        tailf:cli-drop-node-name;
                        type xs:time;
                        
                        must "compare(../end_date, ../../start/start_date) = 1 
                            or (compare(../end_date, ../../start/start_date) = 0 and compare(../end_time, ../../start/start_time) = 1) "
                        {
                           error-message "The end time can not less than start time!";
                        }

                    }
                }

**Comment by mbj4668** [comment]
compare() is not a core XPath 1.0 function, nor is it a standard YANG extension, thus it is rejected by pyang.  You can use --lax-xpath-checks to make pyang accept this.

(compare() is a XPath 2.0 function that tail-f supports, as an extension)
