### ISSUE TITLE
Pyang: No result in converting Json

### ISSUE THREAD

**Issue by andersliuc** [mbj4668/pyang#332]
Hi, I want to convert yang to json refer to XmlJson: https://github.com/mbj4668/pyang/wiki/XmlJson.
Firstly, I use pyang to convert yang to xml(yin) and xsl, then I use xsltproc to convert them to json.
But there is no result for the command of xsltproc, Is it something wrong with my steps?

**Comment by llhotka** [comment]
We cannot tell until you show us what your steps are. Note that you cannot convert YANG to JSON, you can only convert between XML and JSON representations of **instance data**.
