### ISSUE TITLE
Pattern in key attribute gives error [error: unexpected keyword "pattern"]

### ISSUE THREAD

**Issue by baovu2** [mbj4668/pyang#334]
Pyang compilation with key attribute of string type gives error when pattern is defined 'error: unexpected keyword "pattern" '. I don't see any restriction with the pattern statement that it cannot be used for key attribute.

**Comment by mbj4668** [comment]
Please include the YANG module that gives the error, otherwise it is difficult to do anything...

**Comment by baovu2** [comment]
Sample yang
========
module mysample-iproute {
    yang-version 1.1;
    namespace "urn:sample.com:mgmt:mysample-iproute";
    prefix "mysample-iproute";

    organization "mysample";
    contact "support@sample.com";
    description
        "The module for sample iproute.";

    revision 2007-11-05 {
        description "Initial revision.";
	reference "None";
    }

    container mysample-iproute{
	description "Sample Iproute container";
        list iproute {
            key "name";
            description "List of interfaces in the system";
            leaf name {
                type string;
		pattern '(([0-9]{1,2})\/([0-9]{1,2}))';
		description "slot/port argument of the interface";
            }
            leaf ip{
                type string;
		description "IP address subnet";
            }
            leaf prefix{
                type string;
		description "prefix length";
            }
            leaf gateway{
                type string;
		description "gateway";
            }
        }
    }
}

Compilation:
=========
pyang -f yin --yin-canonical --strict --lint mysample-iproute.yang 
**mysample-iproute.yang:23: error: unexpected keyword "pattern"**
<?xml version="1.0" encoding="UTF-8"?>
<module name="mysample-iproute"
        xmlns="urn:ietf:params:xml:ns:yang:yin:1"
        xmlns:mysample-iproute="urn:sample.com:mgmt:mysample-iproute">
  <yang-version value="1.1"/>
  <namespace uri="urn:sample.com:mgmt:mysample-iproute"/>
  <prefix value="mysample-iproute"/>
  <organization>
    <text>mysample</text>
  </organization>
  <contact>
    <text>support@sample.com</text>
  </contact>
  <description>
    <text>The module for sample iproute.</text>
  </description>
  <revision date="2007-11-05">
    <description>
      <text>Initial revision.</text>
    </description>
    <reference>
      <text>None</text>
    </reference>
  </revision>
  <container name="mysample-iproute">
    <description>
      <text>Sample Iproute container</text>
    </description>
    <list name="iproute">
      <key value="name"/>
      <description>
        <text>List of interfaces in the system</text>
      </description>
      <leaf name="name">
        <type name="string"/>
        <pattern value="(([0-9]{1,2})\/([0-9]{1,2}))"/>
        <description>
          <text>slot/port argument of the interface</text>
        </description>
      </leaf>
      <leaf name="ip">
        <type name="string"/>
        <description>
          <text>IP address subnet</text>
        </description>
      </leaf>
      <leaf name="prefix">
        <type name="string"/>
        <description>
          <text>prefix length</text>
        </description>
      </leaf>
      <leaf name="gateway">
        <type name="string"/>
        <description>
          <text>gateway</text>
        </description>
      </leaf>
    </list>
  </container>
</module>

**Comment by mbj4668** [comment]
The error description tells you what is wrong - "pattern" is not expected at this point. "pattern" is a substatement to "type".

Also, you must not escape the / with a \ within single quotes.
