### ISSUE TITLE
How to generate .xml file required to generate .json from .xsl

### ISSUE THREAD

**Issue by sidheshdivekar29** [mbj4668/pyang#338]
Hi,
I am not sure as to how to generate "turning-machine-config.xml" used below for my model.
xsltproc -o turing-machine-config.json tm-json.xsl turing-machine-config.xml

**Comment by tmkkopec** [comment]
You can generate sample .xml based on yang model by using sample-xml-skeleton pyang plugin:
pyang -f sample-xml-skeleton -o turing-machine-config.xml turing-machine.yang

**Comment by llhotka** [comment]
This is correct. The sample XML file usually has to be manually edited.
