### ISSUE TITLE
PYANG DOESNOT SUPPORT description keyword in deviation

### ISSUE THREAD

**Issue by amundra30** [mbj4668/pyang#339]
Hi ,

In deviation "xpath" {
 deviate replace {
   descrption "example abc not " 
}
}

ITS throwing an error unexpected keyword description .
Pyang version :1.7.2
is pyang support description keyword in deviate / deviation ?
If need other info let me know .

**Comment by mbj4668** [comment]
"description" is not legal as a substatement to "deviate", according to RFC 6020, section 7.18.3.2.
