### ISSUE TITLE
RFE: Maintaining string plus'ing in yang output

### ISSUE THREAD

**Issue by AlphaKoder** [mbj4668/pyang#342]
Enhancement request:

When using pyang -f yang to "pretty print" a YANG file, pyang does not maintain the string concatenation syntax.

For example:
```
    pattern "foo|" +
                 "bar";
```

will become
```
    pattern "foo|bar";
```

This may be preferable for some (particularly those trying to read YANG files programmatically who just want a single string); however, it does cause problems if the intent was to clean up the indentation, but not at the cost of altering the file contents.

Would it be possible to add a CLI switch to prevent plus'd strings from being concatenated?

**Comment by mbj4668** [comment]
With the latest code, pyang keeps concatented strings.
