### ISSUE TITLE
pyang does not catch incorrect compare value for identityref

### ISSUE THREAD

**Issue by mjethanandani** [mbj4668/pyang#345]
Using ietf-dslite@2017-11-15.yang and ietf-nat@2017-11-15.yang from draft-ietf-softwire-dslite-yang-10 and draft-ietf-opsawg-nat-yang-09 respectively, the following comparison is incorrect.

XPath:/nat:nat/nat:instances/nat:instance/nat:type='napt44' and /nat:nat/nat:instances/nat:instance/nat:per-interface-binding='dslite'
ietf-dslite@2017-11-15.yang: line 155: warning(1052): XPath compare value invalid for YANG type

and

Warning: compare value 'napt44' invalid for object 'ietf-nat:type type:identityref'
XPath:/nat:nat/nat:instances/nat:instance/nat:type='napt44' and /nat:nat/nat:instances/nat:instance/nat:per-interface-binding='dslite'
ietf-dslite@2017-11-15.yang: line 248: warning(1052): XPath compare value invalid for YANG type

That is because per YANG RFC,

9.10.2.  The identityref's "base" Statement
 
   The "base" statement, which is a substatement to the "type"
   statement, MUST be present at least once if the type is
   "identityref".  The argument is the name of an identity, as defined
   by an "identity" statement.  If a prefix is present on the identity
   name, it refers to an identity defined in the module that was
   imported with that prefix.  Otherwise, an identity with the matching
   name MUST be defined in the current module or an included submodule.

**Comment by mbj4668** [comment]
Right, pyang doesn't have an XPath parser, so it can't detect these things.
