### ISSUE TITLE
Min-elements is not enforced for leaf-list if it's container's when statement is evaluated true

### ISSUE THREAD

**Issue by szabolcsszekely** [mbj4668/pyang#349]
If a leaf-list has a min-elements substatement, and the leaf-list is in a container with a when substatement, the min-elements is not enforced by yang2dsdl even if the when substatement of the container is evaluated to true.
Based on the YANG RFC, I  expected that the min-elements will be enforced during validation. For example, the commercial netconf implementation ConfD works like this.

It looks like to me, that ConfD creates the non-presence containers if their when statements evaluates to true, while pyang/yang2dsdl does not.

Example:
```
$ cat main.yang
module main {
    yang-version 1;
    namespace
        "http://main.com";

    prefix main;

    container all {
        leaf parameter {
            type enumeration {
                enum on;
                enum off;
            }
        }
        container list-of-test {
            when "../parameter = 'on'";
            leaf-list test {
                min-elements 1;
                type string;
            }
        }
    }
}

$ cat test-main.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <all xmlns="http://main.com">
    <parameter>on</parameter>
  </all>
</config>

$ yang2dsdl -j -t config -v test-main.xml main.yang
== Generating RELAX NG schema './main-config.rng'
Done.

== Generating Schematron schema './main-config.sch'
Done.

== Generating DSRL schema './main-config.dsrl'
Done.

== Validating grammar and datatypes ...
test-main.xml validates.

== Adding default values... done.

== Validating semantic constraints ...
No errors found.

pyang version: ce0e806 Merge pull request #331 from glennmatthews/persnickety
```

I expected this error message:
`error: element "list-of-test" incomplete; missing required element "test"`

This is a limitation of pyang/yang2dsdl or the standard does not require this?

**Comment by llhotka** [comment]
This is caused by the fact that the number of list entries is validated using the RELAX NG schema (via ``<oneOrMore>`` pattern) but RELAX NG is not able to determine whether the **when** expression is true or false, so the constraint isn't enforced.
