### ISSUE TITLE
leafref among different submodules

### ISSUE THREAD

**Issue by mc-cisco** [mbj4668/pyang#355]
module a {
  yang-version 1.1;
  namespace "http://my.com/a";
  prefix a;
 
  include b;
  include c;

  container node {
    uses b-grp;
    uses c-grp;
  }
}

-----------------------------------

submodule b {
  yang-version 1.1;
  belongs-to a {
    prefix a;
  } 

  grouping b-grp {
    leaf c-ref {
      type leafref {
        path "../c-name";
      }
    }
  }
}

----------------------------------------

submodule c {
  yang-version 1.1;
  belongs-to a {
    prefix a;
  } 

  grouping c-grp {
    leaf c-name {
      type string;
    }
  }
}

---------------------------------------

$pyang -version
$pyang 1.7.3
$pyang a.yang
$b.yang:10: error: a:c-name in the path for c-ref at a.yang:10 (at b.yang:8) is not found

I didn't find any reason why this is not working, am I missing something here?
Thanks,
Marco.

**Comment by mbj4668** [comment]
This is a duplicate of #323, closing.
