### ISSUE TITLE
Unable to parse yang files which depends on ietf-restconf (2015-01-30)

### ISSUE THREAD

**Issue by rkosegi** [mbj4668/pyang#356]
Unable to parse yang files which depends on ietf-restconf (2015-01-30)

```
pyang  --lint  -p test-data test-data/standard/ietf/DRAFT/ietf-restconf-collection.yang 
test-data/standard/ietf/DRAFT/ietf-restconf-collection.yang:69: error: unexpected keyword "rc:restconf-media-type"

```

Version of pyang

> pyang --version
> pyang 1.7.3

Please note that when downgrading pyang to 1.7.1, parsing run ok.

**Comment by mbj4668** [comment]
Try -p test-data/standard/ietf/DRAFT ...

**Comment by rkosegi** [comment]
Problem is not about resolving dependent modules, but with ietf-restconf module.
I have seen this sentence in most recent release notes:

- Handle multiple rc:yang-data statements. This bug caused validation of ietf-restconf, or any module that imported ietf-restconf, to fail.

Could that be related to my issue?

**Comment by mbj4668** [comment]
With the latest (github) version of pyang, and the latest (draft -05) versions of the routing modules, I can validate all the modules.  However, if I don't add the correct path to their directory, I get the same errors asa you do.

**Comment by rkosegi** [comment]
We use these yang models to test our tool based on pyang https://github.com/YangModels/yang/tree/tnadeau-patch-4/standard/ietf

But this one fails : https://github.com/netconf-wg/restconf-collection/blob/master/ietf-restconf-collection.yang

So question is, can recent version (1.7.3) of pyang parse this?
Version 1.7.1 has no issue with it.
This lead us to decision if we stuck with old version which works (1.7.1) or be backward incompatible.

**Comment by mbj4668** [comment]
Were you now able to check the ietf-ipv6-unicast-routing.yang?

What error do you get for ietf-restconf-collection?

Did you try with the latest github code?

**Comment by rkosegi** [comment]
ietf-ipv6-unicast-routing.yang is fine.

ietf-restconf-collection.yang fails

If I don't provide valid path it fail like this:
```
pyang  --lint   DRAFT/ietf-restconf-collection.yang 
DRAFT/ietf-restconf-collection.yang:5: error: module "ietf-restconf" not found in search path
DRAFT/ietf-restconf-collection.yang:69: error: unexpected keyword "rc:restconf-media-type"

```
If I provide valid path it fail too:
```
pyang  --lint -p ..  DRAFT/ietf-restconf-collection.yang 
DRAFT/ietf-restconf-collection.yang:69: error: unexpected keyword "rc:restconf-media-type"

```

**Comment by mbj4668** [comment]
I would guess that you need -p DRAFT
Note that ietf-restconf-collection was never published, and it uses constructs from an early, unpublished version of ietf-restconf, so it is important to compile it with the correct modules.

**Comment by rkosegi** [comment]
Ok, so it is safe to unsupport ietf-netconf(2015-01-30) ?

**Comment by mbj4668** [comment]
Did you mean ietf-restconf?  Anyway, it is safe to not support any unpublished module, especially the ones that later have been published.

**Comment by rkosegi** [comment]
Yes, you are right, it was typo.
Thanks for confirmation.
