### ISSUE TITLE
leaf-list validation fails if default is set

### ISSUE THREAD

**Issue by santmalta** [mbj4668/pyang#363]
Given the following YANG module:

`module leafListErrorOnDefault {
    namespace "foo:me";
    prefix "me";

    leaf-list myne {
        type string;
        default "bar";
    }
}
`

and trying to validate it with pyang 1.7.3 on Linux:

`pyang leafListErrorOnDefault.yang`

the following error is generated:

`leafListErrorOnDefault.yang:7: error: unexpected keyword "default"`

**Comment by mbj4668** [comment]
This works as expected.  "default" is not valid in "leaf-list" in YANG 1.0.  It is valid in YANG 1.1 though.

**Comment by santmalta** [comment]
Hi Martin, I am confused:

I used the latest tag 1.7.3, but it is not 1.1 compliant? How to find out which version is 1.1 compliant?

BR

Axel

**Comment by mbj4668** [comment]
add statement  yang-version 1.1; 
directly before namespace.  see RFC 7950.

**Comment by santmalta** [comment]
Ok. Thank you very much for the fast and kind answer!
