### ISSUE TITLE
pyang CLI command not found after installation

### ISSUE THREAD

**Issue by Mazimer** [mbj4668/pyang#366]
I've installed pyangbind with pip3 install pyangbind after which, as i understand it, a shell command should be available. The problem is, that command is simply not showing up and googling has not yielded anyone else having a similar issue.

i'm running a clean install of kubuntu 17.10 VM on a Windows host.

any help would be appreciated.

**Comment by mbj4668** [comment]
I think you need to report this error to pyangbind.
