### ISSUE TITLE
how to run pyang plugin on all the yang files within a folder

### ISSUE THREAD

**Issue by mohitmessi007** [mbj4668/pyang#368]
i want to run my custom plugin all the yang modules within a subfolder
so what i can do

i tried like: pyang -f xpath ./
but it wont work

**Comment by remingtonc** [comment]
@mohitmessi007 Assuming Linux or MacOS, this `bash` script might help. Runs your plugin using all cores available.
```bash
PLUGIN_NAME=<your_plugin_name>
NUM_PROCS=0
UNAME="$(uname -s)"
case "${UNAME}" in
    Linux*)     NUM_PROCS=$(grep -c ^processor /proc/cpuinfo);;
    Darwin*)    NUM_PROCS=$(sysctl -n hw.ncpu);;
esac
printf "Using ${NUM_PROCS} processes.\n"
find . -name "*.yang" | xargs -P $NUM_PROCS -n 1 -I {} bash -c 'cd $(dirname {}) && pyang -f $PLUGIN_NAME $(basename {}) > $(basename {}).$PLUGIN_NAME'
```

**Comment by mohitmessi007** [comment]
thanx @remingtonc 
i solved the issue
i was missing a * in the previous implementation and path for the imported yang files.

this line worked perfectly-
pyang --plugindir plugins --path plugins --path ../18.2/yang/ --path ../18.2/augment --path ../18.2/dynamic-rendering/ -f xpath ../18.2/dynamic-rendering/* > /homes/amohit/xpath.xml

Thank you

**Comment by jamalakhaligova** [comment]
How can this issue be solved in Windows OS?
