### ISSUE TITLE
sample-xml-skeleton does not work with some valid models

### ISSUE THREAD

**Issue by Reshad-Rahman** [mbj4668/pyang#371]
FYI, the OSPF YANG doesn’t give much (but no errors as in BFD case), but the routing one does give good skeleton. Acee, wondering if you’ve tried to use sample-xml-skeleton with the OSPF YANG?
 
RRAHMAN-M-545W:Modules rrahman$ pyang ietf-ospf\@2017-10-30.yang -p ../.. -f sample-xml-skeleton  --verbose --lax-quote-checks 
<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" />RRAHMAN-M-545W:Modules rrahman$ 
 
RRAHMAN-M-545W:Modules rrahman$ pyang -p ../.. -f sample-xml-skeleton ietf-routing.yang  --lax-quote-checks 
<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><routing xmlns="urn:ietf:params:xml:ns:yang:ietf-routing"><router-id /><interfaces><interface /></interfaces><control-plane-protocols><control-plane-protocol><type /><name /><description /><static-routes /></control-plane-protocol></control-plane-protocols><ribs><rib><name /><address-family /><routes><route><route-preference /><next-hop><outgoing-interface /><special-next-hop /><next-hop-list><next-hop><outgoing-interface /></next-hop></next-hop-list></next-hop><source-protocol /><active /><last-updated /></route></routes><description /></rib></ribs></routing><routing-state xmlns="urn:ietf:params:xml:ns:yang:ietf-routing"><router-id /><interfaces><interface /></interfaces><control-plane-protocols><control-plane-protocol><type /><name /></control-plane-protocol></control-plane-protocols><ribs><rib><name /><address-family /><routes><route><route-preference /><next-hop><outgoing-interface /><special-next-hop /><next-hop-list><next-hop><outgoing-interface /></next-hop></next-hop-list></next-hop><source-protocol /><active /><last-updated /></route></routes></rib></ribs></routing-state></data>RRAHMAN-M-545W:Modules rrahman$
 
 
From: "Reshad Rahman (rrahman)" <rrahman@cisco.com>
Date: Friday, February 23, 2018 at 6:07 PM
To: Martin Bjorklund <mbj@tail-f.com>
Subject: pyang sample-xml-skeleton
 
Hi Martin,
 
I can’t get the sample skeleton to work with the BFD modules, and I can’t figure out why. The modules are/seem valid, any ideas?
 
Thanks,
Reshad.
 
$ pyang -p ../.. -f tree ietf-bfd\@2018-01-22.yang    --verbose
../../YANG/Modules/ietf-netconf-acm.yang:103: warning: the escape sequence "\*" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
../../YANG/Modules/ietf-netconf-acm.yang:144: warning: the escape sequence "\*" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
ietf-netconf-acm.yang:103: warning: the escape sequence "\*" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
ietf-netconf-acm.yang:144: warning: the escape sequence "\*" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
module: ietf-bfd
  augment /rt:routing/rt:control-plane-protocols/rt:control-plane-protocol:
    +--rw bfd
       +--ro session-statistics
          +--ro session-count?              uint32
          +--ro session-up-count?           uint32
          +--ro session-down-count?         uint32
          +--ro session-admin-down-count?   uint32
$ pyang -p ../.. -f sample-xml-skeleton ietf-bfd\@2018-01-22.yang  --lax-quote-checks  --verbose
sample-xml-skeleton plugin needs a valid module
$

**Comment by llhotka** [comment]
You cannot get the skeleton (= XML instance document) for a module that only augments another. You have to add the augmented module, i.e. `ietf-routing` in this case.

**Comment by Reshad-Rahman** [comment]
Thanks Lada, makes sense. The error message should be a bit more descriptive than "needs a valid module"
