### ISSUE TITLE
Yang modules starting with [Xx] [Mm] [Ll]

### ISSUE THREAD

**Issue by ankitjain093** [mbj4668/pyang#374]
Hi

I wanted to know why does pyang not support compiling yang modules starting with [Xx] [Mm] [Ll], 

> error: illegal identifier "xmlproxyd_sysusers", must not start with [xX][mM][lL]

Is it a pyang specific restriction or an RFC prescription? ( Couldn't locate this in RFC 7950)

Thanks
Ankit

**Comment by mbj4668** [comment]
This is a RFC 6020 restriction that was lifted in RFC 7950.  Try to use yang-version 1.1.

**Comment by ankitjain093** [comment]
Thanks Martin,

I see at
https://github.com/mbj4668/pyang/blob/master/pyang/grammar.py#L647

that the code forgives the [Xx Mm Ll] syntax but insists on emitting the warning about incorrect syntax.

Can the warning be made conditional to yang version < 1.1
