### ISSUE TITLE
pyang crashes with pip 10.0.0 on macOS

### ISSUE THREAD

**Issue by dmfigol** [mbj4668/pyang#387]
Hi,
pyang crashes with pip version 10.0.0 on macos with the following traceback:

```
-> % pyang -f tree
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 450, in <module>
    run()
  File "/usr/local/bin/pyang", line 225, in run
    repos = pyang.FileRepository(path, no_path_recurse=o.no_path_recurse)
  File "/usr/local/lib/python3.6/site-packages/pyang/__init__.py", line 418, in __init__
    location = pip.locations.distutils_scheme('pyang')
AttributeError: module 'pip' has no attribute 'locations'
```
It does not crash on pip 9.0.3
Tested only on macOS, haven't tested on other OS.

**Comment by mbj4668** [comment]
Hi, I think this works now.  Apparently they changed the pip internals in 10.

**Comment by yamekimsense** [comment]
Pls, run in virtual environment and then, there will be no error.

**Comment by yamekimsense** [comment]
https://info.tail-f.com/hubfs/Whitepapers/Replacing%20the%20pyang%20Tool%20Rev%20A%202019-03-13.pdf
