### ISSUE TITLE
[feature request] tree plugin: fully describe the paths when the leafref types are referenced indirectly through a typedef

### ISSUE THREAD

**Issue by jean-christophe-manciot** [mbj4668/pyang#391]
Ubuntu 17.10
pyang 1.7.5 from PyPi
example yang modules from [official Ynag Models](https://github.com/YangModels/yang): 
- (1) ```ietf-interfaces@2018-02-20.yang```
- (2) ```ietf-hardware@2018-03-13.yang```

The goal is to **improve the readability** of the converted module into a tree without the need to consult the corresponding yang module.

For instance, (1) contains:
```
...
  typedef interface-ref {
    type leafref {
      path "/if:interfaces/if:interface/if:name";
    }
    description
      "This type is used by data models that need to reference
       interfaces.";
  }
...
      leaf-list higher-layer-if {
        type interface-ref;
        config false;
        description
          "A list of references to interfaces layered on top of this
           interface.";
        reference
          "RFC 2863: The Interfaces Group MIB - ifStackTable";
      }
...
```
which is currently translated with the tree plugin into:
```
  |     +--ro higher-layer-if*            interface-ref
```
In order to understand what the reference points to, it is necessary to consult the yang module.

It could rather be translated into:
```
  |     +--ro higher-layer-if*            -> /interfaces/interface/name
```

An example which is fully translated is with (2):
```
...
      leaf-list contains-child {
        type leafref {
          path "../../component/name";
        }
        config false;
        description
          "The name of the contained component.";
        reference
          "RFC 6933: Entity MIB (Version 4) - entPhysicalChildIndex";
      }
..
```
which is translated into:
```
        +--ro contains-child*   -> ../../component/name
```

**Comment by mbj4668** [comment]
It is not that clear which version is more readable.  If there is a typedef, the tree output will print the typedef's name, as you noted.  The thinking behind this is that if there is a typedef, it is (supposedly) on a higher abstraction level.
