### ISSUE TITLE
RuntimeError: dictionary changed size during iteration in pyang 1.7.5

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [mbj4668/pyang#392]
Hello, im trying to convert yang files using pyang and pyangbind.
but pyang 1.7.5 have bugs.

this is the error code.

>     ubuntu@ubuntu:~$ pyang --plugindir $PYBINDPLUGIN -f pybind -o ietf_ip_binding.py ietf-ip.yang ietf-interfaces.yang ietf-inet-types.yang ietf-yang-types.yang
>     Traceback (most recent call last):
>       File "/usr/local/bin/pyang", line 450, in <module>
>         run()
>       File "/usr/local/bin/pyang", line 419, in run
>         emit_obj.emit(ctx, modules, fd)
>       File "/usr/local/lib/python2.7/dist-packages/pyangbind/plugin/pybind.py", line 220, in emit
>         build_pybind(ctx, modules, fd)
>       File "/usr/local/lib/python2.7/dist-packages/pyangbind/plugin/pybind.py", line 406, in build_pybind
>         build_identities(ctx, defn['identity'])
>       File "/usr/local/lib/python2.7/dist-packages/pyangbind/plugin/pybind.py", line 446, in build_identities
>         idstore.build_store_from_definitions(ctx, defnd)
>       File "/usr/local/lib/python2.7/dist-packages/pyangbind/helpers/identity.py", line 75, in build_store_from_definitions
>         mod_ref_prefixes = module_import_prefixes(ctx)
>       File "/usr/local/lib/python2.7/dist-packages/pyangbind/helpers/misc.py", line 24, in module_import_prefixes
>         for mod in ctx.modules:
>     RuntimeError: dictionary changed size during iteration

when im trying to downgrade the pyang and pyangbind to 1.7.4 and 0.6.0 this error is not happen again.

**Comment by tarkatronic** [comment]
@zufardhiyaulhaq I believe this was a bug in `pyangbind`, which should be fixed now. v0.7.0 was release recently. If that release is still not working for you, it would be very helpful if you could test against the latest `master` branch in git. If that still doesn't work for you, please create a bug report on `pyangbind` and we can look into it there!

**Comment by zufardhiyaulhaq** [comment]
Hi @tarkatronic, i have fix this issue by downgrade the pip, pyangbind, and pyang. okey thanks now you have fix this issue.

**Comment by carlsaj** [comment]
Hi 

I am having the same issue and i just running the latest version pyang and pyangbind

**Comment by devopsnetworks** [comment]
Facing the issue to create Pyangbid 

(venv) root@DESKTOP-54MQ89O:/home/devex_bc/mdt/output_info# pyang --plugindir \
  /home/venv/lib/python3.10/site-packages/pyangbind/plugin \
  --format pybind ietf-interfaces.yang > ietf-interfaces.py
Traceback (most recent call last):
  File "/home/venv/bin/pyang", line 580, in <module>
    run()
  File "/home/venv/bin/pyang", line 549, in run
    emit_obj.emit(ctx, modules, fd)
  File "/home/venv/lib/python3.10/site-packages/pyangbind/plugin/pybind.py", line 201, in emit
    build_pybind(ctx, modules, fd)
  File "/home/venv/lib/python3.10/site-packages/pyangbind/plugin/pybind.py", line 403, in build_pybind
    build_identities(ctx, defn["identity"])
  File "/home/venv/lib/python3.10/site-packages/pyangbind/plugin/pybind.py", line 448, in build_identities
    idstore.build_store_from_definitions(ctx, defnd)
  File "/home/venv/lib/python3.10/site-packages/pyangbind/helpers/identity.py", line 75, in build_store_from_definitions
    mod_ref_prefixes = module_import_prefixes(ctx)
  File "/home/venv/lib/python3.10/site-packages/pyangbind/helpers/misc.py", line 24, in module_import_prefixes
    for mod in ctx.modules:
RuntimeError: dictionary changed size during iteration
(venv) root@DESKTOP-54MQ89O:/home/devex_bc/mdt/output_info#
