### ISSUE TITLE
Backslash followed by unexpected character in quote should throw error?

### ISSUE THREAD

**Issue by abhikeshav** [mbj4668/pyang#394]
Currently, the below yang model just causes a warning (`ILLEGAL_ESCAPE_WARN`) in pyang `1.7.5`.
```yang
  extension a {
    description
      "((\d+(-\d+)?)(,(\d+(-\d+)?))*)";
        }
```

```
~>pyang ~/Downloads/x.yang
/Downloads/x.yang:114: warning: the escape sequence "\
" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
```

Should pyang change the above warning into an error. Referencing the [3rd paragraph](https://tools.ietf.org/html/rfc7950#page-46) of the RFC and then the one-line sentence "The backslash MUST NOT be followed by any other character.".

(Refer to https://github.com/CESNET/libyang/issues/450)

**Comment by mbj4668** [comment]
If you use YANG 1.1 (yang-version 1.1) in your module, pyang will give an error for this.

In YANG 1, the behaviour was unspecified, hence the warning.
