### ISSUE TITLE
bug for leaf-ref/xpath validation

### ISSUE THREAD

**Issue by GuoyouZhang** [mbj4668/pyang#396]
when pyang convert yang to yin or yin to yang, it will do leaf-ref/xpath validation.  Ideally if submodule A “uses” some grouping/typedef from submodule B, then A should include B. But for xpath, I don’t think it should follow this rule.  Otherwise it is a big limitation for leaf-ref in submodule B.  in my case, A uses B, and A inlucde B, but B also leaf-ref to some leaf defined in A, then pyang report error. see attachment for the detail.  use "pyang --lax-quote-checks -f yin -o epg.yin epg.yang" to see the result.
[yang.zip](https://github.com/mbj4668/pyang/files/2038889/yang.zip)

**Comment by GuoyouZhang** [comment]
I would suggest to remove "if not is_submodule_included(path, ptr)" in function "follow_path". ( line:2695, file: "statements.py") Any comment?

**Comment by GuoyouZhang** [comment]
commit code, please expert to review and merge it. so that I can close this issue.
Change-Id: I979851ec224734d4a59f090587c0dd5d0e391b21

**Comment by mbj4668** [comment]
If a submodule needs to use a definition from another submodule, it needs to include that submodule.  This includes definitions in leafrefs.  Note that this has been relaxed in YANG 1.1 - in 1.1 a submodule automatically has access to all definitions in the module and other submodules.  However, this is not yet implemented in pyang.

**Comment by GuoyouZhang** [comment]
in that case, will this commit be merged?
 or when pyang will support YANG1.1 spec for this part?

**Comment by mbj4668** [comment]
No, this commit is not quite correct, so it won't be merged.  With the commit, we might miss to report some invalid paths.

As for the general case of submodule scoping in 1.1, see [#323](https://github.com/mbj4668/pyang/issues/323)

**Comment by GuoyouZhang** [comment]
@mbj4668 , In #323, at least we can use "include" to workaround it,  but in my case,  there is no way to workaround it. because A includes B, and B also includes A will lead to "circulate include" error.
So what is the community plan to solve this issue,  or you have better way to workaround it?
Many thanks!
