### ISSUE TITLE
Range with min and max values being the same is rejected

### ISSUE THREAD

**Issue by alfleung** [mbj4668/pyang#407]
We have a model with range having min/max values being the same. (An initial setting for future growth of range without using different types.)  This is rejected by pyang.  Trying other validator like yanger, that's not rejected.   It may be caused by a minor comparison setting in types.py:is_smaller? For example,

leaf name-index {
  type uint32 {
    range "1..1";
  }
  description "Group name index";
}

**Comment by mbj4668** [comment]
It is not quite clear if this is allowed ot not. The RFC text says:

    A range consists of an explicit value, or a lower-inclusive bound,
    two consecutive dots "..", and an upper-inclusive bound.  Multiple
    values or ranges can be given, separated by "|".  If multiple values
    or ranges are given, they all MUST be disjoint and MUST be in
    ascending order.

I suggest you use:  range "1";    This still leaves room for future growth.
