### ISSUE TITLE
LEAFREF_IDENTIFIER_NOT_FOUND when submodule leafref uses prefixed path to parent module

### ISSUE THREAD

**Issue by glennmatthews** [mbj4668/pyang#409]
Given the following YANG modules:

```yang
module main {
  namespace "http://test.test";
  prefix test;

  include submain;

  revision 2018-06-27;

  container native {
    container ip {
      container vrf {
        leaf name {
          type string;
        }
      }
    }

    uses config-interface-grouping;
  }
}
```

```yang
submodule submain {
  belongs-to main {
    prefix test;
  }

  revision 2018-06-27;

  grouping config-interface-grouping {
    choice vrf-choice {
      container ip-vrf {
        container ip {
          container vrf {
            leaf forwarding-prefixed {
              type leafref {
                path "/test:native/test:ip/test:vrf/test:name";
              }
            }
            leaf forwarding-unprefixed {
              type leafref {
                path "/native/ip/vrf/name";
              }
            }
          }
        }
      }
    }
  }
}
```

The `forwarding-unprefixed` leafref is correctly resolved, but the `forwarding-prefixed` leafref reports a LEAFREF_IDENTIFIER_NOT_FOUND error:

> submain:native in the path for forwarding at .../main@2018-06-27.yang:18 (at .../submain@2018-06-27.yang:13) is not found

A possibly related factor is that the `find_identifier('test', 'native')` function is returning a reference to the 'submain' module Statement, rather than the 'main' module Statement as I might expect.

**Comment by mbj4668** [comment]
Note that in YANG 1, a submodule cannot "see" any definitions in the main module.  It can only see definitions in included submodules.  The common solution to this is to let the main module only contain include statements, and move all data definition statements to a submodule  called (in this case) "sub-common", and let "sub-main" include "sub-common".

This has been changed in YANG 1.1, but pyang does not yet handle this case.
