### ISSUE TITLE
Cannot find pyang executable after installing pyang

### ISSUE THREAD

**Issue by gerardo-garcia** [mbj4668/pyang#412]
I have installed pyang in a clean Ubuntu VM, but I cannot find pyang executable:

To reproduce:
 ```
sudo apt-get install python-pip
sudo -H pip install pip==9.0.3
sudo -H pip install pyang
whereis pyang
```

**Comment by gerardo-garcia** [comment]
My fault. I deleted the executable manually. Uninstalling and installing pip package again fixed it.

**Comment by LinguiMa** [comment]
> I have installed pyang in a clean Ubuntu VM, but I cannot find pyang executable:
> 
> To reproduce:
> 
> ```
> sudo apt-get install python-pip
> sudo -H pip install pip==9.0.3
> sudo -H pip install pyang
> whereis pyang
> ```

this is a good method, I have resolved my question.

**Comment by gerardo-garcia** [comment]
Today, based on my experience, the precise method to install pyang would be:

```
sudo apt-get install python3 python3-pip
sudo -H python3 -m pip install -U pip
# Then, to install pyang for all users
sudo -H python3 -m pip install pyang
# Instead, you can install pyang in a single user
python3 -m pip install pyang
whereis pyang
```
