### ISSUE TITLE
pyang --check-update-from with deviate/augment

### ISSUE THREAD

**Issue by yuekyang** [mbj4668/pyang#415]
There are two versions of cisco-xe-openconfig-interfaces-deviation.yang which deviate openconfig-interfaces.yang in a backwards compatible way:

old model (BLD_V169_THROTTLE_LATEST_20180712_092155/cisco-xe-openconfig-interfaces-deviation.yang):
  deviation "/oc-if:interfaces/oc-if:interface/oc-if:hold-time" +
            "/oc-if:config/oc-if:up" {
      deviate delete {
        default 0;
      }
      description
        "Hold-time 0 is not configurable on XE, use no dampening.";
  }

new model (BLD_POLARIS_DEV_LATEST_20180706_002134/cisco-xe-openconfig-interfaces-deviation.yang):
  deviation "/oc-if:interfaces/oc-if:interface/oc-if:hold-time" +
            "/oc-if:config/oc-if:up" {
      deviate delete {
        default 0;
      }
      description
        "Hold-time 0 is not configurable on XE, use no dampening.";
  }

pyang command:
pyang -p BLD_POLARIS_DEV_LATEST_20180706_002134 --check-update-from BLD_V169_THROTTLE_LATEST_20180712_092155/openconfig-interfaces.yang --check-update-from-path BLD_V169_THROTTLE_LATEST_20180712_092155 BLD_POLARIS_DEV_LATEST_20180706_002134/openconfig-interfaces.yang BLD_POLARIS_DEV_LATEST_20180706_002134/cisco-xe-openconfig-interfaces-deviation.yang

pyang output complains "error: the default '0', defined at ... is illegally removed", which is a false alarm. The fact is default statements of “oc-if:interfaces/oc-if:interface/oc-if:hold-time/oc-if:config/oc-if:up” are deleted in both old and new model by cisco-xe-openconfig-interfaces-deviation.yang. pyang picks up deviation of new model but not deviation of old model, so it thinks new model removes it illegally. We need a way to let --check-update-from consider deviate/augment.

**Comment by einarnn** [comment]
Jonathan,

Would adding an extra option to check-update-from work for you? Maybe like this:

```
pyang -p BLD_POLARIS_DEV_LATEST_20180706_002134 \
    --check-update-from BLD_V169_THROTTLE_LATEST_20180712_092155/openconfig-interfaces.yang \
    --check-update-from-deviation BLD_V169_THROTTLE_LATEST_20180712_092155/cisco-xe-openconfig-interfaces-deviation.yang \
    --check-update-from-path BLD_V169_THROTTLE_LATEST_20180712_092155 \
    BLD_POLARIS_DEV_LATEST_20180706_002134/openconfig-interfaces.yang \
    BLD_POLARIS_DEV_LATEST_20180706_002134/cisco-xe-openconfig-interfaces-deviation.yang
```

I.e. add the `--check-update-from-deviation`, letting the two "deviated" versions of the basic model be compared?

Cheers,

Einar

**Comment by yuekyang** [comment]
Hi Einar,

Your new option --check-update-from-deviation needs to support a list of deviation or augment files. It’s common we have multiple files deviate/augment openconfig-interfaces.yang.

Therefore, to simplify the solution, I extend the existing option --check-update-from to support a list of deviation or augment files. This would be very similar to the existing usage of compiling a module file with augments. A list of files can be appended after openconfig-interfaces.yang:

pyang -p BLD_POLARIS_DEV_LATEST_20180706_002134 
      BLD_POLARIS_DEV_LATEST_20180706_002134/openconfig-interfaces.yang \
      BLD_POLARIS_DEV_LATEST_20180706_002134/cisco-xe-openconfig-interfaces-deviation.yang \
      …

I guess it’s intuitive to allow a list of files in --check-update-from. Please review my PR (https://github.com/mbj4668/pyang/pull/417).

Cheers,
Jonathan

**Comment by einarnn** [comment]
Just posted a comment there. I still think specific arguments work better to ensure that people know EXACTLY what they're getting.

Cheers,

Einar

**Comment by mbj4668** [comment]
PR #417 now merged.  Thanks!
