### ISSUE TITLE
How to convert Yang TO XML using Pyang

### ISSUE THREAD

**Issue by ksp2** [mbj4668/pyang#429]
Hi,
 
For converting YANG to XML we need pyang . I installed pyang 1.7.5 version in my machine.But I am facing difficulty how toconvert using pyang. Can anyone help me regarding this.It's too critical for me.

Thanks and Regards,

Sai Pavan.

**Comment by mbj4668** [comment]
If this is still a problem, please include more information (what command did you try, what failed etc) and I'll re-open the issue.
