### ISSUE TITLE
Issue when must statement has arithmetic operations {Confd Yang}!

### ISSUE THREAD

**Issue by bkannadassan** [mbj4668/pyang#430]
Hi All!
   
    We have following must statement, which throws error when doing yang2dsdl

        must "e-band != 'and-2' or " +
           "(e-band = 'and-2' and " +
           "earfcn >= (600 + ((../map/freq-map[name = current()/eb]/value)*5)) and " +
           "earfcn <= (1200 - ((../map/freq-map[name = current()/eb]/value)*5)))" {

But when the same is modified to below compiles fine 

        must "e-band != 'and-2' or " +
           "(e-band = 'and-2' and " +
           "earfcn >= (((../map/freq-map[name = current()/eb]/value))) and " +
           "earfcn <= (((../map/freq-map[name = current()/eb]/value))))" {

So what I could conclude is its not happy about dynamic calculations done with node values. Please let us know if this is on purpose ?. If so anyother way to overcome the same ?. Above is a yang model used with confd.

rgds
Balaji Kamal Kannadassan

**Comment by mbj4668** [comment]
I cannot reproduce this.  If it is still an issue, please attach all relevant files and instructions for how to reproduce.
