### ISSUE TITLE
XML instance validation errors using yang2dsdl

### ISSUE THREAD

**Issue by nsridevius** [mbj4668/pyang#432]
hi,
I used yang2dsdl to generate relax-ng/schematron from the yang files. now when i go to validate the XML instance document, i get the following errors

1. deref function in the confd yang is not recognized
2. Arithematic operations  like + , - , * in the must statement are having issues
Any suggestions on alternate usage to deref etc.
Trying to use the oXygen XML Editor to validate the XML instance using the generated relaxng/schematron schemas

yang2dsdl -s -j -b unicloud-config -t config -v config.xml 
== Using pre-generated schemas

== Validating grammar and datatypes ...
[warning] /usr/bin/jing: Unable to locate avalon-framework in /usr/share/java
[warning] /usr/bin/jing: Unable to locate batik-all in /usr/share/java
config.xml validates.

== Adding default values... done.

== Validating semantic constraints ...
xmlXPathCompOpEval: function deref not found
XPath error : Unregistered function
XPath error : Stack usage error
xmlXPathCompiledEval: 1 objects left on the stack.
--- Failed assert at "/nc:config/unicloud:profiles/unicloud:lte/unicloud:frequency":
    invalid earfcn value for Band-3 band, must be 1200 + (eutra-bandwidth * 5) .. 1950 - (eutra-bandwidth * 5)
--- Failed assert at "/nc:config/unicloud:profiles/unicloud:lte/unicloud:frequency":
    invalid earfcn value for Band-5 band, must be 2400 + (eutra-bandwidth * 5) .. 2650 - (eutra-bandwidth * 5)
--- Failed assert at "/nc:config/unicloud:profiles/unicloud:wifi/unicloud:radio/unicloud:operating-band":
    Not valid for the hardware.
--- Failed assert at "/nc:config/unicloud:profiles/unicloud:wifi/unicloud:radio/unicloud:operating-band":
    Not allowed in the Jurisdiction.

thx
Sri

**Comment by llhotka** [comment]
The `yang2dsdl` plugin doesn't support YANG 1.1. One of the reasons is that Schematron validation uses off-the-shelf XML tools (`xsltproc`) that don't understand YANG-specific functions such as `deref`.
