### ISSUE TITLE
About syntax.py

### ISSUE THREAD

**Issue by wangke1970** [mbj4668/pyang#441]
in syntax.py 
14  comment = '(/\*([^*]|[\r\n\s]|(\*+([^*/]|[\r\n\s])))*\*+/)|(//.*)|(/\*.*)'
why not 
 comment = r'(/\*([^*]|[\r\n\s]|(\*+([^*/]|[\r\n\s])))*\*+/)|(//.*)|(/\*.*)'

**Comment by fredgan** [comment]
Maybe they are both OK?

**Comment by fredgan** [comment]
It is already modified in de7dd5feef0f81cce102b075e2df17c284600bcb as you want. @wangke1970 
If you wish , you can close this issue.
