### ISSUE TITLE
AttributeError: 'YANGPlugin' object has no attribute 'add_transform'

### ISSUE THREAD

**Issue by kwatsen** [mbj4668/pyang#449]
I pulled the latest and saw this error:

```
Traceback (most recent call last):
  File "/Users/kwatsen/Juniper/version-control-servers/github/mbj4668/pyang/bin/pyang", line 488, in <module>
    run()
  File "/Users/kwatsen/Juniper/version-control-servers/github/mbj4668/pyang/bin/pyang", line 38, in run
    p.add_transform(xforms)
AttributeError: 'YANGPlugin' object has no attribute 'add_transform'
```

Reseting to the Dec 10 commit clears it.
```
  git reset --hard 45c4111a9c0763f2bc2821eaf4c0cf08d14f4ecb
```

I did not look to see which of the intervening commits is the culprit.

**Comment by wlupton** [comment]
I guess I must be the culprit here... at least I contributed the transform code (via PR #435). But I don't see why this error would occur. The PyangPlugin base class defines an add_transform() method and the YANGPlugin class should be inheriting from it and picking up the (empty) base class method implementation.

Could you possibly double-check your copy of pyang/plugin.py? I believe that add_transform() should be as shown [here](https://github.com/mbj4668/pyang/blob/34d3545907efb32fb9c7e3253284f41ff862bd8e/pyang/plugin.py#L96).

**Comment by kwatsen** [comment]
@william, plugin.py has that method defined.

@martin, it's a fresh `git clone`

```
# rm -rf pyang

# git clone https://github.com/mbj4668/pyang.git
Cloning into 'pyang'...
remote: Enumerating objects: 273, done.
remote: Counting objects: 100% (273/273), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 9329 (delta 156), reused 228 (delta 130), pack-reused 9056
Receiving objects: 100% (9329/9329), 7.76 MiB | 2.64 MiB/s, done.
Resolving deltas: 100% (6568/6568), done.

# cd pyang

# . env.sh 
# cd ../../netconf-wg/zero-touch/refs/
# ./validate-all.sh 

Testing YANG modules first...

validating ietf-sztp-bootstrap-server.yang...
  ^ with pyang...failed (error code: 0)
Traceback (most recent call last):
  File "/Users/kwatsen/Juniper/version-control-servers/github/mbj4668/pyang/bin/pyang", line 488, in <module>
    run()
  File "/Users/kwatsen/Juniper/version-control-servers/github/mbj4668/pyang/bin/pyang", line 38, in run
    p.add_transform(xforms)
AttributeError: 'YANGPlugin' object has no attribute 'add_transform'
```

But resetting works:

```
# cd -
/Users/kwatsen/Juniper/version-control-servers/github/mbj4668/pyang

# git reset --hard 45c4111a9c0763f2bc2821eaf4c0cf08d14f4ecb
HEAD is now at 45c4111 check grammar after expansion of uses

# cd -
/Users/kwatsen/Juniper/version-control-servers/github/netconf-wg/zero-touch/refs

# ./validate-all.sh 

Testing YANG modules first...

validating ietf-sztp-bootstrap-server.yang...
  ^ with pyang...okay.
  ^ with yanglint...okay.

<snip/>
```


I once upon a time accidentally did a `python setup.py install`, but I thought I cleaned it up.  Could there be a remnant somewhere still?

**Comment by kwatsen** [comment]
FWIW, I'm on a Mac, running OS X 10.12.6 with Python 2.7.

**Comment by wlupton** [comment]
Maybe, having done the clone and `. env.sh`, you could go to `test/test_yang` and see whether `make` works there? It should be executing this command:
```
pyang -Wnone a.yang --keep-comments -f yang --yang-canonical -o out/a.yang
```
And this variant should show where it's getting `plugin.pyc` from (I'm sure there's a better way):
```
python -v ../../bin/pyang -Wnone a.yang --keep-comments -f yang --yang-canonical -o out/a.yang 2>&1 | grep plugin.py
# /Users/william/Documents/BBF/Standards/pyang/pyang/plugin.pyc matches /Users/william/Documents/BBF/Standards/pyang/pyang/plugin.py
import pyang.plugin # precompiled from /Users/william/Documents/BBF/Standards/pyang/pyang/plugin.pyc
```
If it works here but not in your environment, maybe you could do something similar there?

(`env.sh` puts the pyang directory at the head of `PYTHONPATH` so I would think a past `python setup.py install` shouldn't matter, but I'm not sure exactly how `.pyc` files are searched for)

**Comment by mbj4668** [comment]
Hi,

Yes, please remove that directory!

**Comment by kwatsen** [comment]
Yep, that was it.  
Thanks for your help.  
Closing the issue.
