### ISSUE TITLE
error: package directory 'pyang' does not exist

### ISSUE THREAD

**Issue by shuailily0108** [mbj4668/pyang#451]
running install
running bdist_egg
running egg_info
writing pyang.egg-info\PKG-INFO
writing dependency_links to pyang.egg-info\dependency_links.txt
writing top-level names to pyang.egg-info\top_level.txt
**error: package directory 'pyang' does not exist**

**Comment by fredgan** [comment]
@shuailily0108 
Sorry for long time. We don't know how you got this issue. It's been a long time.  So, I close this now.

If you still encounter this issue, please let us know.
