### ISSUE TITLE
XPath syntax error: Literal 

### ISSUE THREAD

**Issue by markhaajii** [mbj4668/pyang#462]
Hello Dears,

i try to parse Huawei yang models by pyang. I tested another Netconf client and it parsed and passed with warnings instead of errors. But pyang display those errors:

data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-arp@2018-06-11.yang:553: error: XPath syntax error: Literal true from path is not of type enumeration
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-bfd-deviations-ATN-980B@2018-06-11.yang:421: error: XPath syntax error: Literal VXLAN from path is not of type enumeration
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-bfd-deviations-ATN-980B@2018-06-11.yang:426: error: XPath syntax error: Literal VXLAN from path is not of type enumeration
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-bfd-deviations-ATN-980B@2018-06-11.yang:431: error: XPath syntax error: Literal VXLAN from path is not of type enumeration
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-bgp-bgpcomm@2018-06-11.yang:319: error: XPath syntax error: Literal _public_ from path is not of type leafref
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-bgp-bgpcomm@2018-06-11.yang:326: error: XPath syntax error: Literal _public_ from path is not of type leafref

How could i upload those models

Thanks.

**Comment by mbj4668** [comment]
which version of pyang are you using?

**Comment by markhaajii** [comment]
[root@localhost admin]# pyang -v
pyang 1.7.5

**Comment by mbj4668** [comment]
I think you are using an old github checkout.  Please do a git pull.

But note that the models may still be broken - we have just removed the xpath checking code.

**Comment by mbj4668** [comment]
it would be interesting to see the broken model,  e.g.  can you show the line 553 of huawei-arp@2018-06-11.yang?

**Comment by markhaajii** [comment]
Dear mbj4668
I upgraded pyang to 1.7.8 and previous errors are fixed. but some errors are displayed. My netconf client is YangExplorer. Could you mind know those errors:

data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-mcfwd@2018-06-11.yang:699: error: huawei-devm:lpuBoards in the path for setEgressMcFwdMode at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-mcfwd@2018-06-11.yang:697 is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:744: error: huawei-devm:lpuBoards in the path for sourceSlot at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:742 is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:757: error: huawei-devm:lpuBoards in the path for destSlot at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:754 is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:824: error: huawei-devm:lpuBoards in the path for samperSlot at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:822 is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:870: error: huawei-devm:lpuBoards in the path for samperSlot at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-nsm@2018-06-11.yang:868 is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:338: error: huawei-nqa:nqaIcmps in the path for trackNqaAdminName at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt@2018-06-11.yang:50 (at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:335) is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:347: error: huawei-nqa:nqaIcmps in the path for trackNqaTestName at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt@2018-06-11.yang:50 (at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:344) is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:608: error: huawei-nqa:nqaIcmps in the path for trackNqaAdminName at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt@2018-06-11.yang:50 (at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:606) is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:616: error: huawei-nqa:nqaIcmps in the path for trackNqaTestName at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt@2018-06-11.yang:50 (at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/huawei-staticrt-staticrtbase@2018-06-11.yang:614) is not found
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/ietf-ip@2014-06-16.yang:132: error: there is already a child node to "/if:interfaces/if:interface" at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/ietf-ip@2014-06-16.yang:127 with the name "ipv4" defined at /home/admin/yang-explorer/v/share/yang/modules/ietf/ietf-ip.yang:155
data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/ietf-ip@2014-06-16.yang:380: error: there is already a child node to "/if:interfaces-state/if:interface" at data/session/nr8xm6al6etlfukn59tqb45z4rxkcl5s/ietf-ip@2014-06-16.yang:377 with the name "ipv4" defined at /home/admin/yang-explorer/v/share/yang/modules/ietf/ietf-ip.yang:565

**Comment by mbj4668** [comment]
you need to check the modules and error messages.  after checking this, if you think there is a bug in pyang, please put together an example that shows how to reproduce the bug, and I'll have a look.

**Comment by markhaajii** [comment]
thanks mbj4668
The main issue is fixed by the upgrade and I modified remaining models which are occurred error to fix.
