### ISSUE TITLE
pre_validate_ctx not called at correct time

### ISSUE THREAD

**Issue by immibis** [mbj4668/pyang#465]
The docstring for the `pre_validate_ctx` hook in `PyangPlugin` says:

    def pre_validate_ctx(self, ctx, modules):
        """Called for all plugins, before the modules are validated"""
        return

And indeed if you look at the [main script](https://github.com/mbj4668/pyang/blob/master/bin/pyang#L365) it looks like this hook is called before `ctx.validate()` is called.

However, this is not actually where the modules are validated. They are validated [as they are loaded](https://github.com/mbj4668/pyang/blob/master/pyang/__init__.py#L135) in `add_parsed_module`. All that [`ctx.validate`](https://github.com/mbj4668/pyang/blob/master/pyang/__init__.py#L331) does is check for duplicate namespaces.

This impacts the tailf plugin, which tries to do some pre-processing in pre_validate_ctx. (I could be wrong about this - maybe it really is supposed to be after validating modules)

**Comment by mbj4668** [comment]
It seems the code has always been like this.  Odd.  Do you have an example when the tailf plugin fails due to this?
