### ISSUE TITLE
new boilerplate validation too literal

### ISSUE THREAD

**Issue by kwatsen** [mbj4668/pyang#478]
Happy to see this addition, but it's flagging my modules unnecessarily because the line-returns are in different locations.

I believe the versions I have are better looking, but it would be best if the check could insensitive to where endings are located.

BTW, the "XXXX" assumes that the particular draft is using "XXXX" to represent the assign number for the current draft.  It's a safe guess, but not guaranteed.  Will the validator throw an error if the author chose a different placeholder value?   

FWIW, that last comment is a problem for me now as my folding script uses "XXXX" (for the artwork-folding draft) *and* the draft itself uses "XXXX" (to represent itself).  Since I've already moved to using "AAAA", "BBBB", "CCCC", etc. for imports, I was thinking about maybe doing the same for the main draft.  I probably won't, but I don't want the reason to be because a tool forced me.

**pyang**:
```
     The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL', 'SHALL
     NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED', 'NOT RECOMMENDED',
     'MAY', and 'OPTIONAL' in this document are to be interpreted as
     described in BCP 14 (RFC 2119) (RFC 8174) when, and only when,
     they appear in all capitals, as shown here.
```
**mine**:
```
     The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL',
     'SHALL NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED',
     'NOT RECOMMENDED', 'MAY', and 'OPTIONAL' in this document
     are to be interpreted as described in BCP 14 (RFC2119)
     (RFC8174) when, and only when, they appear in all
     capitals, as shown here.
```

**pyang**:
```
     Copyright (c) <year> IETF Trust and the persons identified as
     authors of the code.  All rights reserved.

     Redistribution and use in source and binary forms, with or
     without modification, is permitted pursuant to, and subject to
     the license terms contained in, the Simplified BSD License set
     forth in Section 4.c of the IETF Trust's Legal Provisions
     Relating to IETF Documents
     (https://trustee.ietf.org/license-info).

     This version of this YANG module is part of RFC XXXX
     (https://www.rfc-editor.org/info/rfcXXXX); see the RFC itself
     for full legal notices.
```
**mine**:
```
     Copyright (c) 2019 IETF Trust and the persons identified
     as authors of the code. All rights reserved.

     Redistribution and use in source and binary forms, with
     or without modification, is permitted pursuant to, and
     subject to the license terms contained in, the Simplified
     BSD License set forth in Section 4.c of the IETF Trust's
     Legal Provisions Relating to IETF Documents
     (https://trustee.ietf.org/license-info).
  
     This version of this YANG module is part of RFC XXXX
     (https://www.rfc-editor.org/info/rfcXXXX); see the RFC
     itself for full legal notices.
```

**Comment by kwatsen** [comment]
Actually, pyang's 2119 boilerplate is growing on me.  Even though it's not as tight, it's roughly the same width as my copyright text, which makes to two stacked on top of each other nicer looking (see below).

Still, I think the tool should be insensitive to where line endings occur.

But, so long as the tool is going to output a sample, perhaps it could be this combo?
```
     Copyright (c) 2019 IETF Trust and the persons identified
     as authors of the code. All rights reserved.

     Redistribution and use in source and binary forms, with
     or without modification, is permitted pursuant to, and
     subject to the license terms contained in, the Simplified
     BSD License set forth in Section 4.c of the IETF Trust's
     Legal Provisions Relating to IETF Documents
     (https://trustee.ietf.org/license-info).

     This version of this YANG module is part of RFC XXXX
     (https://www.rfc-editor.org/info/rfcXXXX); see the RFC
     itself for full legal notices.; 
    
     The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL',
     'SHALL NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED',
     'NOT RECOMMENDED', 'MAY', and 'OPTIONAL' in this document
     are to be interpreted as described in BCP 14 (RFC2119)
     (RFC8174) when, and only when, they appear in all
     capitals, as shown here.
```

**Comment by mbj4668** [comment]
It actually already didn't care about whitespaces.  But there was one bug in the 8174 regexp and one in the TLP regexp, both fixed.

(The format that pyang prints in --ietf-help uses the line breaks that the RFC editor have used in recent modules)

**Comment by kwatsen** [comment]
The copyright warning is gone, but I'm still getting a warning for the 2119 language.

Comparing, I can't see the diff, except maybe because mine is at the and of a YANG `description` statement and hence ends with an extra `";` ?

Here's what mine looks like:
```
  description
    "...

     The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL',
     'SHALL NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED',
     'NOT RECOMMENDED', 'MAY', and 'OPTIONAL' in this document
     are to be interpreted as described in BCP 14 (RFC2119)
     (RFC8174) when, and only when, they appear in all
     capitals, as shown here.";
```

**Comment by kwatsen** [comment]
never mind, missing space in mine: `RFCXXXX` --> `RFC XXXX`

**Comment by mbj4668** [comment]
> So long as the tool is going to output a sample, perhaps it could be this combo?
> 
> ```
>      Copyright (c) 2019 IETF Trust and the persons identified
>      as authors of the code. All rights reserved.
> 
>      Redistribution and use in source and binary forms, with
>      or without modification, is permitted pursuant to, and
>      subject to the license terms contained in, the Simplified
>      BSD License set forth in Section 4.c of the IETF Trust's
>      Legal Provisions Relating to IETF Documents
>      (https://trustee.ietf.org/license-info).
> 
>      This version of this YANG module is part of RFC XXXX
>      (https://www.rfc-editor.org/info/rfcXXXX); see the RFC
>      itself for full legal notices.; 
>     
>      The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL',
>      'SHALL NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED',
>      'NOT RECOMMENDED', 'MAY', and 'OPTIONAL' in this document
>      are to be interpreted as described in BCP 14 (RFC2119)
>      (RFC8174) when, and only when, they appear in all
>      capitals, as shown here.
> ```

The TLP boilerplate is always required, but the BCP14 boilerplate is only required if 2119 languange is used somewhere in the module's description statements.

**Comment by kwatsen** [comment]
i know, and pyang does a good job saying that.  i only put the two blocks together statically like that to show what the net appearance looks like.  

I don’t think think this is a tooling issue (since it’s inside artwork) and it’s not a legal issue (since the data is there), and already pyang allows for the line breaks to be in other locations...

If you agree that the net result is more pleasing, then it would be best for the samples to output it, since many will copy from there.
