### ISSUE TITLE
how to mention datastore contents (configuration and state data) to verify xpath in a notification

### ISSUE THREAD

**Issue by babukt** [mbj4668/pyang#479]
I don't see any option in help to mention about data contents to validate the xpath of an instance identifier in notification data.

root@Attella-ODL-Server:/home/attella/orm_2_2_1# yang2dsdl -s -b sample -t notification -v chg_dsdl.xml
== Using pre-generated schemas

== Validating grammar and datatypes ...
chg_dsdl.xml validates

== Adding default values... done.

== Validating semantic constraints ...
XPath error : Undefined namespace prefix
xmlXPathEval: evaluation failed
dyn:evaluate() : unable to evaluate expression '/en:notification/org-openroadm-device:org-openroadm-device/org-openroadm-device:users/babu:user[org-openroadm-device:name='test']'
--- Failed assert at "/en:notification/org-openroadm-device:change-notification/org-openroadm-device:edit/org-openroadm-device:target":
    The instance "/en:notification/org-openroadm-device:org-openroadm-device/org-openroadm-device:users/babu:user[org-openroadm-device:name='test']" must exist.
--- Failed assert at "/en:notification/org-openroadm-device:change-notification/org-openroadm-device:edit/org-openroadm-device:target":
    The instance "/en:notification/org-openroadm-device:org-openroadm-device/org-openroadm-device:users/org-openroadm-device:user[org-openroadm-device:name='test']/org-openroadm-device:group" must exist.
root@Attella-ODL-Server:/home/attella/orm_2_2_1#
root@Attella-ODL-Server:/home/attella/orm_2_2_1#

**Comment by llhotka** [comment]
*yang2dsdl* cannot support references to datastores from RPCs or notifications. The only instance data available is the XML document `chg_dsdl.xml`.
