### ISSUE TITLE
Convert YANG to XML

### ISSUE THREAD

**Issue by Skebard** [mbj4668/pyang#480]
Hello,
 
I i'm working with netopeer2 to configure a switch but i'm having problems trying to convert my yang model to xml. The main problem is that i don't know how to express a container that is inside another container. 
Thank you in advance.

module NewSwitch {
	yang-version 1;
	namespace "urn:NewSwitch:test";

	prefix bld;
	}

	container ietf-interfaces-interfaces {
		list interface {
			key name;
			leaf type{
				type uint32;															//ethernetCsmacd
			}
			leaf enabled{
				type boolean;																//default value = true
			}
			leaf name{																		//Port-number
				type uint32;
			}

			container ieee802-dot1q-bridge-bridge-port{
				container ieee802-dot1q-sched-gate-parameters{
					container admin-cycle-time{
						leaf denominator{												//500/hypercycle
							type uint32;
						}
						leaf numerator{
							type uint32;													//500

						}
					}
					leaf config-change{
						type boolean;
					}
					list admin-control-list{
						key index;
						container sgs-params{
							leaf time-interval-value{
								type uint32;
							}
							leaf gate-states-value{
								type uint32;
							}

						}
						leaf index{
							type uint16;
						}

					}
					leaf admin-control-list-length{
						type uint32;
					}
					container admin-base-time{
						leaf seconds{													//default value = 0
							type uint32;
						}
						leaf fractional-seconds{							//defauilt value = 0
							type uint32;
						}

					}

				}

			}

		}
	}
 }

**Comment by mbj4668** [comment]
If you are working with netopeer2, perhaps you should send your question to them.  This repo is for pyang.
