### ISSUE TITLE
The check_update plugin API is not suitable for apps

### ISSUE THREAD

**Issue by ygorelik** [mbj4668/pyang#483]
The check_update plugin API is not suitable for apps where the existing functionality can be used on multiple modules without reloading the context. (Current implementation allows only single module compatibility check).
The main issues:
- [ ] The model context created each time the plugin function 'check_update' is invoked. Need to split the 'check_update' function to separate module comparison (ex.: 'chk_module') after context is created and checked. That would create an API for multiple use of the context to check compatibility for multiple modules.
- [ ] When parsing single module the algorithm removes all 'i_children' from statement, which makes it impossible for the context to be used multiple times.

**Comment by mbj4668** [comment]
PR #484 merged.
