### ISSUE TITLE
pyang does not validate Xpath expression

### ISSUE THREAD

**Issue by rampolisetty** [mbj4668/pyang#486]
I have a must statement like this:

must "current( = 'xpdr'" {
    error-message "The only node-type supported is xpdr";
}

Looks like Pyang does not report any error and my yang gets converted to Yin without issues.

   <must condition="current( = 'xpdr'">
        <error-message>
          <value>The only node-type supported is xpdr</value>
        </error-message>
      </must>

Please clarify if this is expected?

**Comment by mbj4668** [comment]
If this is part of an unsued grouping, it isn't validated, but I view that as a bug which will be fixed.
