### ISSUE TITLE
Ambiguous error message for added/deleted presence node

### ISSUE THREAD

**Issue by ygorelik** [mbj4668/pyang#487]
#### Symptoms
When checking backward compatibility of a module, which has added/deleted presence node, the error message is ambiguous - having quotes on presence statement. Instead it should quote only affected parent node.
#### How to reproduce
Compare IOS XR 652 module Cisco-IOS-XR-ip-tcp-cfg.yang to corresponding module in 633:
```
$ pyang --check-update-from ../633/Cisco-IOS-XR-ip-tcp-cfg.yang -P ../633 Cisco-IOS-XR-ip-tcp-cfg.yang
Cisco-IOS-XR-ip-tcp-cfg.yang:85: error: the base type has illegally changed from int32 to uint32
Cisco-IOS-XR-ip-tcp-cfg.yang:160: error: the presence 'Indicates a ip-tcp node is configured.' is illegally added
Cisco-IOS-XR-ip-tcp-cfg.yang:342: error: the base type has illegally changed from int32 to uint32
Cisco-IOS-XR-ip-tcp-cfg.yang:367: error: a new must expression cannot be added
```
Note ambiguously quoted error message:
**the presence 'Indicates a ip-tcp node is configured.' is illegally added**
#### Expected behavior
It is expected to have the following message:
**the presence 'ip-tcp' is illegally added**

**Comment by mbj4668** [comment]
PR #484 merged.
