### ISSUE TITLE
pyang -f returns empty output file without error message

### ISSUE THREAD

**Issue by ss1350** [mbj4668/pyang#494]
Trying to convert the IEEE module ieee802-dot1q-tsn-types to a tree structure throws no error but generates an empty output file. Validation of Module does not throw errors.

\pyang -f tree .\ieee802-dot1q-tsn-types.yang -p .\.. -o ieee802-dot1q-tsn-types.txt

Module Source:
[https://github.com/YangModels/yang/blob/master/standard/ieee/draft/802.1/ieee802-dot1q-tsn-types.yang](url)

**Comment by mbj4668** [comment]
This is b/c the module doesn't define any data nodes, and -f tree prints the data node tree by default.

You can pass --tree-print-groupings to print the groupings in this module.

**Comment by ss1350** [comment]
Works now. Thank you.
