### ISSUE TITLE
How to create a customized pyang plugin and excute it ?

### ISSUE THREAD

**Issue by buddha1987** [mbj4668/pyang#498]
I am working on a project which I want to use pyang to modify the yang file. 
E.g.: modify the module prefix following some rules.
Now I have two questions :
1. In this case, shoud I create customized plugin then execute it ?
If the answer for question 1 is yes, then I will take the python file in plugins directory as example and write my own.
2. How to execute a customized plugin ?

If this question is not fit for here, please let me know and I can delete it. 

Thanks in advance.

**Comment by wlupton** [comment]
It sounds like you want a transform (a type of plugin that gets to process the statement tree after all the YANG files have been parsed but before the output format is generated).

There aren't yet any standard (i.e. bundled) pyang transforms but you could take a look at the tests in the `test/test_transform` directory.

There is an open PR #437 that proposes an "edit" transform (it can modify the module prefix). There are currently some problems preventing merging this PR (also, it might end up as an example rather than a standard transform) but you could take a look at it.

**Comment by buddha1987** [comment]
@wlupton  Thanks very much. I will take a look.

**Comment by buddha1987** [comment]
when I try to run a customized plugins, the cmd is 
`pyang --plugindir /opt/confd/lib/pyang/pyang/plugins -t DependPlugin /opt/confd/yang/abc.yang`

I got the error like `optparse.OptionConflictError: option --uml-classes-only: conflicting option string(s): --uml-classes-only`

Why it complains a conflict option `--uml-classes-only` which I didn't use?

**Comment by buddha1987** [comment]
@wlupton  Take this plugin `edit` as the example, what the cmd will looks like if I want to run this plugin ?
Thanks.

**Comment by wlupton** [comment]
If you check out the `feature/add-demo-edit-transform` branch, you will find the transform code in `./pyang/transforms/edit.py`. Take a copy of this file.

Use whatever pyang version you usually use, e.g. the latest from GitHub. Obviously you need a version that's new enough to have transform support (it's been there for a while).

Now go to the directory that contains the YANG to be processed and copy `edit.py` into this directory. `pyang --plugindir . --help` should list the plugin and its arguments.

Here's a simple command that doesn't change anything:
```
% pyang --plugindir . --transform edit --format yang ietf-interfaces.yang | grep -A1 organization
  organization
    "IETF NETMOD (Network Modeling) Working Group";
```

And here's a command that edits the `organization`:
```
% pyang --plugindir . --transform edit --edit-organization="example.org" --format yang ietf-interfaces.yang | grep -A1 organization
  organization
    "example.org";
```

The `--edit-organization` etc. arguments support some simple operations such as replacing strings, reading values from files and so on (see the code for details).

**Comment by buddha1987** [comment]
I try and it works!
Thank you very much @wlupton

**Comment by fredgan** [comment]
@buddha1987 Since you have solved this, please close the issue.
