### ISSUE TITLE
yang2dsdl does not search virtualenv path for xslt

### ISSUE THREAD

**Issue by choppsv1** [mbj4668/pyang#499]
yang2dsdl does not search in python virtual environment for xslt files 

```
(default) [05:43:51 dak:~]$ ls -l ~/Envs/default/share/yang/xslt/
total 220
-rw-r--r-- 1 chopps users   544 Jun 11 23:52 basename.xsl
-rw-r--r-- 1 chopps users  3426 Jun 11 23:52 dsrl2xslt.xsl
...
(default) [05:43:59 dak:~]$ which yang2dsdl
/home/chopps/Envs/default/bin/yang2dsdl
(default) [05:34:20 dak:~/w/lisp-yang]$ yang2dsdl -x -t config -d .validate -v test-xml-example.xml ietf-lisp.yang
warning: failed to load external entity "/usr/local/share/yang/xslt/basename.xsl"
cannot parse /usr/local/share/yang/xslt/basename.xsl
...
```

**Comment by llhotka** [comment]
yang2dsdl is a shell script that uses **xsltproc** for XSLT processing, which knows nothing about Python virtualenv. The solution is to set the environment variable `PYANG_XSLT_DIR` to the directory within the virtualenv in which the pyang XSLT stylesheets reside.

**Comment by choppsv1** [comment]
I don't care what yang2dsdl is written in or does to implement it's functionality, I run it it doesn't find it's own files, I say that's broken. :)

If I was going to fix this I'd have yang2dsdl set/add-to PYANG_XSLT_DIR to include the directory that pyang has installed the xslt in.

**Comment by choppsv1** [comment]
Since no reply I'll open a new issue. :)

**Comment by Santhoshexp** [comment]
> yang2dsdl is a shell script that uses **xsltproc** for XSLT processing, which knows nothing about Python virtualenv. The solution is to set the environment variable `PYANG_XSLT_DIR` to the directory within the virtualenv in which the pyang XSLT stylesheets reside.

Can you explain in detail

**Comment by llhotka** [comment]
For example, my `.bashrc` file contains the line
```
export PYANG_XSLT_DIR=$HOME/Projects/pyang/xslt
```

**Comment by Santhoshexp** [comment]
> For example, my `.bashrc` file contains the line
> 
> ```
> export PYANG_XSLT_DIR=$HOME/Projects/pyang/xslt
> ```

Yep this worked✌️

**Comment by maksim-estonia** [comment]
My solution:

```bash
gedit ~/.bashrc
```

And add following lines:

```bash
export PYANG_XSLT_DIR=$HOME/pyang/xslt
export PYANG_RNG_LIBDIR=$HOME/pyang/schema
```

**Comment by wlupton** [comment]
Note that [`env.sh`](https://github.com/mbj4668/pyang/blob/master/env.sh) includes these lines:
```
export PYANG_XSLT_DIR="$PWD/xslt"
export PYANG_RNG_LIBDIR="$PWD/schema"
```

**Comment by maksim-estonia** [comment]
Hi, 

Yes, but I think my issue was caused due to the following lines in [`yang2dsdl`](https://github.com/mbj4668/pyang/blob/master/bin/yang2dsdl):

```
xslt_dir=${PYANG_XSLT_DIR:-/usr/local/share/yang/xslt}
schema_dir=${PYANG_RNG_LIBDIR:-/usr/local/share/yang/schema}
```
