### ISSUE TITLE
What is the best way to generate a yang file ?

### ISSUE THREAD

**Issue by buddha1987** [mbj4668/pyang#504]
I am working on a customized pyang plugin.  The basic functionality of this plugin is it parses multiple yang files, and based these input yang files to generate a new yang file.
In my design, I make this plugin to registeer a new output format :
```
def add_output_format(self, fmts):
      self.multiple_modules = True
      fmts['feature-yang'] = self
```

Now I have finished the parsing logics in this plugin, I already put the needed data for the yang file which I need to generate, into the proper data structures. These data include, E.g.:
1. module name, namespace, prefix
2. all the modules need to be imported
3. all the groupings need to be defined
4. all the groupings need to be augmented

In this case,  is there any class/method in pyang, I can use in order to generate the target yang file ?

Thanks in advance.

**Comment by mbj4668** [comment]
You can use the plugin / translator "YANGPlugin" (which is used when you do -f yang).

**Comment by buddha1987** [comment]
@mbj4668  Thank you for the suggestion. But how to use the "YANGPlugin" in my own plugin ? Is there any example I can follow?
