### ISSUE TITLE
Modules not matched in schema node identifiers

### ISSUE THREAD

**Issue by nkitchen** [mbj4668/pyang#510]
For statements like `deviation` whose argument is a schema node identifier, when an identifier in the path has a prefix from its defining module but belongs to a grouping used by a different module, `find_target_node` fails to match the child for the prefixed identifier.

For an example, see the attached file deviation-test.yang. It contains a deviation to `.../oc-if:subinterface/oc-ip:ipv4/oc-if:unnumbered/...`. If I download the OpenConfig models using `git clone https://github.com/openconfig/public openconfig` and run `pyang -p openconfig deviation-test.yang -f yang -o deviation-test.yang`, I get the message:
```
deviation-test.yang:12: error: node openconfig-interfaces::unnumbered is not found
```

However, if I alter the path to be `.../oc-ip:ipv4/oc-ip:unnumbered/oc-ip:config/oc-ip:enabled` (replacing every prefix under oc-ip:ipv4 with "oc-ip"), pyang runs with no errors.

A statement that seems to be at the center of the problem is https://github.com/mbj4668/pyang/blob/086fc29d/pyang/statements.py#L1551. Every statement for a node in a grouping has i_module set to the module where it is used. That makes sense for the XML namespaces of nodes, but not for schema node identifiers.

A point of comparison: When I run [goyang](https://github.com/openconfig/goyang) on the same modules (`goyang --format=tree --path openconfig openconfig/release/models/interfaces/openconfig-interfaces.yang  openconfig/release/models/interfaces/openconfig-if-ip.yang`), it identifies the same node as "oc-if:unnumbered", not "oc-ip:".

[deviation-test.yang](https://github.com/mbj4668/pyang/files/3719770/deviation-test.yang.txt)

**Comment by mbj4668** [comment]
I cannot reproduce this with the instructions you gave.  When try this with the latest pyang (from master), I don't get any errors.  Did you try with the latest version?

**Comment by nkitchen** [comment]
Sorry, this was my mistake. I did use the latest version, but the test file that I uploaded did not have the correct contents. I forgot to change it back to the original prefixes after altering the path.

The file attached here is the correct one.

[deviation-test-fixed.yang.txt](https://github.com/mbj4668/pyang/files/3740659/deviation-test-fixed.yang.txt)

**Comment by mbj4668** [comment]
It seems that the error message is correct.  "unnumbered" belongs to "openconfig-if-ip".

**Comment by nkitchen** [comment]
After much discussion with colleagues, I am persuaded that I misunderstood RFC 6020 and that you are right.
