### ISSUE TITLE
Can't get yang model tree

### ISSUE THREAD

**Issue by anlaursa** [mbj4668/pyang#513]
I'm new to yang and any help would much appreciated.
I'm trying to get tree format out of a yang file and keep getting the below error.

(py3-venv) andre@devnet:~/yang_models$ pyang -f tree Cisco-IOS-XE-acl.yang
Cisco-IOS-XE-ac.yang:7: error: syntax error: illegal keyword: <!DOCTYPE html>

**Comment by mbj4668** [comment]
It seems there's a syntax error on line 7.  Talk to the author of the model.
