### ISSUE TITLE
New requirement: Validator to check  XML/JSON fragment conforms to a structure definition

### ISSUE THREAD

**Issue by BalazsLengyel** [mbj4668/pyang#517]
A validator to check that an  XML/JSON fragment conforms to a YANG Data Structure definition would be very much needed.
Yang data structures are defined following: draft-ietf-netmod-yang-data-ext

**Comment by fredgan** [comment]
As the description, 
> pyang is a YANG validator, transformator and code generator, written in python. It can be used to validate YANG modules for correctness, to transform YANG modules into other formats, and to generate code from the modules.


If you want to validate the data, you may use `yanglint` tool in [libyang](https://github.com/CESNET/libyang)

**Comment by llhotka** [comment]
@BalazsLengyel what do you mean by “structure definition”?

**Comment by BalazsLengyel** [comment]
I updated the original requirement.
Can yanglint XML/JSON based om check yang data structure s ?

**Comment by fredgan** [comment]
@BalazsLengyel Maybe you can try to read the README and yanglint help message, you can find if it fits your requirement or not.

**Comment by wlupton** [comment]
@BalazsLengyel I suggest taking a look at #426, which includes some discussion of using yanglint for validating XML instance documents. For example this:

_Here's an actual command that you might be able to adapt (I believe that you need to specify explicit paths for files specified on the command line, and that imported/included files will use the supplied search path):_
```
% /usr/local/bin/yanglint \
	--path=<IETF-YANG-LOCATION> --verbose --allimplemented  \
	--strict --type=config --merge --format=xml --default=all-tagged \
	--output=ietf-interfaces.xml.out \
	<IETF-YANG-LOCATION>/iana-if-type.yang \
	<OTHER-YANG-LOCATION>/ietf-bulk-data-export.yang \
	<OTHER-YANG-LOCATION>/ietf-ipfix.yang \
	<OTHER-YANG-LOCATION>/ietf-psamp.yang \
	ietf-interfaces.xml
```

**Comment by fredgan** [comment]
@BalazsLengyel I will close this issue. If you have any other question, please let us know.
