### ISSUE TITLE
[Question] Generating Schematron always results in exslt which has experimental support.

### ISSUE THREAD

**Issue by eduardnegru** [mbj4668/pyang#521]
Whenever I use yang2dsdl to geneate a .sch schema, the resulting file is of the following format:

`<?xml version="1.0" encoding="utf-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="`**exslt**`">`

As stated in iso_schematron_skeleton_for_xslt1.xsl, exslt has an experimental support. How can I make sure that xslt will be generated instead of exslt, so that the .sch will look like:
`<?xml version="1.0" encoding="utf-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="`**xslt**`">`

**Comment by llhotka** [comment]
No way. The XSL transformations, and Schematron validation in particular, rely heavily on EXSLT.
