### ISSUE TITLE
statements data_keywords vs data_definition_keywords

### ISSUE THREAD

**Issue by remingtonc** [mbj4668/pyang#523]
What is the difference between [`statements.data_keywords`](https://github.com/mbj4668/pyang/blob/4435dfec9396c9c1f3ef6b3c22e4f804a6051f92/pyang/statements.py#L288-L289) and [`statements.data_definition_keywords`](https://github.com/mbj4668/pyang/blob/4435dfec9396c9c1f3ef6b3c22e4f804a6051f92/pyang/statements.py#L120-L121)? `statements.data_keywords` seems broader - would everything being in `data_keywords` have an XPath?

For instance - here if we filter by keyword...
```python
statement_children = (
    child
    for child in statement.i_children
    if child.keyword in statements.data_definition_keywords
)
```

Should filtering happen on `data_keywords` or `data_definition_keywords`?

Blocks #519

**Comment by remingtonc** [comment]
The `tree` plugin [filters](https://github.com/mbj4668/pyang/blob/4435dfec9396c9c1f3ef6b3c22e4f804a6051f92/pyang/plugins/tree.py#L141-L142) on `statements.data_definition_keywords` as opposed to `data_keywords` - is this correct behavior?

**Comment by mbj4668** [comment]
data_definition_keywords are statements that add nodes to the data tree of a module (this term is defined in the RFC)

The data tree is the tree of config true / config false in the module.

But there are also other "trees" defined - rpcs, notifications, actions, sx:structure - these are broader and are defined with the data_keywords.

So in the flatten plugin it depends on what you want to do - do you want to include rpcs and notifs and their input/output parameters?  The tree plugin prints rpcs and notifs separately.

**Comment by remingtonc** [comment]
Ah, interesting! Thank you. Can these elements be easily addressed as an XPath? Any immediate gotchas? [`statements.mk_path_str`](https://github.com/mbj4668/pyang/blob/master/pyang/statements.py#L3151-L3183) is the current technique for deriving the XPath.

It might be easiest to limit to `data_definition_keywords` in the plugin at first, but I do consider the other trees equally as important in availability to output - if it's a simple matter with the same semantics in terms of addressing as an XPath then `data_keywords` would immediately be more ideal.

**Comment by mbj4668** [comment]
I think they can be printed as XPaths with mk_path_str.
