### ISSUE TITLE
HelloParser not handling deviations?

### ISSUE THREAD

**Issue by remingtonc** [mbj4668/pyang#530]
EDIT: Should deviations be advertised as their own capability?

I see `deviations` specified in hello messages for instance: https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/701/capabilities-ncs5k.xml#L7

These deviations do not seem to be sourced perusing [`hello.py`](https://github.com/mbj4668/pyang/blob/master/pyang/hello.py).

**Comment by remingtonc** [comment]
@mbj4668 A quick attempt at adding this https://github.com/cisco-ie/pyang/blob/hello-deviations/pyang/hello.py#L87-L89

In a capability, does the deviation require a revision specification as well?

I'm trying to decipher where it would be possible to add some kind of flag along the lines of "If revision is not specified, use the latest found". Do you have an initial pointer in where in the code it would be simplest to have that logic?

**Comment by mbj4668** [comment]
First, note that hello advertising is for YANG 1.0 modules.  With 1.1, modules are advertised in yang-library.
A deviation module is referenced by name in the "deviations=" part.  But the deviation module and its revision (if any) is also advertised as its own <capability> in 1.0.

**Comment by remingtonc** [comment]
@mbj4668 Good to know, I'll keep my eye out for `yang-library`. It appears that not every implementation adheres to advertising the deviation module itself. Per #556 is it reasonable to include some best-effort deviations parsing from capabilities/hello files?
