### ISSUE TITLE
Different "yin conversion" behavior for "if-feature" between pyang1.7.8 and pyang2.1

### ISSUE THREAD

**Issue by lukai-nokia** [mbj4668/pyang#531]
Unzip the attached file

[if-feature.zip](https://github.com/mbj4668/pyang/files/3981457/if-feature.zip)

Then run below command with pyang 1.7.8

> **pyang -f yin bak.yang -p . -F "smp:forwarding-databases,mac-learning"**

The result will be 

```
<?xml version="1.0" encoding="UTF-8"?>
<module name="bak"
        xmlns="urn:ietf:params:xml:ns:yang:yin:1"
        xmlns:bak="http://tail-f.com/ns/example/bak"
        xmlns:bbf-l2-fwd="http://tail-f.com/ns/example/smp">
  <yang-version value="1.1"/>
  <namespace uri="http://tail-f.com/ns/example/bak"/>
  <prefix value="bak"/>
  <import module="smp">
    <prefix value="bbf-l2-fwd"/>
  </import>
  <feature name="bak"/>
  <augment target-node="/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarding-databases/bbf-l2-fwd:forwarding-database/bbf-l2-fwd:static-mac-address/bbf-l2-fwd:learning-constraint/bbf-l2-fwd:allowed-to-learn-on/bbf-l2-fwd:allow-to-learn-on">
    <if-feature name="bbf-l2-fwd:forwarding-databases and bbf-l2-fwd:mac-learning"/>
  </augment>
</module>

```

While running same command with pyang 2.1, the result will be 

```
<?xml version="1.0" encoding="UTF-8"?>
<module name="bak"
        xmlns="urn:ietf:params:xml:ns:yang:yin:1"
        xmlns:bak="http://tail-f.com/ns/example/bak"
        xmlns:bbf-l2-fwd="http://tail-f.com/ns/example/smp">
  <yang-version value="1.1"/>
  <namespace uri="http://tail-f.com/ns/example/bak"/>
  <prefix value="bak"/>
  <import module="smp">
    <prefix value="bbf-l2-fwd"/>
  </import>
  <feature name="bak"/>
  <augment target-node="/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarding-databases/bbf-l2-fwd:forwarding-database/bbf-l2-fwd:static-mac-address/bbf-l2-fwd:learning-constraint/bbf-l2-fwd:allowed-to-learn-on/bbf-l2-fwd:allow-to-learn-on">
    <if-feature name="bbf-l2-fwd:forwarding-databases and bbf-l2-fwd:mac-learning"/>
    <case name="ethernet-interfaces">
      <if-feature name="bbf-l2-fwd:shared-forwarding-databases"/>
      <container name="interface-references">
        <leaf-list name="interface">
          <type name="string"/>
        </leaf-list>
        <leaf name="dev-target">
          <type name="string"/>
        </leaf>
      </container>
    </case>
  </augment>
</module>

```

From my point of view it seems 1.7.8 gives the corret output, i.e. branches under "if-feature bbf-l2-fwd:shared-forwarding-databases" have been removed, cause the feature "bbf-l2-fwd:shared-forwarding-databases" is implicitly disabled. Why 2.1 still keeps them?

**Comment by mbj4668** [comment]
YIN is just another syntax for YANG.  Which features are used do not change the syntax.  -f yang and -f yin both behave in the same way in this regard.

**Comment by lukai-nokia** [comment]
Does that means the parameters "-F" and "--features" will not change the YANG/YIN syntax? And which is the reason why pyang version 2.1 kept the "disabled" branches?
If yes, the parameters "-F" and "--features" will look odd cause they seem to do nothing, neither validate something nor affect the output. Or maybe I misunderstood their usage?

**Comment by mbj4668** [comment]
Correct, they will not change the syntax.

Other plugins may be affected by the features, e.g., if you have a plugin that generates code for an implementation.  The tree plugin also shows a pruned tree.
