### ISSUE TITLE
pyang can't recognize valid values for an identityref.

### ISSUE THREAD

**Issue by fredgan** [mbj4668/pyang#540]
Hi,
As described in [RFC7950 9.10.2](https://tools.ietf.org/html/rfc7950#page-163)
```
   Valid values for an identityref are any identities derived from all
   the identityref's base identities.  On a particular server, the valid
   values are further restricted to the set of identities defined in the
   modules implemented by the server.
```
 Valid values for an identityref is one of identities derived from all the identityref's base identities. However, pyang(version 2.1.1) will report some errors. The module is as following:
`a.yang`
```
module a {
  yang-version 1.1;
  namespace "urn:cesent:a";
  prefix aa;

  identity id1;
  identity id4;
  identity id7;

  identity id2 {
    base id1;
  }

  identity id3 {
    base id2;
  }

  identity id5 {
    base id4;
  }

  identity id6 {
    base id5;
  }

  identity id8 {
    base id7;
    base id6;
  }

  leaf le1 {
    type identityref {
      base id1;
      base id4;  
    }
    default "id8";  // "id8" is derived from "id4" 
  }
}
```
The actual result :
```
$pyang -Werror a.yang
b.yang:36: error: the value "id8" does not match its base type - identityref not derived from id1
```
The expected result is that pyang should not report any error.

**Comment by ptlm** [comment]
Reading the quote from the rfc, for the value "id8" to be valid for le1, it needs to be derived from all base identities of le1, not just some.
Since id8 is not derived from id1, it is not derived from all bases of le1, hence not a valid value for le1.

**Comment by fredgan** [comment]
@ptlm It seems you are right.  But I don't understand what is the intention of thie design. 

Maybe we need Martin for help. @mbj4668

**Comment by mbj4668** [comment]
This rule makes it possible to say that the the leaf must be an identity that is derived from ALL bases.  If you want ANY bases, you can do that with a union:

    type union {
        type identityref {
            base id1;
        }
        type identityref {
            base id4;
        }
    }
