### ISSUE TITLE
env.sh fails if path contains spaces

### ISSUE THREAD

**Issue by ruipires** [mbj4668/pyang#542]
This is a minor issue, but also has a minor fix.

If PATH contains spaces, env.sh will fail.
Spaces in PATH are generally avoided, but that is harder when running under WSL (where windows injects its PATH into the WSL environment PATH).

If env.sh uses PATH (and other similar variables) in quotes, the issue no longer happens.

    p=`pwd`
    export PATH="$p/bin:$PATH"
    export MANPATH="$p/man:$MANPATH"
    export PYTHONPATH="$p:$PYTHONPATH"
    export YANG_MODPATH="$p/modules:$YANG_MODPATH"
    export PYANG_XSLT_DIR="$p/xslt"
    export PYANG_RNG_LIBDIR="$p/schema"
    export W="$p"

**Comment by mbj4668** [comment]
Thanks for the suggestion!
