### ISSUE TITLE
if-feature statements should do the status check for each feature

### ISSUE THREAD

**Issue by fredgan** [mbj4668/pyang#545]
Hi Martin,

As we know
> If a definition is "current", it MUST NOT reference a "deprecated" or
   "obsolete" definition within the same module.
    If a definition is "deprecated", it MUST NOT reference an "obsolete"
   definition within the same module.

But I find the if-feature statment will not check the features' status within the if-feature statement.

I will commit a PR for this issue. And there will be some testcases there.

**Comment by mbj4668** [comment]
fixed in #546
