### ISSUE TITLE
-f yang --keep-comments should print end-of-line comments better

### ISSUE THREAD

**Issue by mbj4668** [mbj4668/pyang#547]
If a module has:

    container foo {
        ...
    } // foo

and you do pyang --keep-comments -f yang, it prints:

    container foo {
        ...
    }
    // foo

The end comment should be printed on the same line.

This is not trivial to fix.

One idea is to try to peek forward on the next stmt when we print "}", and check if the next stmt is a comment, and the one after that is NOT a comment, then treat it as an EOL comment and print it before the newline, if we have space.

Another idea is to modify the tokenizer to keep track of the fact that the comment is on the same line as the "}", and somehow mark that in the _comment stmt, and make use of that in the output module.

**Comment by fredgan** [comment]
Hi Martin @mbj4668 , I want to try to solve this. But I have some questions for the following cases:
How should they be shown?

- 1  after property

```yang
container foo {
    mandatory true; // foo1
} 
```

- 2  `/* foo */` cases

```yang
container foo {
    mandatory true; 
} /* foo2 */
```

- 3 multi lines

```yang
container foo {
    mandatory true; 
} /* foo3-1
foo3-2  */
```

**Comment by mbj4668** [comment]
If we can solve the original use case and your (1) above, that would be great.

Bonus if we also can solve (2).

As for (3), I don't think we should encourage it :)  I.e., don't handle it.
