### ISSUE TITLE
tree diagram differs for feature-constrained caseless 'case'

### ISSUE THREAD

**Issue by kwatsen** [mbj4668/pyang#559]
The tree diagrams for the following two YANG snippets differ:

```
    choice test {
      case foo {
        if-feature disabled-feature;
        container foo {
            ...
        }
      }
    }
```

and:
```
    choice test {
      container foo {
        if-feature disabled-feature;
          ...
      }
    }
```

whereby in the second case the tree diagram contains an empty stub like this:
```
  +--rw (test)
    +--:(foo)
```

FWIW, `yanglint` does NOT print the implicit case statement.  I haven't checked `yangson`.

**Comment by mbj4668** [comment]
I think this is correct.
In the first case the entire case is disabled so it shouldn't be displayed.
In the second case the case is enabled but the container disabled, i.e., it is a shorthand for:

    case foo {
      container foo {
        if-feature disabled-feature;
        ...
      }
    }

**Comment by kwatsen** [comment]
I see how it could be interpreted either way, but it seems that RFC 7950 either left out details or is wrong in saying that they're equivalent.

The issue isn’t limited to tree diagrams either.  For instance, in one case you’re left with an augmentable target and in the other you’re not.

In either case, it seems that Errata may be in order so as to clarify which (if any) descendent statements should be conceptually floated to the implicit ‘case’ statement.   Yes?   [My recommendation is to float both ‘if-feature’ and ‘when’, as that seems to match expected intentions]

In the meanwhile, I’m removing implicit case statements from my modules, since the idiom is being interpreted by tools differently.

Kent

**Comment by mbj4668** [comment]
The RFC doesn't say that substatements are "floated" to the case.  It says that if you omit the case statement, there will still be a "case" schema node, with the same name as the container/leaf/...  The RFC doesn't mention any "implicit case statement", so there is no statement to "float" substatements to.
