### ISSUE TITLE
After install pyang ,it report error,how to set pyang env  ?

### ISSUE THREAD

**Issue by zhanggongc** [mbj4668/pyang#562]
![image](https://user-images.githubusercontent.com/58503468/74795468-04debb80-5301-11ea-85b9-0d640b8bb8c6.png)
![image](https://user-images.githubusercontent.com/58503468/74795515-20e25d00-5301-11ea-8c45-3065ecc13e1a.png)

pyang command report error 
i just want to reproduce openconfig_acl.py from openconfig_acl.yang , so how to use pyang  ?

**Comment by fredgan** [comment]
From your screenshot, I find you install `pyangbind` using `python 2.7`

But when you run pyang,

It report `pyangbind` cannot be found. So you should confirm that you are using python 2.7

1 If you are using python 3.x， please install pyangbind using `pip3 install pyangbind`

2 If still don't work, please try to install pyang first, `python setup.py install`
