### ISSUE TITLE
problem with augment and tree plugin

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [mbj4668/pyang#563]
Hi if we use [this](https://github.com/YangModels/yang/blob/ac6e52f0574d8db59d3ca61f52b339f4a49ea09b/experimental/ietf-extracted-YANG-modules/sfc-oam%402014-09-04.yang) module with pyang -f tree it will fail with error that augment has no i_target_node attribute. this should not happen

**Comment by mbj4668** [comment]
Fixed.  The module is seriously broken though.
