### ISSUE TITLE
Interacting with Juniper models

### ISSUE THREAD

**Issue by ibarrere** [mbj4668/pyang#568]
I'm able to generate a tree representation of Juniper models fine as long as I set the path properly, but for whatever reason bindings and jtox files that I attempt to create with them end up incomplete, although pyang itself does not throw any errors.

Tree command:

`pyang -f tree conf/junos-ex-conf-interfaces@2018-01-01.yang -p ../`

jtox command:

`pyang -f jtox -o ~/juniper_ints.jtox conf/junos-ex-conf-interfaces@2018-01-01.yang -p ../`

Running the jtox command does not throw an error, but the jtox file is basically empty except for the import declarations from junos-ex-conf-interfaces@2018-01-01.yang:

```{"tree": {}, "modules": {"junos-ex-conf-root": ["jc", "http://yang.juniper.net/junos-ex/conf/root"], "junos-ex-conf-interfaces": ["jc-interfaces", "http://yang.juniper.net/junos-ex/conf/interfaces"], "junos-common-ddl-extensions": ["junos", "http://yang.juniper.net/junos/common/ddl-extensions"], "junos-common-types": ["jt", "http://yang.juniper.net/junos/common/types"]}, "annotations": {}}```

The same thing happens when I try to create a pybind file from Juniper models. The .py file ends up tiny, with just a few lines in it.

Is there something I'm missing here?

```
{ version info:

ibarrere@rigel junos-ex % python --version
Python 2.7.16
ibarrere@rigel junos-ex % pyang --version
pyang 2.1.1
ibarrere@rigel junos-ex %

}
```

**Comment by fredgan** [comment]
Will you mind attaching the YANG models?

**Comment by ibarrere** [comment]
No problem, here is the one I was testing with (I changed the extension from .txt to .yang as github doesn't support uploading arbitrary file types apparently). It seems to affect most/all of the Juniper ones in the [YangModels github repo](https://github.com/YangModels/yang.git) though.

[junos-ex-conf-interfaces@2018-01-01.txt](https://github.com/mbj4668/pyang/files/4262599/junos-ex-conf-interfaces%402018-01-01.txt)

**Comment by fredgan** [comment]
Hi, I checked the YANG model `junos-ex-conf-interfaces@2018-01-01.yang`

All the contents are grouping statements except meta statements and import statements.
There are no data nodes(leaf or leaflist or container and so on) in the root of the model.

But the tree format or jtox format only shows data nodes. So there are no schema nodes showed in tree or jtox format.

So, if you want to show one of the grouping, you can use `uses` statements.

**Comment by ibarrere** [comment]
> All the contents are grouping statements except meta statements and import statements.
> There are no data nodes(leaf or leaflist or container and so on) in the root of the model.

Good point, I didn't notice that, and it surely has something to do with the issue.

> However, the tree format or jtox format only shows data nodes. So there are no schema nodes showed in tree or jtox format.

The default tree format shows all the elements for this particular model though (only including a few lines here for brevity):

`ibarrere@rigel conf % pyang -f tree junos-ex-conf-interfaces@2018-01-01.yang -p ../../

module: junos-ex-conf-interfaces
  augment /jc:configuration:
    +--rw interfaces
...
       |     +--rw name     string
       |     +--rw value?   string
       +--rw interface-set* [name]
       |  +--rw name                   string
...
       |  |  +--rw name    string
       |  |  +--rw data* [name]
       |  |     +--rw name     string
       |  |     +--rw value?   string
       |  +--rw interface* [name]
       |     +--rw name                   union
 ...
       |     |  +--rw data* [name]
       |     |     +--rw name     string
...`

If I run with --tree-no-expand-uses then the tree reflects what I see in the jtox and pybind outputs:

`ibarrere@rigel conf % pyang -f tree junos-ex-conf-interfaces@2018-01-01.yang -p ../../ --tree-no-expand-uses

module: junos-ex-conf-interfaces
  augment /jc:configuration:
    +---u interfaces-group
  augment /jc:configuration/jc:groups:
    +---u interfaces-group
ibarrere@rigel conf %`

> So, if you want to show the nodes in one of the grouping statements, you can use uses statements.

I'm not sure what you mean here. I would like to create jtox or pybind files based on the Juniper models. Is there a way to do this with the current state of the Juniper models and pyang?

**Comment by fredgan** [comment]
Hi,
Unfortunately, both `jtox` and `pyangbind` plugins do not support `augment` or `grouping` statements.
`tree` plugin is a bit better, supports `augment` statement.

> I would like to create jtox or pybind files based on the Juniper models. Is there a way to do this with the current state of the Juniper models and pyang?

Maybe current output is not what you expect, but it is the actual jtox or pybind files created by jtox or pyangbind.

If you want to show the inner structure of `grouping A`, you should write a statment `uses A;` in the model. 

If you want to show the result of `augment` statement, I have no idea now.

**Comment by ibarrere** [comment]
I see, so using the default Juniper models (without changing them) there is no way to generate jtox ot pybind.

Thanks for answering my question.
