### ISSUE TITLE
An action MUST NOT have any ancestor node that is a list node without a "key" statement

### ISSUE THREAD

**Issue by fredgan** [mbj4668/pyang#572]
Hi,
As described in [RFC 7950 Chapter 7.15](https://tools.ietf.org/html/rfc7950#page-119)
```
An action MUST NOT have any ancestor node that is a list node without a "key" statement.
```
As far as I know, when a module's yang-version is 1.1, it should throw some errors if a 'list' node without a 'key' statement contains an 'action' node. However, things don't turn out the way you want.
`pyang version is 2.1.1`

YANG module:
```
module mod1 {
  yang-version 1.1;
  prefix aa;
  namespace "urn:mod1";

  list lst1 {
    //key "name";
    config false;
    leaf name {
      type string;
    }
    action act { // error: 'key' is missing
      description "test description";
    }
  }
}
```
It's expected to report an error like : ` an action node cannot have  an accestor list node without a key`

**Comment by 13301584865** [comment]
Hi fredgan,

I noticed that the content of v_reference_notification is same as v_reference_action, the code is redundant.

Thanks

Jie

**Comment by fredgan** [comment]
@13301584865 You are right. Thank you, I will push an PR for reducing one.
