### ISSUE TITLE
Package __init__ contains code; imports a lot

### ISSUE THREAD

**Issue by ptlm** [mbj4668/pyang#581]
The pyang/__init__.py module contains the implementation for module repository, and its context. To that end, it imports several modules, which in turn pull in most of pyang. 

This means, that each import pyang, imports all of it in effect. All of the imports except grammar.py are used by the implemented classes. It is unclear, if the imports were meant to provide a convenience API to just import pyang in client code instead of individual modules the client code uses.

In case of package requirements like lxml, the current code cannot import them normally, as setup.py would fail in case the dependency is missing - all the while setup.py is supposed to declare the dependency as a target for installation.

The suggestion is to move the code into a separate repository.py module. Thus only `__version__` and `__date__` would remain. A potential side effect is for 3-rd party code that relies on just importing pyang, this would be a breaking change.

**Comment by mbj4668** [comment]
Sounds like a good idea!
