### ISSUE TITLE
pyang crash because of no validating the value of min-elements when the "default" statement is present

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#590]
I did the following test with pyang 2.2.1, pyang will crash.

pyang mod2.yang --print-error-code

module mod2 {
  yang-version 1.1;
  prefix bb;
  namespace "urn:mod2";

  leaf-list le1 {
    type int8;
    max-elements 50;
    min-elements 'cd';
    default 0;
  }
}

output:
  File "E:\PycharmProjects\pyang_master\venv\lib\site-packages\pyang\statements.py", line 1029, in v_type_leaf_list
    if m is not None and int(m.arg) > 0:
ValueError: invalid literal for int() with base 10: 'cd'

Thanks

Jie

**Comment by fredgan** [comment]
Hi,Jie. It’s also fixed by #588

**Comment by JieZhang0822** [comment]
@fredgan,

I checked your fix of #588, current case is not covered by #588.

In current case the "default" statement is present in the leaf-list.

You can try it.

Thanks

Jie

**Comment by fredgan** [comment]
Hi Jie, actually it is covered in my second commit in #588 . Thanks

**Comment by JieZhang0822** [comment]
fredgan,

Sorry about it. I missed your second commit of c56ccb6.

Thanks

Jie

**Comment by JieZhang0822** [comment]
Thanks fredgan. 

As you already fixed this issue in your second commit of c56ccb6, I will close current issue directly.

Jie
