### ISSUE TITLE
illegal range restriction is not checked by pyang of 2.2.1

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#592]
Test procedure:

Use the following yang file to run pyang with 2.2.1.

pyang mod1.yang  --print-error-code

```
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m1;

  typedef my-base-int32-type {
    type int32 {
      range "1..4 | 10..20";
      }
   }

   typedef my-type1 {
     type my-base-int32-type {
       range "1..10"; //illegal range restriction
     }
   }
}
```

The range "1..10" is illegal range restriction, but there is no error reported.

Thanks

Jie

**Comment by fredgan** [comment]
Thanks for your report. Should be fixed now, please try the latest master branch again.
