### ISSUE TITLE
pyang wrongly rejects substring function with 2 arguments

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#601]
See the attached yang model
[example.zip](https://github.com/mbj4668/pyang/files/4509710/example.zip)

It has a must constraint "substring(., 2) = 'test'" which is rejected by pyang 2.2.1 with the following error:

"example.yang:10: error: XPath function "substring" takes 3-4 arguments but called with 2."

This is completely wrong, the substring function has 2-3 arguments, not 3-4.   See https://www.w3.org/TR/1999/REC-xpath-19991116/#section-String-Functions

**Comment by verthezpw** [comment]
Note that in pyang 1.7.5 this was working fine.

**Comment by fredgan** [comment]
Thanks for you report. It should be fixed now. Please try the latest master branch.
