### ISSUE TITLE
An action MUST NOT be defined within an rpc, another action, or a notification

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#603]
The following is mentioned in RFC 7950:

> 7.15. The "action" Statement
> An action MUST NOT be defined within an rpc, another action, or a
> notification, i.e., an action node MUST NOT have an rpc, action, or a
> notification node as one of its ancestors in the schema tree.

**An action MUST NOT be defined within an rpc, another action, or a notification.**

But use the following yang file to run pyang with 2.2.1, no errors are reported.

```
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m1;

  rpc rpcnode {//This is rpc node
    input {
      leaf reset-rpc {
        type string;
      }
      list ifEntry {
        key "ifIndex";
        leaf ifIndex {
          type uint32;
        }

        action reset {//error: action is defined within an rpc
          input {
            leaf reset-at {
              type string;
              mandatory true;
            }
          }
          output {
            leaf reset-finished-at {
              type string;
              mandatory true;
            }
          }
        }
      }
    }
  }
}
```

I am not sure that the current case accords with an action defined within a rpc.

Please correct me if my understanding is wrong.

Thanks

Jie

**Comment by fredgan** [comment]
Thanks, it should be fixed now
