### ISSUE TITLE
A notification MUST NOT be defined within an rpc, action, or another notification

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#604]
The following is mentioned in RFC 7950:

> 7.16. The "notification" Statement
> A notification MUST NOT be defined within an rpc, action, or another
> notification, i.e., a notification node MUST NOT have an rpc, action,
> or a notification node as one of its ancestors in the schema tree.

**A notification MUST NOT be defined within an rpc, action, or another notification**

But use the following yang file to run pyang with 2.2.1, no errors are reported.

```
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m1;

  rpc rpcnode {//This is rpc node
    input {
      leaf reset-rpc {
        type string;
      }
      list ifEntry {
        key "ifIndex";
        leaf ifIndex {
          type uint32;
        }

        notification reset {//error: notification is defined within an rpc
          leaf reset-at {
            type string;
            mandatory true;
          }
        }
      }
    }
  }
}
```

Thanks

Jie

**Comment by fredgan** [comment]
Thanks, it should be fixed now
