### ISSUE TITLE
 A definition of "current" reference a "deprecated" or "obsolete" definition within the same module.

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#606]
The following is mentioned in RFC 7950:

> 7.21.2. The "status" Statement
> If a definition is "current", it MUST NOT reference a "deprecated" or
> "obsolete" definition within the same module.
> If a definition is "deprecated", it MUST NOT reference an "obsolete"
> definition within the same module.

But use the following yang file to run pyang with 2.2.1, no errors are reported.

```
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m1;

  list my-leaf {
    key name;
    status current;

    leaf name {
      type string;
      status obsolete; //illegal, since name is obsolete
    }
  }
}
```

Thanks

Jie

**Comment by fredgan** [comment]
it won't report any errors when a `current` list node exists a `obsolete` leaf node, but it will if a `current` list node references a `obsolete` leaf node

you can try it.
```
$pyang -f yang mod1.yang
mod1.yang:15: error: the "leaf" definition is current, but the "leaf" it references is obsolete
module mod1 {
  yang-version 1.1;
  namespace "urn:mod1";
  prefix m1;

  list my-leaf {
    key name;
    status current;

    leaf name {
      type string;
      status obsolete; //illegal, since name is obsolete
    }
  }
  leaf le1 {
    type leafref {
      path "../my-leaf/name";
    }
  }
}
```

**Comment by JieZhang0822** [comment]
@fredgan ,

Thanks your response. 

I still have some confusion, as the leaf name is the key of list in my test case, but the status is obsolete.

It is not reasonable.

Thanks

Jie

**Comment by mbj4668** [comment]
I agree w/ @JieZhang0822.  The "key" statement is part of a "current" definition, and it references an "obsolete" leaf.  So I think this should be reported.

**Comment by fredgan** [comment]
Thanks, it should be fixed now.
