### ISSUE TITLE
pyang does not support default deviation on leaf-list

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#615]
The attached model defines a deviation to add a default to a leaf list:
[example.zip](https://github.com/mbj4668/pyang/files/4573228/example.zip)

pyang 2.2.1 fails this erroneously with:
example-dev.yang:12: error: the "default" property cannot be added

Adding a default to a leaf is working properly.

**Comment by fredgan** [comment]
Thanks for reporting, it should be fixed now.
