### ISSUE TITLE
Command 'pyang' not found

### ISSUE THREAD

**Issue by mrmerumaru** [mbj4668/pyang#624]
Hi,

I have already installed pyang, but when I want to use it, it says command not found.
What am I missing / not doing?

meru@ubuntu:\~/Documents/$ pip3 install pyang
Requirement already satisfied: pyang in /home/meru/.local/lib/python3.8/site-packages (2.2.1)
Requirement already satisfied: lxml in /home/meru/.local/lib/python3.8/site-packages (from pyang) (4.5.0)
meru@ubuntu:~/Documents/$ pyang -f tree ietf-interfaces.yang

Command 'pyang' not found, did you mean:

  command 'pynag' from deb pynag (1.1.2+dfsg-2)
  command 'pylang' from deb pylang (0.0.4-0ubuntu3)

Try: sudo apt install <deb name>

meru@ubuntu:\~/Documents/$
meru@ubuntu:\~/Documents/$ sudo pyang -f tree ietf-interfaces.yang
sudo: pyang: command not found
meru@ubuntu:\~/Documents/$

**Comment by fredgan** [comment]
Maybe just because your env `PATH` is not set correctly, referring to: https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

For another way, you can clone this repo, then use `python3 setup.py install` to install `pyang`

**Comment by mrmerumaru** [comment]
after googling, turns out the fix was pretty simple

meru@ubuntu:\~$ sudo pip3 install pyang **--user**
[sudo] password for meru:
Collecting pyang
  Downloading pyang-2.2.1-py2.py3-none-any.whl (578 kB)
     |████████████████████████████████| 578 kB 813 kB/s
Collecting lxml
  Downloading lxml-4.5.0-cp38-cp38-manylinux1_x86_64.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 1.6 MB/s
Installing collected packages: lxml, pyang
Successfully installed lxml-4.5.0 pyang-2.2.1
meru@ubuntu:\~$

now I can use pyang
