### ISSUE TITLE
Questions about the choice’s "case" Statement  

### ISSUE THREAD

**Issue by JieZhang0822** [mbj4668/pyang#630]
@mbj4668 ,

I have some questions about the choice’s "case" Statement.

The following is mentioned in RFC 7950:

> 7.9.2.  The choice’s "case" Statement
> As a shorthand, the "case" statement can be omitted if the branch   contains a single "anydata", "anyxml", "choice", "container", "leaf",   "list", or "leaf-list" statement.  In this case, the case node still   exists in the schema tree, and its identifier is the same as the   identifier of the child node.  Schema node identifiers (Section 6.5)   MUST always explicitly include case node identifiers. 
> The following   example:

```
 choice interface-type {      
     container ethernet { ... }     
  }
```

> is equivalent to:

```
 choice interface-type {       
      case ethernet {         
        container ethernet { ... }      
      }     
   }

```
**My question is what's meaning the following example?**
```
 choice interface-type {      
     container ethernet { ... }     
     container gpon { ... }
     container vdsl { ... }  
  }
```
Is  equivalent to?
```
 choice interface-type {       
      case ethernet {         
        container ethernet { ... }      
      }     
      case gpon {         
        container gpon { ... }      
      }  
      case vdsl {         
        container vdsl { ... }      
      }  
   }

```
Could you please help me confirm it?

Thanks

Jie

**Comment by fredgan** [comment]
Yeah, what you understanding is correct.

In fact, you can print the tree format in both cases, then you will find they are the same.

**Comment by JieZhang0822** [comment]
@fredgan,

Thanks your answer. Now it is clear for me.

Jie
