### ISSUE TITLE
Share my Experience of Installing pyang on Windows Platform

### ISSUE THREAD

**Issue by ericchenkai** [mbj4668/pyang#636]
Hi, I find it is easier to use "Git Bash"  to use `pyang` on windows. 

1. Download "Git on Windows" on https://gitforwindows.org/ and install as normally as other windows software (double click and next step). 

2. Install `python`. I installed latest python 3.8.  Just ensure to check "Add python 3.8 to PATH" if one does not have good experience of using python. 
NOTE: virtualenv is a good option if one is an experienced user. 

3. Install `python` using `pip install pyang`

4. How-to-use: (Optionally, open the directory with pyang files) Right click , and choose "Git Bash Here", test run `pyang -h`. 

If any issue, check the python PATH is correct in **system variables** configuration.

**Comment by fredgan** [comment]
Okay, Thanks for your sharing.

**Comment by ericchenkai** [comment]
Cheers. I think I can close this ticket by myself now :-)
