### ISSUE TITLE
Next release cut?

### ISSUE THREAD

**Issue by remingtonc** [mbj4668/pyang#637]
Selfishly wondering when the next release of pyang will be cut, specifically so I can `pip install pyang` for the `flatten` plugin instead of eggs and GitHub. :) Not a rush, but interested!

**Comment by mbj4668** [comment]
I was hoping to do this before going on vacation, but didn't get hold of @fredgan .  So it may have to wait a few weeks.

**Comment by fredgan** [comment]
OK, I will.

**Comment by remingtonc** [comment]
Will this make it to pypi?
