### ISSUE TITLE
jstree HTML output: "action" parameters are not expanded, just listed as tooltip

### ISSUE THREAD

**Issue by GermanoSMO** [mbj4668/pyang#638]
As per the subject

Generating the HTML view with the --jstree option, while for "rpc" the input and output parameters are expanded and visibile as any other data tree node, this is not happening for the "action" statement

In the HTML tree view, the "action" is reported as expected in the datatree, but there is a generic "parameters" type and nothing else. 

To see which are the input and output parameters defined for the action, the only way is hovering the "parameters" type and then the tooltip simply summarizes "in" and "out" nodes - that's it.  See the attached screenshot:

![Action1-pyang](https://user-images.githubusercontent.com/15357944/85730951-602f1900-b6fa-11ea-97fc-52a0d8a6278a.png)

It would be definitely useful if also the "action" is expanded in the HTML jstree view exactly as it is done for "rpc", i.e. as expandable/collapsible nodes like that:

![Action2-Window](https://user-images.githubusercontent.com/15357944/85731028-73da7f80-b6fa-11ea-8336-be0382196309.png)

**Comment by fredgan** [comment]
Hi Germano @GermanoSMO ,
In fact, there is another way, just click `Expand All` button, it will show the `action` like `rpc`. But you are right, there is no way to expand it alone.
I will try to modify this like `rpc`. But I am not sure whether we should reserve the `parameters` label?

**Comment by fredgan** [comment]
Hi Germano @GermanoSMO ,
    Please have a look at #640 
    If you feel OK, I will merge it and make a release soon.
