### ISSUE TITLE
tree format: inline augments

### ISSUE THREAD

**Issue by alex4747-pub** [mbj4668/pyang#644]
It is a real pain to manually move 100+ augments to proper place inside a big tree, is it possible to automate this process?

**Comment by fredgan** [comment]
Sorry, I don't understand it completely. Can you explain it more detailed?

**Comment by alex4747-pub** [comment]
Say I have set of yang trees with about quite a few augmentation statements. When I run pyang -f tree ..., I got the base tree first
module: volta-cli
  +--rw volta-top
     +--rw devices
        +--rw device* [id]
           +--rw id                    uint64
           +--rw name                  string

And then every augmentation as separate unrelated fragment:

  augment /oc-netinst:network-instances/oc-netinst:network-instance:
    +--rw bridge-domains
       +--rw bridge-domain* [name]
          +--rw name                       string
          +--rw descirption?               string

And I want a single tree with all deviations and augmentations applied.

**Comment by fredgan** [comment]
Maybe you can try like:
`pyang -f tree test.yang test-dev.yang`

`test.yang`:

```yang
module test {
  yang-version 1.1;

  namespace urn:test;

  prefix test;

  container root {
    list child {
      key name;
      leaf name {
        type string;
      }
      leaf foo {
        mandatory true;
        type string;
      }
    }

    leaf-list ll {
      type string;
    }
  }
}
```
`test-dev.yang`:

```yang
module test-dev {
  yang-version 1.1;
  namespace urn:test-dev;
  prefix test-dev;

  import test {
    prefix t;
  }

  augment /t:root {
    leaf augmented {
      type string;
    }
  }

  deviation /t:root/t:ll {
    deviate replace {
      type int32;
    }
  }
}

```

output:
```
module: test
  +--rw root
     +--rw child* [name]
     |  +--rw name    string
     |  +--rw foo     string
     +--rw ll*                   int32
     +--rw test-dev:augmented?   string
```

I am not sure whether this is what you want.

**Comment by llhotka** [comment]
If you have a large number of modules and don't want to write them all on the command line, you can also use the `-L/--hello` option with a name of a NETCONF hello file. See [YANG Data Model](https://github.com/mbj4668/pyang/wiki/Tutorial#yang-data-model) for an example.

**Comment by alex4747-pub** [comment]
This is what I want, and it does work. I added nested container and augmented it. It did not work as expected. Also I found that I may have augment statements for nodes that do not exist in my tree, may be this is the I would expect that it should be flagged by strict check and ignored.

In the mean time my results on augmenting nested container:
 
test.yang

module test {
  yang-version 1.1;

  namespace urn:test;

  prefix test;

  container root {
    list child {
      key name;
      leaf name {
        type string;
      }
      leaf foo {
        mandatory true;
        type string;
      }
    }

    leaf-list ll {
      type string;
    }

    container nested {
      leaf nested-val {
        type uint32;
      }
    }
  }
}

test-dev.yang

module test-dev {
  yang-version 1.1;
  namespace urn:test-dev;
  prefix test-dev;

  import test {
    prefix t;
  }

  augment /t:root {
    leaf augmented {
      type string;
    }
  }

  augment /t:root/nested {
    leaf nested-augmented {
      type string;
    }
  }

  deviation /t:root/t:ll {
    deviate replace {
      type int32;
    }
  }
}

 pyang -f tree test.yang test-dev.yang
test-dev.yang:16: error: node test-dev::nested is not found
module: test
  +--rw root
     +--rw child* [name]
     |  +--rw name    string
     |  +--rw foo     string
     +--rw ll*                   int32
     +--rw nested
     |  +--rw nested-val?   uint32
     +--rw test-dev:augmented?   string
     +--rw test-dev:nested
        +--rw test-dev:nested-augmented?   string

**Comment by alex4747-pub** [comment]
I had resolved it. I had augments to non-existing nodes.
