### ISSUE TITLE
config false deviation not working when leaf did not mention config true explicitly

### ISSUE THREAD

**Issue by verthezpw** [mbj4668/pyang#646]
See the following example model:
[example.zip](https://github.com/mbj4668/pyang/files/4850451/example.zip)

This fails to validate with the following error:
example.yang:8: error: the "config" property does not exist in node "example::someleaf"

It looks like the deviation fails because someleaf does not explicitly have 'config true'. 

But according to the YANG RFC, 'config true' is implied when it is not present (https://tools.ietf.org/html/rfc7950#section-7.21.1)

This is failing newly in 2.3.0.   It was succeeding in 2.2.1 and 1.7.5

**Comment by fredgan** [comment]
Hi @verthezpw , 
  according to my understanding to the RFC,  `deviate replace` target nodes must explicitly have `config true`.  
Because `deviate add`/`deviate delete` use the same word to describe the property. `config` property always exists. So the `exist` means explicitly exist.

**Comment by verthezpw** [comment]
According to me the property does exist.   If you ask the leaf for whether it is config false or config true, then it will reply config true, so it has the property, even if it is not explicitly in the YANG model.   I'll check with some other experts on my side for their opinion, or if needed even on the netconf mailing list.

**Comment by fredgan** [comment]
OK, How do you understand the under quote?
```
The argument "add" adds properties to the target node.  The
   properties to add are identified by substatements to the "deviate"
   statement.  If a property can only appear once, the property MUST NOT
   exist in the target node.
```
If I use the following to one leaf node, because config property  will alway exists in the node (implicit or explicit). If `exist` means not explicitly, this should be always failed
```yang
deviate add {
    config true;
}
```

I also tested it in `yanglint`, it's the same result with current `pyang`.

**Comment by verthezpw** [comment]
Well, I just found this: https://github.com/mbj4668/pyang/issues/267 where the pyang developer says the exact opposite...

**Comment by verthezpw** [comment]
I see that the answer in #267 comes from Martin Bjorklund himself, who is the author of the YANG RFC.   So do you agree that this is a definite reference?

**Comment by fredgan** [comment]
Hmmm, I'd better ask himself to confirm this. So please just wait for some time.

**Comment by verthezpw** [comment]
OK, thanks, no problem. I do agree that the YANG RFCs can sometimes be interpreted in different ways.

**Comment by fredgan** [comment]
Hi, @verthezpw 

You are right! Martin has confirmed this and I will re-fix this soon!

**Comment by verthezpw** [comment]
Thanks!

**Comment by fredgan** [comment]
@verthezpw Please try again

**Comment by verthezpw** [comment]
I took the latest master, but the example I uploaded above is still giving the same error.

**Comment by fredgan** [comment]
There is no error reported when I use the example provided above, do you use the wrong version?

**Comment by verthezpw** [comment]
I did a git clone of https://github.com/mbj4668/pyang.git again to be sure to have the latest, but I still see the problem.    I tried also with python2 and python3 to be sure, but both are giving the error.

**Comment by verthezpw** [comment]
Output:

verthezp@host-192-168-0-14:~/local/pyang/pyang-master$ git log | head -10
commit 87e67fe3b5346e82f2e8d531d62c65092db34108
Author: fredgan <ganshaolong@vip.qq.com>
Date:   Thu Jul 2 17:16:39 2020 +0800

    Bugfix #646 config false deviation not working when leaf did not mention config true explicitly

commit 95d15e4bba106ebe97235b97b9b061db9d2fe6ba
Author: Fred Gan <ganshaolong@vip.qq.com>
Date:   Wed Jul 1 16:12:37 2020 +0800

verthezp@host-192-168-0-14:~/local/pyang/pyang-master$ cd ../configbug/
verthezp@host-192-168-0-14:~/local/pyang/configbug$ which pyang
/home/verthezp/local/pyang/pyang-master/bin/pyang
verthezp@host-192-168-0-14:~/local/pyang/configbug$ pyang *.yang
example-dev.yang:13: error: the "config" property does not exist in node "example::someleaf"
verthezp@host-192-168-0-14:~/local/pyang/configbug$

**Comment by fredgan** [comment]
Yeah, you are right. It's my mistake. Please try the master again.

**Comment by verthezpw** [comment]
OK, on the current master it is fixed now.   Thanks!
