### ISSUE TITLE
I have a little question Pyang Jstree

### ISSUE THREAD

**Issue by dongyeon94** [mbj4668/pyang#655]
I have a question about  Jstree type

I try convert my data file to jstree

but I didn't get result 

my data example
![image](https://user-images.githubusercontent.com/37605781/87263831-40b92e00-c4f9-11ea-9482-93d8f0eeff9b.png)

but I get this result.
![image](https://user-images.githubusercontent.com/37605781/87262736-05693000-c4f6-11ea-91f5-232355d8695a.png)

why lib out blank result??

**Comment by fredgan** [comment]
Hi @dongyeon94 
Are your leafs in the `grouping`? `jstree` won't show the nodes in the grouping if they are not `uses`ed.

**Comment by dongyeon94** [comment]
Hi @fredgan  

yes they are in the group

there are sample code in my data
![image](https://user-images.githubusercontent.com/37605781/87265100-cee2e380-c4fc-11ea-883f-94311366a299.png)


other sample ( contanier , leaf, list) 
![image](https://user-images.githubusercontent.com/37605781/87265198-1ff2d780-c4fd-11ea-8ad8-79338ef2e842.png)


thank you for answer my question
