### ISSUE TITLE
Does the new pyang release support RFC 8529?

### ISSUE THREAD

**Issue by ZengYuanHong** [mbj4668/pyang#668]

**Comment by mbj4668** [comment]
What do you mean with "support"?  RFC 8529 defines a data model.  pyang doesn't implement any data models.

**Comment by ZengYuanHong** [comment]
Thank you very much for your quick response.
My question is that to support the new RFC 8529 "YANG Data Model for Network Instances", does pyang need any update for supporting the new concept "Mount Points"?  
Thank you for pointing out that RFC 8529 is just a model extention and not a language extention, seems that pyang doesn't need any update for it, thanks again.
