### ISSUE TITLE
Type validator crashes on valid range restriction

### ISSUE THREAD

**Issue by Nitori-** [mbj4668/pyang#669]
This scenario is pretty weird, but I think it is still valid YANG:

```
    typedef value_restricted {
        type int8 {
            range 5..10;
        }
    }

    typedef typedef_value_restricted {
        type value_restricted {
            range "min | max";
        }
    }
```

Attempting to use this `min | max` range will result in a crash here due to trying to compare an int and a string:

https://github.com/mbj4668/pyang/blob/9d5ab49c5456646a4a03a4549c13b8c4fa67f54f/pyang/types.py#L346-L347

**Comment by fredgan** [comment]
Thanks for your reporting! It should be fixed now, please try it again using the latest master branch.
