### ISSUE TITLE
Quoted hexadecimal notation returns an error when used in range

### ISSUE THREAD

**Issue by GermanoSMO** [mbj4668/pyang#671]
Hello

while parsing a yang module, pyang returned me an error on this statement:

    leaf foo {
        type uint16 {
            range "0x0000..0x0fff";
        }
    }

pyang returns the following three error messages for the line where the "range" statement is used:

`error: bad value "0x0000..0x0fff" (should be range-arg)`
`error: the value "0000" does not match its base type - not an integer`
`error: range error: "0" is not larger than "0"`  (this latter sounds pretty odd....)

If I remove the quotes, the parsing succeeds.

But if I express the range with the corresponding decimal values, pyang always succeeds regardless of quoting, i.e.:

    range 0..4095;

and

    range "0..4095";

are both accepted as valid and correct.

Considering that:

1. pyang accepts quoted hexadecimal for expressing default values
2. all "range" examples reported in RFC7950 use quoted ranges
3. pyang already ignores the quote presence/absence when using the decimal notation in range expressions

the request is that also hexadecimal notation should be accepted as valid regardless of quoting when used for expressing ranges (exactly as decimal ranges are accepted regardless of quoting)

pyang version used:  pyang 2.3.1

**Comment by fredgan** [comment]
Hi Germano,
for the hexadecimal value type, you said

> If I remove the quotes, the parsing succeeds.

However, I tried, but it also failed, just like the same as that with quotes.

Pyang doesn't accept hexadecimal range values. 

The grammar in RFC7950 in Chapter14 described, it also don't accept hexadecimal range values.

>    range-boundary      = min-keyword / max-keyword /
>                         integer-value / decimal-value
>   integer-value       = ("-" non-negative-integer-value) /
>                          non-negative-integer-value
>
>   non-negative-integer-value = "0" / positive-integer-value
>
>   positive-integer-value = (non-zero-digit *DIGIT)
>
>   zero-integer-value  = 1*DIGIT
> 
>  decimal-value       = integer-value ("." zero-integer-value)

**Comment by GermanoSMO** [comment]
Ok so this is a correct behavior according to RFC7950 and pyang behaves correctly.

I guess that this issue can then be closed with no further actions.
