### ISSUE TITLE
Choice and Case Deprecation

### ISSUE THREAD

**Issue by masif-cs** [mbj4668/pyang#673]
Hi,

I have a  yang model where Choice and Case statement are deprecated as shown below. When I try to generate yang tree out of this I get something like below:

**Yang Snippet:**
```yang
choice subnet {
          status deprecated;
          description
            "The subnet can be specified as a prefix length or,
             if the server supports non-contiguous netmasks, as
             a netmask.";
          leaf prefix-length {
            type uint8 {
              range "0..32";
            }
            status deprecated;
            description
              "The length of the subnet prefix.";
          }
          leaf netmask {
            if-feature ipv4-non-contiguous-netmasks;
            type yang:dotted-quad;
            status deprecated;
            description
              "The subnet specified as a netmask.";
          }
        }
```
**Yang Tree Output:**
```yin
        |  |  x--ro ietf-ip:ip                ietf-inet-types:ipv4-address-no-zone
        |  |  x--ro (ietf-ip:subnet)?
        |  |  |  +--:(ietf-ip:prefix-length)
        |  |  |  |  x--ro ietf-ip:prefix-length?   uint8
        |  |  |  +--:(ietf-ip:netmask)
        |  |  |     x--ro ietf-ip:netmask?
```
Here the problem is when the Choice and the Leaf inside it is marked as deprecated(x) then why the yang tree output has case statement coming as current(+)?

**Comment by fredgan** [comment]
Hi @masif-cs , I find an issue you asked in March #577 
As is said, 

> In YANG, if a container is marked as deprecated, its children are NOT automatically also deprecated. You need to explicitly mark them as well.

Then, in `choice` node, as is described in RFC7950 chapter 7.9.2

> As a shorthand, the "case" statement can be omitted if the branch
   contains a single "anydata", "anyxml", "choice", "container", "leaf",
   "list", or "leaf-list" statement.

So the `case` node is marked as current, the leaf node in `case` is deprecated as what is marked.

**Comment by mbj4668** [comment]
This isn't really specified in the RFC, but imo the status of the implict "case" statement should be the status of the "leaf".

**Comment by fredgan** [comment]
Well, since Martin has explained the case, this should be a bug in pyang. I will fix it soon.

**Comment by masif-cs** [comment]
Hi,

I am trying after downloading the latest Pyang changes. Still I see the same issue. Can you please let me know if I need to follow certain procedure?

**Comment by fredgan** [comment]
@masif-cs Hi, It hasn't not been merged to the master. It will be merged soon and I will notifiy you.

**Comment by fredgan** [comment]
@masif-cs Hi, It should be fixed now.
