### ISSUE TITLE
Yang parsing error around list keys

### ISSUE THREAD

**Issue by esend7881** [mbj4668/pyang#674]
### Problem:
I am working on a project that requires inhereting opendaylight yang models. During the process, I am using pyang to check my syntax and work as I go, however I am finding that pyang is calling out an error in one of the official ODL yangs:

```
$ pyang opendaylight-flow-types@2013-10-26.yang
openflow-instruction@2013-07-31.yang:21: error: the list at "openflow-instruction@2013-07-31.yang:21 (at openflow-action@2015-02-03.yang:32)" needs at least one key because it is used as config
```

I know this yang file installs just fine in the Opendaylight project. 

### My questions:
1. I tried to ignore errors with `-W NEED_KEY_USE` and a variety of other error messages. None work. I did try `--ignore-errors` but that seemed to not do anything. I do want to see errors, just not one related to ODL.
2. Did Opendaylight fork out their YANG syntax, which explains why they don't need the "key" field, etc?

### My Environment:
- pyang 2.3.2
- python 2.7.5 / 3.6.8
- Opendaylight Sodium

### Reference Files:
- [opendaylight-flow-types.yang](https://github.com/opendaylight/openflowplugin/blob/stable/sodium/model/model-flow-base/src/main/yang/opendaylight-flow-types.yang) 
- [more yangs here](https://github.com/opendaylight/openflowplugin/tree/stable/sodium/model/model-flow-base/src/main/yang) 
- The rest of the yang files are scattered about. 
- That said, I zipped them up and attached them here: [yang.zip](https://github.com/CESNET/libyang/files/5177135/yang.zip)

### Also
Since I can't really tell if the problem is on ODL's side as well, I made a couple tickets over at their Jira board:
https://jira.opendaylight.org/browse/OPNFLWPLUG-1103
https://jira.opendaylight.org/browse/OPNFLWPLUG-1104
I also wrote out this issue in the Libyang repo and one of the developers informed me that the devel versions of libyang don't have this problem. Is it possible a devel version of pyang has it resolved as well? https://github.com/CESNET/libyang/issues/1192

**Comment by fredgan** [comment]
@esend7881 
Hi Eric,
  I researched your attached YANG models. I find the `missing key` issue does exist in the models.

I simply analysis it as follows:

the `openflow-instruction.yang` has a root container node in Line20, apparantly it is `config true`.
```yang
    container instruction-container {
        uses instruction-grouping;
    }
```

grouping "instruction-grouping" refers to a grouping `openflow-action:actions-grouping` in Line55 and Line60, which is defined in `openflow-action.yang` in Line31

```yang
    grouping actions-grouping {
        list action {
            uses action-grouping;
            leaf experimenter-id {
                type oft:experimenter-id;
            }
        }
    }
```

Then, you can there's no key in the list. So the error report is correct!

I try to insert a statement like `key experimenter-id;` in `openflow-action.yang` in Line33 (logically maybe incorrect), the error is missing.

Best Regards
Fred

**Comment by esend7881** [comment]
@fredgan thank you very much. I jumped in and found a few other lists that don't have key elements. I really did not expect ODL to have syntax errors like this.  I am updating my [ODL Jira ticket](https://jira.opendaylight.org/browse/OPNFLWPLUG-1103) with this
