### ISSUE TITLE
Exposing the yang model attributes

### ISSUE THREAD

**Issue by masif-cs** [mbj4668/pyang#676]
Hi,

I have set of yang models which we expose to outer world. But I dont want to expose certain leaf/container/list so that user can perform edit-config/get-config etc RPC on those parameters. Is there anyway to achieve that?

**Comment by mbj4668** [comment]
This is a protocol question, not YANG specific, and not pyang specific.

In protocols like NETCONF and RESTCONF, you can apply access control rules to filter out some nodes.

Another option could be to put all these hidden nodes in a separate module that augments the other module, and not expose the hidden module at all to clients.
