### ISSUE TITLE
tree plugin doesn't print augments correctly

### ISSUE THREAD

**Issue by mbj4668** [mbj4668/pyang#681]
A module with just augments should be printed as:
```
module foo

augment ...
```

But pyang prints:
```

module foo
augment ...
```

**Comment by wlupton** [comment]
@mbj4668, this outputs the following with the PR #683 test YANG. It looks a little strange to me to have a blank line between `module` and `augment` but not before `module`. Is this intentional? (I'd be happy with a blank line before but not after, but perhaps that contravenes RFC 8340?)

```
module: base
  +--rw c
     +--rw ext:b
        +--rw main:a
module: main

  augment /base:c/ext:b:
    +--rw a
```

**Comment by mbj4668** [comment]
You're right, it looks odd.  I've added a newline between modules
