### ISSUE TITLE
Error reporting in output formats

### ISSUE THREAD

**Issue by wlupton** [mbj4668/pyang#685]
Running the PR #683 test with this modified `ext.yang`:

```
    container b {
      leaf b1;                         <-- just inserting this line (invalid because no 'type' statement)
    }
```

...gives this error with no explanation:

```
lewa:test_i683% pyang --format=sample-xml-skeleton base.yang main.yang
sample-xml-skeleton plugin needs a valid module
```

Generating a tree outputs this with no error and _including_ the erroneous leaf:

```
lewa:test_i683% pyang --format=tree base.yang main.yang
module: base
  +--rw c
     +--rw ext:b
        +--rw ext:b1?                 <-- this is the erroneous leaf
        +--rw main:a
module: main

  augment /base:c/ext:b:
    +--rw a
```

Of course, specifying `ext.yang` on the command-line reports the error (in both cases):

```
lewa:test_i683% pyang --format=sample-xml-skeleton base.yang main.yang ext.yang 
ext.yang:12: error: expected keyword "type" as child to "leaf"
sample-xml-skeleton plugin needs a valid module
```

...but is this the expected behavior? In the `sample-xml-skeleton` case just getting a general "can't do it" error with no expectation surely can't be intended. The tree case is maybe OK: it's doing the best it can in the circumstances.

**Comment by mbj4668** [comment]
Fixed.  For the tree plugin, you are right; the idea is to do "best effort".
