### ISSUE TITLE
converting leafs to python class generate illegal python code (async)

### ISSUE THREAD

**Issue by taljmars** [mbj4668/pyang#688]
Hi,

First, +1 for impressive work in this repository.

I am see unexpected behavior when t using a generated code by this module.
### Scenario:
1. Generate open-config python modules from YANG models.
2. When loading the modules in my python app I notice the illigal syntax error (due to misuse of "async" keyword)

### Notes:
1. I am generating and using python3.7
2. It look that the following leaf: https://github.com/mbj4668/pyang/blob/master/modules/iana/iana-if-type.yang#L585 cause the issue.

**How can I convert leaf named "async" to something that python accept without breaking any RFCs (i.e. bla_async)**

Stacktrace:
  _File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/python3.7/site-packages/open-config/__init__.py", line 1095, in <module>
    from . import bfd
  File "/python3.7/site-packages/open-config/bfd/__init__.py", line 24, in <module>
    from . import interfaces
  File "/python3.7/site-packages/open-config/bfd/interfaces/__init__.py", line 24, in <module>
    from . import interface
  File "/python3.7/site-packages/open-config/bfd/interfaces/interface/__init__.py", line 28, in <module>
    from . import peers
  File "/python3.7/site-packages/open-config/bfd/interfaces/interface/peers/__init__.py", line 24, in <module>
    from . import peer
  File "/python3.7/site-packages/open-config/bfd/interfaces/interface/peers/peer/__init__.py", line 24, in <module>
    from . import state
  File "/python3.7/site-packages/open-config/bfd/interfaces/interface/peers/peer/state/__init__.py", line 25
    from . import async
                      ^
SyntaxError: invalid syntax_

Thanks In advanced,
Tal

**Comment by fredgan** [comment]
Hi Tal, 
`async` is a keyword in Python version greater than 3.5.
Which software are you using for generating  the python code from YANG files? 

Maybe you should raise an issue to that repo(Such as renaming the leafs with python keyword name)

**Comment by taljmars** [comment]
Hi @fredgan,
I am using pyang to convert the YANG models. i.e.
`pyang --plugindir $PYBINDPLUGIN -f pybind --split-class-dir /generated/ --use-xpathhelper ./*.yang`

I am using the models in the standard OpenConfig, so changing them cannot be done.
b.t.w you can also find a problematic code in this repository: https://github.com/mbj4668/pyang/blob/master/modules/iana/iana-if-type.yang#L585

I think it need to be solved in the convertor level for varied cases like "class", "def", etc..
like the conversion being made from '-' to '_'..

Can you assist with fixing it or at least direct me to the relevant place in the code for now ?

Thanks again,
Tal

**Comment by fredgan** [comment]
Hi @taljmars 
I see. It's generated by the plugin `pyangbind`, the repo is https://github.com/robshakir/pyangbind 
You'd better to raise an issue to that repo. I will also try to research it.

**Comment by taljmars** [comment]
@fredgan Indeed an issue in the plugin, I will try `pyangbind` - Thanks.
