### ISSUE TITLE
Should 'looks like a prefix' warning be applied to string comparisons?

### ISSUE THREAD

**Issue by wivory** [mbj4668/pyang#693]
I'm seeing a PYANG warning in a must statement comparing a node value to a string that contains a ':', as it 'looks like a prefix'.  I am surprised that PYANG is concerning itself with the content of a string here.  It is only a warning, and I note that the warning has changed from 'prefix is not defined' in 1.7.8 to 'looks like a prefix' in 2.3.2, but I am unclear why it should matter inside a string?

Obviously I could disable this specific warning, but I don't like doing that unless I really really have to, so would appreciate an explanation of why it is considered a warning in case I'm missing something.

For reference, the must statement is this:

						must "not(../../clock-profile = 'vyatta-g.8275.1-v1:g.8275.1-forwardable-profile'"
							 + "or ../../clock-profile = 'vyatta-g.8275.1-v1:g.8275.1-non-forwardable-profile')" {
							error-message "The G.8275.1 profile clock does not support allowed-peer configuration";
						}

So while in this case it is a prefix, I could equally be simply looking for a string that happens to include a colon and I'd get the same warning.

Thanks!

**Comment by mbj4668** [comment]
The reason for this is that originally pyang didn't have an XPath parser, so it would complain that an imported module wasn't being used in some cases.  Then we added a rudimentary XPath parser, and now we a proper XPath parser, so perhaps this warning should be removed.  Meanwhile, you can pass "--ignore-error WPREFIX_NOT_DEFINED" to supress this error (use "--print-error-code" to find the name of the code).

**Comment by wivory** [comment]
OK - thanks for clarifying.  I'll use WPREFIX_NOT_DEFINED for now. Feel free to close the bug if you want.
