### ISSUE TITLE
pyang does not detect missing quote

### ISSUE THREAD

**Issue by BalazsLengyel** [mbj4668/pyang#700]
pyang 2.4.0 
IN line 8 in the statemetn units minutes";
A quote is missing. pyang does not detect it. Why?
 ON the yangvalidator webpage I get 

yanglint Validation

err : Unterminated double-quoted string.
err : Module "a" parsing failed.

-------------------------------------------------------------------------
yangDir: cat a.yang
module a {
  namespace "urn:a";
  prefix "a";

  leaf leafB {
          type uint32 ;
          units minutes";
  }
}

yangDir: pyang a.yang
yangDir:

**Comment by fredgan** [comment]
@BalazsLengyel Hi Balazs, you are right. Thanks for reporting. It should be fixed now. Please try with the latest master branch.

**Comment by BalazsLengyel** [comment]
Thanks for the quick response. Awesome!

**Comment by BalazsLengyel** [comment]
This works well, even with my initial bigger file.
