### ISSUE TITLE
pyang flatten options: add dialect for semi-colon separated excel csv

### ISSUE THREAD

**Issue by GermanoSMO** [mbj4668/pyang#705]
Hello 

the --flatten-csv-dialect option currently allows only three choices:

1.  excel -> comma-separated list of elements
2.  excel-tab -> tab-separated list of elements 
3.  unix  -> comma-separated list of quoted elements

But Excel supports also an additional CSV format where elements in a CSV row are separated by semicolon and based on the local system settings this is a possible default format expected to open "nicely" the file, with all fields properly distributed across columns. Currently, an additional conversion of the resulting csv file is needed in order to achieve this result in those cases. 

Adding this choice would allow opening the resulting flattened CSV file natively as well-formatted Excel CSV file without requiring an intermediate off-line format conversion. The suggested request is then to add to the FLATTEN_CSV_DIALECT choice list a new value "excel-semicolon" to produce automatically the alternative CSV format (semicolon-separated list of quoted elements) supported by Excel  

Example for the expected result:

xpath;keyword;flag;type;status
;;;;
/ietf-ptp:ptp;container;rw;nil;current
;;;;
/ietf-ptp:ptp/instance-list;list;rw;nil;current
;;;;
/ietf-ptp:ptp/instance-list/current-ds;container;rw;nil;current

This could be achieved by adding the dialect definition in the flatten.py plugin, e.g. something like:

`csv.register_dialect('excel-semicolon', delimiter=';')`

**Comment by fredgan** [comment]
It seems good. 

Hi @remingtonc , how do you think about this?

**Comment by fredgan** [comment]
Hi @GermanoSMO ,Please view #706 , try with the latest master branch.

**Comment by remingtonc** [comment]
Latent, LGTM :)
