### ISSUE TITLE
Importing a module in submodule of another module is broken in latest branch

### ISSUE THREAD

**Issue by Anukul-Verma-Dev** [mbj4668/pyang#712]
After https://github.com/mbj4668/pyang/commit/8ffe54fc50f02e8d16eca9bb4dc95acc1617b5e7  import issue is seen.

e.g.
module A
  {
      leaf a;
  }

module B
 {

 }

submodule C
{
  belongs-to B;
  
   import A;

   leaf c
   {
      path A:a;
   }
}

With the latest codebase this is broken.
Lint validation gives error for submodule C leaf-c. Module not imported.

Note: When we add a duplicate import of module A in module B it works.

**Comment by fredgan** [comment]
Hi Anukul @Anukul-Verma-Dev 

I tried to normalize your example as follows:

`a.yang`:

```yang
module a{
  prefix ma;
  namespace "urn:ma";

  leaf la{
    type string;
  }
}
```

`b.yang`:

```yang
module b{
  namespace "urn:b";
  prefix mb;

  include sb;
}
```

`sb.yang`:

```yang
submodule sb{
  belongs-to b {
    prefix mb;
  }

  import a {
    prefix ma;
  }

  leaf c{
    type leafref{
      path /ma:la;
    }
  }
}
```

I use command `pyang b.yang`, It shows no error.

Would you please detail it more?

**Comment by Anukul-Verma-Dev** [comment]
pyang --lint b.yang

**Comment by fredgan** [comment]
@Anukul-Verma-Dev Yeah, you are right. @pmerlo74 Would you please look at this issue?

**Comment by pmerlo74** [comment]
Sure - I will have a look.

Please clarify if the example above is sufficient to demonstrate the new issue. With that example I see the following output which looks the same as before the change I made so not sure what I'm missing:

%pyang --lint b.yang
b.yang:1: warning: RFC 8407: 4.1: no module name prefix string used
b.yang:1: error: RFC 8407: 4.8: statement "module" must have a "contact" substatement
b.yang:1: error: RFC 8407: 4.8: statement "module" must have a "organization" substatement
b.yang:1: error: RFC 8407: 4.8: statement "module" must have a "description" substatement
b.yang:1: error: RFC 8407: 4.8: statement "module" must have a "revision" substatement
sb.yang:1: warning: RFC 8407: 4.1: no module name prefix string used
sb.yang:1: error: RFC 8407: 4.8: statement "submodule" must have a "contact" substatement
sb.yang:1: error: RFC 8407: 4.8: statement "submodule" must have a "organization" substatement
sb.yang:1: error: RFC 8407: 4.8: statement "submodule" must have a "description" substatement
sb.yang:1: error: RFC 8407: 4.8: statement "submodule" must have a "revision" substatement
sb.yang:10: error: RFC 8407: 4.14: statement "leaf" must have a "description" substatement

**Comment by fredgan** [comment]
@pmerlo74 The examples are:

`a.yang`:

```yang
module a{
  prefix ma;
  namespace "urn:ma";

  leaf la{
    type string;
  }
}
```

`b.yang`:

```yang
module b{
  namespace "urn:b";
  prefix mb;

  include sb;
  uses gg;
}
```

`sb.yang`:

```yang
submodule sb{
  belongs-to b {
    prefix mb;
  }

  import a {
    prefix ma;
  }

  grouping gg{
    leaf c{
      type leafref{
        path /ma:la;
      }
    }
  }
}
```

Use command `pyang b.yang`, It shows an error after the PR while no error before the PR.

**Comment by fredgan** [comment]
@Anukul-Verma-Dev Hi, it's been fixed now. Please try it again using the latest master branch. Maybe you will have more scenarios to test it.

**Comment by Anukul-Verma-Dev** [comment]
Thanks. Issue is resolved in latest code.
