### ISSUE TITLE
Warning "imported module not used" when using grouping

### ISSUE THREAD

**Issue by eericso** [mbj4668/pyang#718]
We get the following PYANG warning for our YANG modules:

[PYANG] WARNING ericsson-gnbcucp-radio.yang:14 imported module "ericsson-yang-types" not used
[PYANG] WARNING ericsson-gnbcuup-radio.yang:14 imported module "ericsson-yang-types" not used
[PYANG] WARNING ericsson-gnbdu-radio.yang:14 imported module "ericsson-yang-types" not used

It looks like the problem is that we get this warning when the leaf (that uses the import) is inside a grouping.

In all our three modules extra-yang-types is imported:

import **ericsson-yang-types** {
  prefix **typese**;
}

It is used in many places in the modules, e.g.

**grouping ExampleGrp** {
  leaf operationalState {
    description
      "...";
    mandatory true;
    config false;
    type **typese**:oper-state;
    reference
      "abc";
  }
}

list ExampleCell {
  key id;
  ...

  leaf id {
    ...
  }
  container attributes {
    **uses ExampleGrp**;
  }
}

**Comment by fredgan** [comment]
Hi @eericso 

I try to reproduce your case using the following examples.
`pyang a.yang`

However, no warning reported like yours. Would you mind looking at these yang files whether they are what you are describing?

`atype.yang`
```yang
module atype{
  prefix mt;
  namespace "urn:mt";

  typedef ttype{
    type uint8;
  }
}
```

`a.yang`
```yang
module a{
  prefix ma;
  namespace "urn:a";

  import atype{
    prefix ta;
  }

  grouping gg{
    leaf ga{
      type ta:ttype;
    }
  }

  container cc{
    uses gg;
  }
}
```

**Comment by eericso** [comment]
Hi,

Sorry for late response but I have now checked and I have tried to use your example and I don't get any warning either with your example but if I add a description (in leaf ga), then I get the warning. Try this:

a.yang
```
module a {
  prefix ma;
  namespace "urn:a";

  import atype {
    prefix ta;
  }

  grouping gg {
    leaf ga {
      description "";
      type ta:ttype;
    }
  }

  container dd {
      uses gg;
  }
}
```

[PYANG] WARNING a.yang:5 imported module "atype" not used

Regards
/Daniel

**Comment by fredgan** [comment]
Hi Daniel @eericso ,
Unfortunately, I don't get the warning.
BTW, which version are you using?

**Comment by eericso** [comment]
pyang 2.4.0

**Comment by mbj4668** [comment]
It seems this issue has been fixed in recent versions of pyang.
