### ISSUE TITLE
How to generate the code for given yang model

### ISSUE THREAD

**Issue by ravikumar1907** [mbj4668/pyang#723]
Hi
As description says, API code can be generated  using pyang.  If true what would be input parameters. Some example would be more helpful.

**Comment by mbj4668** [comment]
This was not a correct description, I will fix it.  It can be used to write plugins that do code generation.

**Comment by ravikumar1907** [comment]
> This was not a correct description, I will fix it. It can be used to write plugins that do code generation.

Any help to write the plugins to generate code. Some sample example if it is there?

**Comment by fredgan** [comment]
@ravikumar1907 
Hi, In fact, there's a example plugin called [pyangbind](https://github.com/robshakir/pyangbind), which is used to generate python code. You can reference it.
