### ISSUE TITLE
YANG to XSD

### ISSUE THREAD

**Issue by jlost** [mbj4668/pyang#761]
Hi, the README suggests Pyang can convert YANG to XSD, but I don't see xsd in `pyang/translators`, nor do I see it anywhere in the docs. As I was reading issues, I saw it mentioned that this functionality is unmaintained and doesn't really work. Was it since removed? Are there any plans to get it working again? If not, it should probably be removed from the README.

**Comment by mbj4668** [comment]
Thanks, now fixed.
The XSD translation didn't really work, so the plugin was removed.
