### ISSUE TITLE
When is the i_config attribute set?

### ISSUE THREAD

**Issue by wlupton** [mbj4668/pyang#789]
I am writing a plugin that adds a validator:
```
statements.add_validation_fun('strict', ['must'], validator)
```

In the validator I want to check whether the parent node is configurable. From a brief look at the `tree` code I think I need to look at the `i_config` attribute, but it doesn't always exist, and I ended up doing this:
```
getattr(stmt.parent, 'i_config', None)
```

Is this correct, what governs whether `i_config` is set, and is there a best practice that I should follow? Thanks.

Note:
* It seems that `i_config` is not set within `rpc` / `action` trees (which makes sense)
* How does `tree` avoid getting an error when visiting a node without `i_config`?

**Comment by mbj4668** [comment]
Den fre 14 jan. 2022 kl 11:23 skrev William Lupton ***@***.***
>:

> I am writing a plugin that adds a validator:
>
> statements.add_validation_fun('strict', ['must'], validator)
>
> In the validator I want to check whether the parent node is configurable.
> From a brief look at the tree code I think I need to look at the i_config
> attribute, but it doesn't always exist, and I ended up doing this:
>
> getattr(stmt.parent, 'i_config', None)
>
> Is this correct, what governs whether i_config is set, and is there a
> best practice that I should follow? Thanks.
>
It is set in the 'inherit_properties' phase so it should be ok check in
'strict'.
As for which nodes has it, see v_inherit_properties.  Using None if not set
seems correct.



> Note:
>
>    - It seems that i_config is not set within rpc / action trees (which
>    makes sense)
>    - How does tree avoid getting an error when visiting a node without
>    i_config?
>
> Pure luck, perhaps ;-)   It seems it checks other properties before it
checks `i_config`.


/martin

**Comment by wlupton** [comment]
Thanks!
