### ISSUE TITLE
'strict' validation doesn't visit nodes defined in groupings?

### ISSUE THREAD

**Issue by wlupton** [mbj4668/pyang#804]
We've got a lint-like plugin that adds 'strict' phase validators, but were perplexed that it doesn't seem to visit nodes that are defined in groupings.

After a while we realised that 'strict' validation visits sub-statements rather than child nodes, so it descends into the groupings rather than into the nodes that have been expanded from the groupings.

The 'fix' is to use the 'reference_2' phase rather than 'strict' but:
* Is this intentional behaviour?
* Could there perhaps be a more obviously-named phase that will visit child nodes?

**Comment by mbj4668** [comment]
Yes this is intentional.  The dict `_v_i_children` defines which phases are run over the expanded nodes.

A plugin can add its own phases with `add_validation_phase()`, and use `set_phase_i_children()` to make it run over the expanded nodes.

**Comment by wlupton** [comment]
ok; thanks!
