### ISSUE TITLE
warning: how to resolve!!!

### ISSUE THREAD

**Issue by SysAdminOkuns** [mbj4668/pyang#817]
warning: failed to load external entity "/home/myuser/pyang/xslt/basename.xsl/basename.xsl"
cannot parse /home/user/pyang/xslt/basename.xsl/basename.xsl

**Comment by llhotka** [comment]
What is the value of the environment variable `PYANG_XSLT_DIR`?

**Comment by SysAdminOkuns** [comment]
> What is the value of the environment variable `PYANG_XSLT_DIR`?

Hello, thanks for your assistance. I tried export PYANG_XSLT_DIR=$HOME/pyang/xslt/basename.xsl in the .bashrc file but it didn't work. Let me know if there's a way around this.

**Comment by llhotka** [comment]
This variable has to point to the **directory** containing XSLT stylesheets, hence
```bash
export PYANG_XSLT_DIR=$HOME/pyang/xslt
```

**Comment by SysAdminOkuns** [comment]
Thanks
