### ISSUE TITLE
html typo in jstree 

### ISSUE THREAD

**Issue by nicetiger** [mbj4668/pyang#821]
Shouldn't it be "<**abbr** ...>" instead of <**attr** ...> in jstree.py line 464?
https://github.com/mbj4668/pyang/blob/1865311ef8a88efaaf6b26a9ed7476bb5128b9be/pyang/plugins/jstree.py#L464

**Comment by fredgan** [comment]
@nicetiger Hi, yeah, you are right. Thanks. I will submit a PR to fix this.
