### ISSUE TITLE
Line wraps around column 70, regardless of options

### ISSUE THREAD

**Issue by mjethanandani** [mbj4668/pyang#844]
pyang offers an option to limit tree line length to a certain value, called --tree-line-length. However, regardless of what value is given to it, it seems to default value of 70 columns.

```
                |  +--ro neighbors
                |     +--ro neighbor* [neighbor-address]
                |        +--ro neighbor-address    inet:ip-address
                |        +--ro adj-rib-in-pre
                |        |  +--ro routes
                |        |  |  +--ro route* [prefix path-id]
                |        |  |     +--ro prefix
                |        |  |     |       inet:ipv4-prefix
                |        |  |     +--ro path-id
                |        |  |     |       uint32
                |        |  |     +--ro attr-index?              leafre
f
```
Even if the above line wrap may not be desirable, there is no way (it seems) to prevent this line wrap.

The complete command issued is the following:

`pyang --ietf --strict --canonical -p ../bin/yang-parameters -p ../bin/submodules -p ../bin -f tree --max-line-length=72 --tree-line-length=69 $name.yang > $name-tree.txt`

The version of pyang is 2.5.3.

**Comment by mbj4668** [comment]
Can you include the module?  I have tried with various modules and it seems to produce correct result.
