### ISSUE TITLE
pyang yang augment issue

### ISSUE THREAD

**Issue by kirankotari** [mbj4668/pyang#871]
Here, In the yang model with an action in grouping, when it's uses I am adding new leaf to my action inputs, this is achieved by augment <action-name/input>. The pyang couldn't find the action-name, but yang model is working as expected.

<img width="662" alt="Screenshot 2023-07-08 at 10 00 27" src="https://github.com/mbj4668/pyang/assets/1794046/4aeda0df-f150-4fc0-9b64-220bdab00949">
<img width="659" alt="Screenshot 2023-07-08 at 10 00 48" src="https://github.com/mbj4668/pyang/assets/1794046/4e70d471-0cc6-4036-a554-18cbe5ab6dd0">
Note:- both of them are in a same file.

**Comment by mbj4668** [comment]
tailf:action cannot be augumented, but the YANG 1.1 standard action can.
