### ISSUE TITLE
--ieee flag produces an incorrect warning message related to module name

### ISSUE THREAD

**Issue by samans** [mbj4668/pyang#893]
When using the --ieee flag there are warnings on all modules from IEEE 802, IEEE 802.1, and IEEE 802.3 modules:

warning: RFC 8407: 4.1: the module name should start with the string "ieee-"

The naming guidelines used by IEEE 802.1, IEEE 802.3, and IEEE 1588 are found here:  https://1.ieee802.org/yangsters/yangsters-guidelines/yang-module-naming-guidelines/

The modules start with either "ieee802-" or "ieee1588-".

Not a big deal, but as we have more YANG developers now, it would reduce concern to get this --ieee check updated.

**Comment by mbj4668** [comment]
Fixed in 4f271ff
