### ISSUE TITLE
Publish release 2.6.1 please?

### ISSUE THREAD

**Issue by rgwilton** [mbj4668/pyang#908]
Hi Martin,

If you get some spare minutes, would it be possible to publish as 2.6.1 release that includes the fix for https://github.com/mbj4668/pyang/issues/884 please?  This is already on the main branch in the repo, but folks using a regular install are tripping over this.

Regards,
Rob

**Comment by mbj4668** [comment]
Done. I have some issues w/ PyPi, but hopefully it is resolved soon.
